# Generated by Django 5.1.1 on 2025-02-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='service_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(choices=[('PROPERTY_OWNER', 'Property Owner'), ('SERVICE_PROVIDER', 'Service Provider'), ('STAFF', 'Hestami AI Staff'), ('SERVICE_ACCOUNT', 'Service Account')], max_length=20),
        ),
    ]
