# Generated by Django 5.1.1 on 2025-04-25 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_remove_serviceprovider_users'),
        ('users', '0002_user_service_token_alter_user_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='services.serviceprovider'),
        ),
    ]
