# Generated by Django 5.1.1 on 2025-04-25 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_serviceresearch_service_provider_created'),
        ('users', '0003_user_service_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='service_provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='services.serviceprovider'),
        ),
    ]
