# Generated by Django 5.1.1 on 2025-11-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_service_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='librechat_password_encrypted',
            field=models.CharField(blank=True, help_text='Encrypted password for LibreChat authentication', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='librechat_synced_at',
            field=models.DateTimeField(blank=True, help_text='Last successful sync with LibreChat', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='librechat_user_id',
            field=models.CharField(blank=True, help_text='LibreChat internal user ID', max_length=255, null=True),
        ),
    ]
