import type { LensPhaseManifest } from '../../lib/orchestrator/types.js';
import { SHARED_AGENTS } from '../sharedAgents.js';

export const LEGAL_RESEARCH_MEMO_LENS_ID = 'legal_research_memo_lens';

export const legalResearchMemoManifest: LensPhaseManifest = {
  lensId: LEGAL_RESEARCH_MEMO_LENS_ID,
  lensVersion: 'v1',
  practiceArea: 'legal_research',
  applicableJurisdictions: ['MD', 'VA', 'PA', 'DC', 'US'],
  states: [
    {
      stateId: 'ResearchQuestionNormalize',
      required: true,
      predecessors: [],
      permittedAgents: [SHARED_AGENTS.intakeNormalize],
      inputSchema: 'ResearchQuestionInput.v1',
      outputSchema: 'NormalizedResearchQuestion.v1',
      validators: [],
      escalationConditions: [],
      clvScope: ['clv.core.matter.v1', 'clv.core.issue.v1'],
      artifactsProduced: [],
    },
    {
      stateId: 'JurisdictionCapture',
      required: true,
      predecessors: ['ResearchQuestionNormalize'],
      permittedAgents: [SHARED_AGENTS.jurisdictionCapture],
      inputSchema: 'JurisdictionCaptureInput.v1',
      outputSchema: 'JurisdictionCaptureOutput.v1',
      validators: [],
      escalationConditions: [],
      clvScope: ['clv.core.matter.v1'],
      artifactsProduced: [],
    },
    {
      stateId: 'AuthorityRetrieve',
      required: true,
      predecessors: ['JurisdictionCapture'],
      permittedAgents: [SHARED_AGENTS.authorityRetrieve],
      inputSchema: 'AuthorityRetrieveInput.v1',
      outputSchema: 'AuthorityRetrieveOutput.v1',
      validators: [],
      escalationConditions: [],
      clvScope: ['clv.core.authority.v1', 'clv.core.citation.v1'],
      artifactsProduced: [],
    },
    {
      stateId: 'DraftMemoGenerate',
      required: true,
      predecessors: ['AuthorityRetrieve'],
      permittedAgents: [SHARED_AGENTS.researchMemoDraft],
      inputSchema: 'ResearchMemoDraftInput.v1',
      outputSchema: 'ResearchMemoDraftOutput.v1',
      validators: [],
      escalationConditions: [],
      clvScope: ['clv.core.work_product.v1', 'clv.core.conclusion.v1'],
      artifactsProduced: ['research_memo_draft'],
    },
    {
      stateId: 'AuthorityVerification',
      required: true,
      predecessors: ['DraftMemoGenerate'],
      permittedAgents: [SHARED_AGENTS.authorityVerification],
      inputSchema: 'AuthorityVerificationInput.v1',
      outputSchema: 'AuthorityVerificationOutput.v1',
      validators: [],
      escalationConditions: [],
      clvScope: ['clv.core.authority.v1', 'clv.core.machine_assessed_support.v1'],
      artifactsProduced: [],
    },
    {
      stateId: 'ReleaseStatusDetermine',
      required: true,
      predecessors: ['AuthorityVerification'],
      permittedAgents: [SHARED_AGENTS.releaseStatusDetermine],
      inputSchema: 'ReleaseStatusInput.v1',
      outputSchema: 'ReleaseStatusOutput.v1',
      validators: [],
      escalationConditions: [],
      clvScope: ['clv.core.release.v1', 'clv.core.gate.v1'],
      artifactsProduced: [],
    },
  ],
  requiredArtifacts: [{ artifactType: 'research_memo_draft', schema: 'ResearchMemoDraftOutput.v1' }],
  validators: [],
  escalationTriggers: [],
  releasePolicies: [],
  clvBindings: [
    'clv.core.matter.v1',
    'clv.core.issue.v1',
    'clv.core.authority.v1',
    'clv.core.citation.v1',
    'clv.core.work_product.v1',
    'clv.core.conclusion.v1',
    'clv.core.machine_assessed_support.v1',
    'clv.core.release.v1',
    'clv.core.gate.v1',
  ],
  dependencies: [],
};
