name: hestami-ai-prod

networks:
  traefik-public:
    name: traefik-public
    external: true
    driver: bridge
  backend-dev:
    name: backend-dev
    external: true
    driver: bridge
  backend-prod:
    name: backend-prod
    external: true
    driver: bridge

volumes:
  hestami_media_data_prod:
  postgres_data_prod:

services:
  init-volumes:
    image: busybox
    container_name: init-volumes-prod
    volumes:
      - "hestami_media_data_prod:/mnt/hestami-static:rw"
    command: >
      /bin/sh -c "mkdir -p /mnt/hestami-static/media /mnt/hestami-static/static &&
      chown -R 999:999 /mnt/hestami-static &&
      chmod -R 775 /mnt/hestami-static"
    runtime: runc

  frontend:
    build: 
      context: .
      dockerfile: ./docker/frontend/sveltekit/Dockerfile
      args:
        ENV_NPM_BUILD_FILE: ./.env.prod
    env_file:
      - ./.env.prod
    deploy:
      resources:
        limits:
          memory: 4G  # Production: allow more concurrent uploads
        reservations:
          memory: 1G  # Base memory for app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`homeservices.hestami-ai.com`)"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
      # Enable request buffering for large uploads
      - "traefik.http.middlewares.frontend-buffering.buffering.maxRequestBodyBytes=104857600"  # 100MB
      - "traefik.http.middlewares.frontend-buffering.buffering.memRequestBodyBytes=104857600"  # 100MB in memory
      - "traefik.http.routers.frontend.middlewares=frontend-buffering"
    networks:
      - traefik-public
      - backend-prod
    depends_on:
      - api
      - static
    restart: unless-stopped
    runtime: runc
    logging:
      driver: "local"
      options:
        max-size: "20m"
        max-file: "5"

  api:
    build: 
      context: .
      dockerfile: ./docker/backend/django/Dockerfile
    command: python manage.py runserver 0.0.0.0:8050
    volumes:
      - "hestami_media_data_prod:/mnt/hestami-static:rw"
    #ports:
    #  - 8050:8050
    env_file:
      - ./.env.prod
    depends_on:
      - db
      - redis
      - clamav
      - static
      - init-volumes
    networks:
      - backend-prod
    restart: unless-stopped
    runtime: runc
    logging:
      driver: "local"
      options:
        max-size: "20m"
        max-file: "5"

  db:
    image: postgres:17
    env_file:
      - ./.env.prod
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    networks:
      - backend-prod
    restart: unless-stopped
    runtime: runc
    logging:
      driver: "local"
      options:
        max-size: "20m"
        max-file: "5"

  static:
    build: 
      context: .
      dockerfile: ./docker/backend/static/Dockerfile
    volumes:
      - "./volumes/prod/static/templates/etc/nginx:/templates/etc/nginx:ro"
      - "hestami_media_data_prod:/usr/share/nginx/html/:ro"
    env_file:
      - ./.env.prod
    command: >
      /bin/sh -c "envsubst '$$NGINX_SECURE_LINK_SECRET' < /templates/etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf 
      && exec nginx -g 'daemon off;'"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.hestamistatic.rule=Host(`static.hestami-ai.com`)"
      - "traefik.http.routers.hestamistatic.tls=true"
      - "traefik.http.services.hestamistatic.loadbalancer.server.port=80"
    networks:
      - traefik-public
    restart: unless-stopped
    runtime: runc
    logging:
      driver: "local"
      options:
        max-size: "20m"
        max-file: "5"

  redis:
    image: redis:8.0-M02-alpine3.20
    #ports:
    #  - "6379:6379"
    networks:
      - backend-prod
    restart: unless-stopped
    runtime: runc
    logging:
      driver: "local"
      options:
        max-size: "20m"
        max-file: "5"

  clamav:
    image: clamav/clamav:latest
    container_name: clamav
    #ports:
    #  - "3310:3310"
    environment:
      - CLAMAV_NO_MILTERD=true
    networks:
      - backend-prod
    restart: unless-stopped
    runtime: runc
    logging:
      driver: "local"
      options:
        max-size: "20m"
        max-file: "5"