# LibreChat Integration with Hestami AI Backend Network
# 
# This file extends the LibreChat docker-compose.yml to connect it to the
# Hestami AI backend network, allowing Django and SvelteKit to communicate
# with LibreChat.
#
# Usage:
#   Development: docker-compose -f backend/LibreChat-main/docker-compose.yml -f compose.librechat.yaml up -d
#   Production:  docker-compose -f backend/LibreChat-main/docker-compose.yml -f compose.librechat.yaml up -d

name: hestami-ai-librechat

networks:
  backend-dev:
    name: backend-dev
    external: true
  backend-prod:
    name: backend-prod
    external: true

services:
  api:
    # Extend the LibreChat API service to join backend network
    networks:
      default:  # Keep LibreChat's internal network
      backend-dev:  # Add to Hestami AI backend network (dev)
        aliases:
          - librechat  # Add unique hostname to avoid conflict with Django's 'api' service
      # backend-prod:  # Uncomment for production
      #   aliases:
      #     - librechat
    
    # Override container name to be more descriptive
    container_name: librechat-api
    
    # Increase rate limits for automated user provisioning and disable bans
    environment:
      - REGISTER_MAX=100        # Allow 100 registrations per window
      - REGISTER_WINDOW=1       # 1 minute window
      - REGISTER_MAX=100
      - REGISTER_WINDOW=1
      - LOGIN_MAX=100
      - LOGIN_WINDOW=1
      - BAN_VIOLATIONS=false    # Disable automatic user banning
      - NON_BROWSER_VIOLATION_SCORE=0  # Allow server-to-server requests
    
    # Add health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${PORT:-3080}/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
