# Generated by Django 5.1.1 on 2024-12-09 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_media', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['uploader', '-upload_date'], name='media_media_uploade_e04f38_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['file_type'], name='media_media_file_ty_a7869c_idx'),
        ),
    ]
