# Generated by Django 5.1.1 on 2025-10-16 20:21

import django.core.validators
import media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_alter_media_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to=media.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'mp4', 'mov', 'md', 'pdf', 'docx', 'txt', 'doc', 'usdz'])]),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_sub_type',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('360_DEGREE', '360 Degree'), ('FLOORPLAN', 'Floorplan'), ('3D_MODEL', '3D Model'), ('DOCUMENT', 'Document'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('3D_MODEL', '3D Model'), ('FILE', 'File'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
