# Generated by Django 5.1.1 on 2025-10-16 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_alter_media_file_alter_media_media_sub_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_sub_type',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('360_DEGREE', '360 Degree'), ('FLOORPLAN', 'Floorplan'), ('USDZ', 'USDZ Model'), ('DOCUMENT', 'Document'), ('OTHER', 'Other')], default='OTHER', max_length=50),
        ),
    ]
