import { readFileSync } from 'node:fs';
import * as publicSurface from '@janumipwb/csaa';
import ts from 'typescript';
import { describe, expect, it } from 'vitest';
import {
	CALL_GRAPH_OPERATION_VERSION,
	CALL_GRAPH_REQUEST_SCHEMA_VERSION,
	CALL_GRAPH_SCHEMA_VERSION,
	CALL_GRAPH_PROGRESS_MAX_BYTES,
	CALL_GRAPH_PROGRESS_MAX_EVENTS,
	CALL_GRAPH_PROGRESS_TRANSPORT_SCHEMA_VERSION,
	CALL_GRAPH_REPORT_OPERATION_VERSION,
	CALL_GRAPH_REPORT_PROGRESS_SCHEMA_VERSION,
	CALL_GRAPH_REPORT_REQUEST_SCHEMA_VERSION,
	CALL_GRAPH_REPORT_RESULT_SCHEMA_VERSION,
	CALL_GRAPH_REPORT_SCHEMA_VERSION,
	CONDITIONAL_EXPORT_RESOLUTION_OPERATION_VERSION,
	CONDITIONAL_EXPORT_RESOLUTION_PROGRESS_SCHEMA_VERSION,
	CONDITIONAL_EXPORT_RESOLUTION_REQUEST_SCHEMA_VERSION,
	CONDITIONAL_EXPORT_RESOLUTION_SCHEMA_VERSION,
	DECLARATION_CONTEXT_ANALYSIS_OPERATION_VERSION,
	DECLARATION_CONTEXT_ANALYSIS_PROGRESS_SCHEMA_VERSION,
	DECLARATION_CONTEXT_ANALYSIS_REQUEST_SCHEMA_VERSION,
	DECLARATION_CONTEXT_ANALYSIS_SCHEMA_VERSION,
	DECLARATION_CONTEXT_PROGRESS_MAX_BYTES,
	DECLARATION_CONTEXT_PROGRESS_MAX_EVENTS,
	DECLARATION_CONTEXT_PROGRESS_TRANSPORT_SCHEMA_VERSION,
	DECLARATION_CONTEXT_REPORT_NONCLAIMS,
	DECLARATION_CONTEXT_REPORT_OPERATION_VERSION,
	DECLARATION_CONTEXT_REPORT_PREDECESSOR_NONCLAIMS,
	DECLARATION_CONTEXT_REPORT_PROGRESS_NONCLAIMS,
	DECLARATION_CONTEXT_REPORT_PROGRESS_SCHEMA_VERSION,
	DECLARATION_CONTEXT_REPORT_REQUEST_SCHEMA_VERSION,
	DECLARATION_CONTEXT_REPORT_RESULT_SCHEMA_VERSION,
	DECLARATION_CONTEXT_REPORT_SCHEMA_VERSION,
	DECLARATION_CONTEXT_REPORT_SELECTION,
	SOURCE_ORIGIN_CORRELATION_OPERATION_VERSION,
	SOURCE_ORIGIN_CORRELATION_PROGRESS_SCHEMA_VERSION,
	SOURCE_ORIGIN_CORRELATION_REQUEST_SCHEMA_VERSION,
	SOURCE_ORIGIN_CORRELATION_SCHEMA_VERSION,
	COMMAND_HANDLER_GRAPH_OPERATION_VERSION,
	COMMAND_HANDLER_GRAPH_PROGRESS_MAX_BYTES,
	COMMAND_HANDLER_GRAPH_PROGRESS_MAX_EVENTS,
	COMMAND_HANDLER_GRAPH_PROGRESS_SCHEMA_VERSION,
	COMMAND_HANDLER_GRAPH_PROGRESS_TRANSPORT_SCHEMA_VERSION,
	COMMAND_HANDLER_GRAPH_REPORT_OPERATION_VERSION,
	COMMAND_HANDLER_GRAPH_REPORT_PROGRESS_SCHEMA_VERSION,
	COMMAND_HANDLER_GRAPH_REPORT_REQUEST_SCHEMA_VERSION,
	COMMAND_HANDLER_GRAPH_REPORT_RESULT_SCHEMA_VERSION,
	COMMAND_HANDLER_GRAPH_REPORT_SCHEMA_VERSION,
	COMMAND_HANDLER_GRAPH_REPORT_SCOPE,
	COMMAND_HANDLER_GRAPH_REQUEST_SCHEMA_VERSION,
	COMMAND_HANDLER_GRAPH_SCHEMA_VERSION,
	COMMAND_DISPATCH_TOPOLOGY_PROGRESS_MAX_BYTES,
	COMMAND_DISPATCH_TOPOLOGY_PROGRESS_MAX_EVENTS,
	COMMAND_DISPATCH_TOPOLOGY_PROGRESS_SCHEMA_VERSION,
	COMMAND_DISPATCH_TOPOLOGY_PROGRESS_TRANSPORT_SCHEMA_VERSION,
	COMMAND_DISPATCH_TOPOLOGY_REPORT_OPERATION_VERSION,
	COMMAND_DISPATCH_TOPOLOGY_REPORT_PROGRESS_SCHEMA_VERSION,
	COMMAND_DISPATCH_TOPOLOGY_REPORT_REQUEST_SCHEMA_VERSION,
	COMMAND_DISPATCH_TOPOLOGY_REPORT_RESULT_SCHEMA_VERSION,
	COMMAND_DISPATCH_TOPOLOGY_REPORT_SCHEMA_VERSION,
	COMMAND_DISPATCH_TOPOLOGY_REPORT_SCOPE,
	COMMAND_EVENT_CONTRACT_OVERLAY_OPERATION_VERSION,
	COMMAND_EVENT_CONTRACT_OVERLAY_PROGRESS_MAX_BYTES,
	COMMAND_EVENT_CONTRACT_OVERLAY_PROGRESS_MAX_EVENTS,
	COMMAND_EVENT_CONTRACT_OVERLAY_PROGRESS_SCHEMA_VERSION,
	COMMAND_EVENT_CONTRACT_OVERLAY_PROGRESS_TRANSPORT_SCHEMA_VERSION,
	COMMAND_EVENT_CONTRACT_OVERLAY_REPORT_OPERATION_VERSION,
	COMMAND_EVENT_CONTRACT_OVERLAY_REPORT_PROGRESS_SCHEMA_VERSION,
	COMMAND_EVENT_CONTRACT_OVERLAY_REPORT_REQUEST_SCHEMA_VERSION,
	COMMAND_EVENT_CONTRACT_OVERLAY_REPORT_RESULT_SCHEMA_VERSION,
	COMMAND_EVENT_CONTRACT_OVERLAY_REPORT_SCHEMA_VERSION,
	COMMAND_EVENT_CONTRACT_OVERLAY_REPORT_SCOPE,
	COMMAND_EVENT_CONTRACT_OVERLAY_REPORT_SELECTION,
	COMMAND_EVENT_CONTRACT_OVERLAY_REQUEST_SCHEMA_VERSION,
	COMMAND_EVENT_CONTRACT_OVERLAY_SCHEMA_VERSION,
	GUARD_CLASSIFICATION_OVERLAY_OPERATION_VERSION,
	GUARD_CLASSIFICATION_OVERLAY_PROGRESS_MAX_BYTES,
	GUARD_CLASSIFICATION_OVERLAY_PROGRESS_MAX_EVENTS,
	GUARD_CLASSIFICATION_OVERLAY_PROGRESS_SCHEMA_VERSION,
	GUARD_CLASSIFICATION_OVERLAY_PROGRESS_TRANSPORT_SCHEMA_VERSION,
	GUARD_CLASSIFICATION_OVERLAY_REPORT_OPERATION_VERSION,
	GUARD_CLASSIFICATION_OVERLAY_REPORT_PROGRESS_SCHEMA_VERSION,
	GUARD_CLASSIFICATION_OVERLAY_REPORT_REQUEST_SCHEMA_VERSION,
	GUARD_CLASSIFICATION_OVERLAY_REPORT_RESULT_SCHEMA_VERSION,
	GUARD_CLASSIFICATION_OVERLAY_REPORT_SCHEMA_VERSION,
	GUARD_CLASSIFICATION_OVERLAY_REPORT_SCOPE,
	GUARD_CLASSIFICATION_OVERLAY_REPORT_SELECTION,
	GUARD_CLASSIFICATION_OVERLAY_REPORT_STATE_SOURCE,
	GUARD_CLASSIFICATION_OVERLAY_REQUEST_SCHEMA_VERSION,
	GUARD_CLASSIFICATION_OVERLAY_SCHEMA_VERSION,
	GUARD_ENFORCEMENT_LEDGER_OPERATION_VERSION,
	GUARD_ENFORCEMENT_LEDGER_PROGRESS_MAX_BYTES,
	GUARD_ENFORCEMENT_LEDGER_PROGRESS_MAX_EVENTS,
	GUARD_ENFORCEMENT_LEDGER_PROGRESS_SCHEMA_VERSION,
	GUARD_ENFORCEMENT_LEDGER_PROGRESS_TRANSPORT_SCHEMA_VERSION,
	GUARD_ENFORCEMENT_LEDGER_REPORT_ADMISSION_LIMITS,
	GUARD_ENFORCEMENT_LEDGER_REPORT_OPERATION_VERSION,
	GUARD_ENFORCEMENT_LEDGER_REPORT_PROGRESS_SCHEMA_VERSION,
	GUARD_ENFORCEMENT_LEDGER_REPORT_REQUEST_SCHEMA_VERSION,
	GUARD_ENFORCEMENT_LEDGER_REPORT_RESULT_SCHEMA_VERSION,
	GUARD_ENFORCEMENT_LEDGER_REPORT_SCHEMA_VERSION,
	GUARD_ENFORCEMENT_LEDGER_SCHEMA_VERSION,
	LOGICAL_GRAPH_COMPOSITION_OPERATION_VERSION,
	LOGICAL_GRAPH_COMPOSITION_PROGRESS_SCHEMA_VERSION,
	LOGICAL_GRAPH_COMPOSITION_REQUEST_SCHEMA_VERSION,
	LOGICAL_GRAPH_COMPOSITION_SCHEMA_VERSION,
	PROJECT_CONTEXT_GRAPH_OPERATION_VERSION,
	PROJECT_CONTEXT_GRAPH_PROGRESS_SCHEMA_VERSION,
	PROJECT_CONTEXT_GRAPH_REQUEST_SCHEMA_VERSION,
	PROJECT_CONTEXT_GRAPH_SCHEMA_VERSION,
	PROJECT_CONTEXT_PROGRESS_MAX_BYTES,
	PROJECT_CONTEXT_PROGRESS_MAX_EVENTS,
	PROJECT_CONTEXT_PROGRESS_TRANSPORT_SCHEMA_VERSION,
	PROJECT_CONTEXT_REPORT_NONCLAIMS,
	PROJECT_CONTEXT_REPORT_OPERATION_VERSION,
	PROJECT_CONTEXT_REPORT_PROGRESS_NONCLAIMS,
	PROJECT_CONTEXT_REPORT_PROGRESS_SCHEMA_VERSION,
	PROJECT_CONTEXT_REPORT_REQUEST_SCHEMA_VERSION,
	PROJECT_CONTEXT_REPORT_RESULT_SCHEMA_VERSION,
	PROJECT_CONTEXT_REPORT_SCHEMA_VERSION,
	READ_WRITE_ACCESS_GRAPH_OPERATION_VERSION,
	READ_WRITE_ACCESS_GRAPH_REQUEST_SCHEMA_VERSION,
	READ_WRITE_ACCESS_GRAPH_SCHEMA_VERSION,
	READ_WRITE_ACCESS_PROGRESS_MAX_BYTES,
	READ_WRITE_ACCESS_PROGRESS_MAX_EVENTS,
	READ_WRITE_ACCESS_PROGRESS_TRANSPORT_SCHEMA_VERSION,
	READ_WRITE_ACCESS_REPORT_OPERATION_VERSION,
	READ_WRITE_ACCESS_REPORT_PROGRESS_SCHEMA_VERSION,
	READ_WRITE_ACCESS_REPORT_REQUEST_SCHEMA_VERSION,
	READ_WRITE_ACCESS_REPORT_RESULT_SCHEMA_VERSION,
	READ_WRITE_ACCESS_REPORT_SCHEMA_VERSION,
	ARROW_COMMAND_CENSUS_OBSERVATION_SCHEMA_VERSION,
	ARROW_COMMAND_CENSUS_OPERATION_VERSION,
	ARROW_COMMAND_CENSUS_PROGRESS_MAX_BYTES,
	ARROW_COMMAND_CENSUS_PROGRESS_MAX_EVENTS,
	ARROW_COMMAND_CENSUS_PROGRESS_SCHEMA_VERSION,
	ARROW_COMMAND_CENSUS_PROGRESS_TRANSPORT_SCHEMA_VERSION,
	ARROW_COMMAND_CENSUS_REPORT_ADMISSION_LIMITS,
	ARROW_COMMAND_CENSUS_REPORT_OPERATION_VERSION,
	ARROW_COMMAND_CENSUS_REPORT_PROGRESS_SCHEMA_VERSION,
	ARROW_COMMAND_CENSUS_REPORT_REQUEST_SCHEMA_VERSION,
	ARROW_COMMAND_CENSUS_REPORT_RESULT_SCHEMA_VERSION,
	ARROW_COMMAND_CENSUS_REPORT_SCHEMA_VERSION,
	DEPENDENCY_CRUISER_NORMALIZATION_OPERATION_VERSION,
	DEPENDENCY_CRUISER_PROVIDER_VERSION,
	DEPENDENCY_PROVIDER_COMPARISON_OPERATION_VERSION,
	MODULE_DEPENDENCY_GRAPH_CANONICAL_PROFILE,
	MODULE_DEPENDENCY_GRAPH_OPERATION_VERSION,
	MODULE_DEPENDENCY_GRAPH_REQUEST_SCHEMA_VERSION,
	MODULE_DEPENDENCY_GRAPH_SCHEMA_VERSION,
	MODULE_DEPENDENCY_PROGRESS_MAX_BYTES,
	MODULE_DEPENDENCY_PROGRESS_MAX_EVENTS,
	MODULE_DEPENDENCY_PROGRESS_TRANSPORT_SCHEMA_VERSION,
	MODULE_DEPENDENCY_REPORT_OPERATION_VERSION,
	MODULE_DEPENDENCY_REPORT_PROGRESS_SCHEMA_VERSION,
	MODULE_DEPENDENCY_REPORT_REQUEST_SCHEMA_VERSION,
	MODULE_DEPENDENCY_REPORT_RESULT_SCHEMA_VERSION,
	MODULE_DEPENDENCY_REPORT_SCHEMA_VERSION,
	MODULE_RESOLUTION_TRACE_OPERATION_VERSION,
	MODULE_RESOLUTION_TRACE_PROGRESS_SCHEMA_VERSION,
	MODULE_RESOLUTION_TRACE_REQUEST_SCHEMA_VERSION,
	MODULE_RESOLUTION_TRACE_SCHEMA_VERSION,
	MODULE_RESOLUTION_TRACE_PROGRESS_MAX_BYTES,
	MODULE_RESOLUTION_TRACE_PROGRESS_MAX_EVENTS,
	MODULE_RESOLUTION_TRACE_PROGRESS_TRANSPORT_SCHEMA_VERSION,
	MODULE_RESOLUTION_TRACE_REPORT_NONCLAIMS,
	MODULE_RESOLUTION_TRACE_REPORT_OPERATION_VERSION,
	MODULE_RESOLUTION_TRACE_REPORT_PREDECESSOR_NONCLAIMS,
	MODULE_RESOLUTION_TRACE_REPORT_PROGRESS_NONCLAIMS,
	MODULE_RESOLUTION_TRACE_REPORT_PROGRESS_SCHEMA_VERSION,
	MODULE_RESOLUTION_TRACE_REPORT_REQUEST_SCHEMA_VERSION,
	MODULE_RESOLUTION_TRACE_REPORT_RESULT_SCHEMA_VERSION,
	MODULE_RESOLUTION_TRACE_REPORT_SCHEMA_VERSION,
	MODULE_RESOLUTION_TRACE_REPORT_SELECTION,
	SEMANTIC_EXTRACTION_VERSION,
	SEMANTIC_OPERATION_VERSION,
	SEMANTIC_REQUEST_SCHEMA_VERSION,
	SEMANTIC_SNAPSHOT_SCHEMA_VERSION,
	STATIC_SEMANTIC_SNAPSHOT_PROGRESS_SCHEMA_VERSION,
	STATE_MACHINE_GRAPH_OPERATION_VERSION,
	STATE_MACHINE_GRAPH_PROGRESS_MAX_BYTES,
	STATE_MACHINE_GRAPH_PROGRESS_MAX_EVENTS,
	STATE_MACHINE_GRAPH_PROGRESS_TRANSPORT_SCHEMA_VERSION,
	STATE_MACHINE_GRAPH_REQUEST_SCHEMA_VERSION,
	STATE_MACHINE_GRAPH_REPORT_OPERATION_VERSION,
	STATE_MACHINE_GRAPH_REPORT_PROGRESS_SCHEMA_VERSION,
	STATE_MACHINE_GRAPH_REPORT_REQUEST_SCHEMA_VERSION,
	STATE_MACHINE_GRAPH_REPORT_RESULT_SCHEMA_VERSION,
	STATE_MACHINE_GRAPH_REPORT_SCHEMA_VERSION,
	STATE_MACHINE_GRAPH_SCHEMA_VERSION,
	STRUCTURAL_MODULE_REACHABILITY_ANALYSIS_OPERATION_VERSION,
	STRUCTURAL_MODULE_REACHABILITY_ANALYSIS_REQUEST_SCHEMA_VERSION,
	STRUCTURAL_MODULE_REACHABILITY_ANALYSIS_SCHEMA_VERSION,
	STRUCTURAL_MODULE_REACHABILITY_REPORT_OPERATION_VERSION,
	STRUCTURAL_MODULE_REACHABILITY_REPORT_NONCLAIMS,
	STRUCTURAL_MODULE_REACHABILITY_REPORT_PROGRESS_NONCLAIMS,
	STRUCTURAL_MODULE_REACHABILITY_REPORT_PROGRESS_SCHEMA_VERSION,
	STRUCTURAL_MODULE_REACHABILITY_REPORT_REQUEST_SCHEMA_VERSION,
	STRUCTURAL_MODULE_REACHABILITY_REPORT_SCHEMA_VERSION,
	STRUCTURAL_MODULE_REACHABILITY_PROGRESS_MAX_BYTES,
	STRUCTURAL_MODULE_REACHABILITY_PROGRESS_MAX_EVENTS,
	STRUCTURAL_MODULE_REACHABILITY_PROGRESS_TRANSPORT_SCHEMA_VERSION,
	STRUCTURAL_SCC_ANALYSIS_OPERATION_VERSION,
	STRUCTURAL_SCC_ANALYSIS_REQUEST_SCHEMA_VERSION,
	STRUCTURAL_SCC_ANALYSIS_SCHEMA_VERSION,
	STRUCTURAL_SCC_REPORT_NONCLAIMS,
	STRUCTURAL_SCC_REPORT_OPERATION_VERSION,
	STRUCTURAL_SCC_REPORT_PROGRESS_NONCLAIMS,
	STRUCTURAL_SCC_REPORT_PROGRESS_SCHEMA_VERSION,
	STRUCTURAL_SCC_REPORT_REQUEST_SCHEMA_VERSION,
	STRUCTURAL_SCC_REPORT_SCHEMA_VERSION,
	STRUCTURAL_SCC_PROGRESS_MAX_BYTES,
	STRUCTURAL_SCC_PROGRESS_MAX_EVENTS,
	STRUCTURAL_SCC_PROGRESS_TRANSPORT_SCHEMA_VERSION,
	STATE_MACHINE_TOPOLOGY_OBSERVATION_OPERATION_VERSION,
	STATE_MACHINE_TOPOLOGY_OBSERVATION_SCHEMA_VERSION,
	TYPESCRIPT_PROVIDER_VERSION,
	buildCallGraph,
	callGraphReportExitCode,
	buildConditionalExportResolution,
	buildDeclarationContextAnalysis,
	declarationContextReportExitCode,
	buildSourceOriginCorrelation,
	buildModuleResolutionTrace,
	moduleResolutionTraceReportExitCode,
	buildCommandEventContractOverlay,
	commandEventContractOverlayReportExitCode,
	runCommandEventContractOverlayReport,
	buildCommandHandlerGraph,
	buildCommandDispatchTopology,
	commandHandlerGraphReportExitCode,
	commandDispatchTopologyReportExitCode,
	runCommandHandlerGraphReport,
	runCommandDispatchTopologyReport,
	buildGuardClassificationOverlay,
	guardClassificationOverlayReportExitCode,
	runGuardClassificationOverlayReport,
	buildGuardEnforcementLedgerArtifactSet,
	guardEnforcementLedgerReportExitCode,
	runGuardEnforcementLedgerReport,
	buildReadWriteAccessGraph,
	readWriteAccessReportExitCode,
	runReadWriteAccessReport,
	buildArrowCommandCensusArtifactSet,
	arrowCommandCensusReportExitCode,
	runArrowCommandCensusReport,
	buildModuleDependencyGraph,
	moduleDependencyReportExitCode,
	runModuleDependencyReport,
	buildLogicalGraphComposition,
	buildProjectContextGraph,
	runProjectContextReport,
	runDeclarationContextReport,
	runModuleResolutionTraceReport,
	projectContextReportExitCode,
	buildStructuralModuleReachabilityAnalysis,
	runStructuralModuleReachabilityReport,
	structuralModuleReachabilityReportExitCode,
	buildStructuralSccAnalysis,
	runStructuralSccReport,
	structuralSccReportExitCode,
	buildStateMachineGraph,
	runStateMachineGraphReport,
	stateMachineGraphReportExitCode,
	buildStaticSemanticSnapshot,
	runCallGraphReport,
	canonicalSemanticJson,
	canonicalSemanticJsonWitness,
	compareDependencyProviders,
	normalizeDependencyCruiserOutput,
	observeStateMachineTopology,
	observeArrowCommandCensus,
	observeGuardEnforcementLedger,
	selectJpwbCommandEventContractOverlayInputs,
	selectJpwbCommandDispatchTopology,
	selectJpwbCommandHandlerRegistries,
	validateDependencyCruiserObservation,
	validateDependencyProviderComparison,
	validateCallGraph,
	validateConditionalExportResolution,
	validateDeclarationContextAnalysis,
	validateSourceOriginCorrelation,
	validateModuleResolutionTrace,
	validateCommandEventContractOverlay,
	validateCommandDispatchTopology,
	validateCommandHandlerGraph,
	validateGuardClassificationOverlay,
	validateGuardEnforcementLedgerArtifactSet,
	validateGuardEnforcementLedgerObservation,
	validateReadWriteAccessGraph,
	validateArrowCommandCensusArtifactSet,
	validateArrowCommandCensusObservation,
	validateModuleDependencyGraph,
	validateLogicalGraphComposition,
	validateProjectContextGraph,
	validateStructuralModuleReachabilityAnalysis,
	validateStructuralSccAnalysis,
	validateStateMachineGraph,
	validateStateMachineTopologyObservation,
	validateStaticSemanticSnapshot
} from '@janumipwb/csaa';

interface PackageManifest {
	readonly dependencies?: Readonly<Record<string, string>>;
	readonly devDependencies?: Readonly<Record<string, string>>;
}

function manifest(relativeUrl: string): PackageManifest {
	return JSON.parse(readFileSync(new URL(relativeUrl, import.meta.url), 'utf8')) as PackageManifest;
}

describe('@janumipwb/csaa public semantic and graph surface', () => {
	it('exports the DWP-003 semantic and bounded DWP-004 graph surfaces', () => {
		expect(buildCallGraph).toBeTypeOf('function');
		expect(runCallGraphReport).toBeTypeOf('function');
		expect(callGraphReportExitCode).toBeTypeOf('function');
		expect(publicSurface).not.toHaveProperty('buildBoundedCallGraph');
		expect(publicSurface).not.toHaveProperty('createCallGraphProgressJsonlWriter');
		expect(publicSurface).not.toHaveProperty('runCallGraphCommand');
		expect(publicSurface).not.toHaveProperty('classifyCallGraphFailureState');
		expect(buildConditionalExportResolution).toBeTypeOf('function');
		expect(buildDeclarationContextAnalysis).toBeTypeOf('function');
		expect(runDeclarationContextReport).toBeTypeOf('function');
		expect(declarationContextReportExitCode).toBeTypeOf('function');
		expect(publicSurface).not.toHaveProperty('createDeclarationContextProgressJsonlWriter');
		expect(publicSurface).not.toHaveProperty('runDeclarationContextCommand');
		expect(publicSurface).not.toHaveProperty('admitModuleResolutionTraceReportRequest');
		expect(publicSurface).not.toHaveProperty('captureModuleResolutionTraceReportPipeline');
		expect(buildSourceOriginCorrelation).toBeTypeOf('function');
		expect(buildModuleResolutionTrace).toBeTypeOf('function');
		expect(runModuleResolutionTraceReport).toBeTypeOf('function');
		expect(moduleResolutionTraceReportExitCode).toBeTypeOf('function');
		expect(publicSurface).not.toHaveProperty('createModuleResolutionTraceProgressJsonlWriter');
		expect(publicSurface).not.toHaveProperty('runModuleResolutionTraceCommand');
		expect(buildCommandEventContractOverlay).toBeTypeOf('function');
		expect(runCommandEventContractOverlayReport).toBeTypeOf('function');
		expect(commandEventContractOverlayReportExitCode).toBeTypeOf('function');
		expect(publicSurface).not.toHaveProperty(
			'createCommandEventContractOverlayProgressJsonlWriter'
		);
		expect(publicSurface).not.toHaveProperty('runCommandEventContractOverlayCommand');
		expect(publicSurface).not.toHaveProperty('admitCommandEventContractOverlayReportRequest');
		expect(publicSurface).not.toHaveProperty(
			'runCommandEventContractOverlayReportWithDependencies'
		);
		expect(buildCommandHandlerGraph).toBeTypeOf('function');
		expect(runCommandHandlerGraphReport).toBeTypeOf('function');
		expect(commandHandlerGraphReportExitCode).toBeTypeOf('function');
		expect(publicSurface).not.toHaveProperty('createCommandHandlerGraphProgressJsonlWriter');
		expect(publicSurface).not.toHaveProperty('runCommandHandlerGraphCommand');
		expect(publicSurface).not.toHaveProperty('admitCommandHandlerGraphReportRequest');
		expect(publicSurface).not.toHaveProperty('runCommandHandlerGraphReportWithDependencies');
		expect(buildCommandDispatchTopology).toBeTypeOf('function');
		expect(selectJpwbCommandDispatchTopology).toBeTypeOf('function');
		expect(validateCommandDispatchTopology).toBeTypeOf('function');
		expect(runCommandDispatchTopologyReport).toBeTypeOf('function');
		expect(commandDispatchTopologyReportExitCode).toBeTypeOf('function');
		expect(publicSurface).not.toHaveProperty('createCommandDispatchTopologyProgressJsonlWriter');
		expect(publicSurface).not.toHaveProperty('runCommandDispatchTopologyCommand');
		expect(publicSurface).not.toHaveProperty('admitCommandDispatchTopologyReportRequest');
		expect(publicSurface).not.toHaveProperty('runCommandDispatchTopologyReportWithDependencies');
		expect(publicSurface).not.toHaveProperty('captureCommandHandlerGraphReportPipeline');
		expect(buildGuardClassificationOverlay).toBeTypeOf('function');
		expect(runGuardClassificationOverlayReport).toBeTypeOf('function');
		expect(guardClassificationOverlayReportExitCode).toBeTypeOf('function');
		expect(publicSurface).not.toHaveProperty('createGuardClassificationOverlayProgressJsonlWriter');
		expect(publicSurface).not.toHaveProperty('runGuardClassificationOverlayCommand');
		expect(publicSurface).not.toHaveProperty('admitGuardClassificationOverlayReportRequest');
		expect(publicSurface).not.toHaveProperty('runGuardClassificationOverlayReportWithDependencies');
		expect(publicSurface).not.toHaveProperty('hasValidatedStaticSemanticSnapshotCapability');
		expect(buildGuardEnforcementLedgerArtifactSet).toBeTypeOf('function');
		expect(runGuardEnforcementLedgerReport).toBeTypeOf('function');
		expect(guardEnforcementLedgerReportExitCode).toBeTypeOf('function');
		expect(publicSurface).not.toHaveProperty('createGuardEnforcementLedgerProgressJsonlWriter');
		expect(publicSurface).not.toHaveProperty('runGuardEnforcementLedgerCommand');
		expect(publicSurface).not.toHaveProperty('admitGuardEnforcementLedgerReportRequest');
		expect(publicSurface).not.toHaveProperty('runGuardEnforcementLedgerReportWithDependencies');
		expect(buildReadWriteAccessGraph).toBeTypeOf('function');
		expect(runReadWriteAccessReport).toBeTypeOf('function');
		expect(readWriteAccessReportExitCode).toBeTypeOf('function');
		expect(publicSurface).not.toHaveProperty('createReadWriteAccessProgressJsonlWriter');
		expect(publicSurface).not.toHaveProperty('runReadWriteAccessCommand');
		expect(publicSurface).not.toHaveProperty('admitProjectContextReportRequest');
		expect(publicSurface).not.toHaveProperty('captureProjectContextReportPipeline');
		expect(publicSurface).not.toHaveProperty('captureSemanticReportPipeline');
		expect(buildArrowCommandCensusArtifactSet).toBeTypeOf('function');
		expect(runArrowCommandCensusReport).toBeTypeOf('function');
		expect(arrowCommandCensusReportExitCode).toBeTypeOf('function');
		expect(publicSurface).not.toHaveProperty('createArrowCommandCensusProgressJsonlWriter');
		expect(publicSurface).not.toHaveProperty('runArrowCommandCensusCommand');
		expect(publicSurface).not.toHaveProperty('admitArrowCommandCensusReportRequest');
		expect(publicSurface).not.toHaveProperty('runArrowCommandCensusReportWithDependencies');
		expect(buildModuleDependencyGraph).toBeTypeOf('function');
		expect(runModuleDependencyReport).toBeTypeOf('function');
		expect(moduleDependencyReportExitCode).toBeTypeOf('function');
		expect(publicSurface).not.toHaveProperty('createModuleDependencyProgressJsonlWriter');
		expect(publicSurface).not.toHaveProperty('runModuleDependencyCommand');
		expect(publicSurface).not.toHaveProperty('classifyModuleDependencyGraphFailureState');
		expect(publicSurface).not.toHaveProperty('projectedModuleDependencyPopulation');
		expect(buildLogicalGraphComposition).toBeTypeOf('function');
		expect(buildProjectContextGraph).toBeTypeOf('function');
		expect(runProjectContextReport).toBeTypeOf('function');
		expect(projectContextReportExitCode).toBeTypeOf('function');
		expect(publicSurface).not.toHaveProperty('createProjectContextProgressJsonlWriter');
		expect(buildStructuralModuleReachabilityAnalysis).toBeTypeOf('function');
		expect(runStructuralModuleReachabilityReport).toBeTypeOf('function');
		expect(publicSurface).not.toHaveProperty(
			'buildStructuralModuleReachabilityAnalysisWithConsumedInputUsage'
		);
		expect(publicSurface).not.toHaveProperty(
			'createStructuralModuleReachabilityProgressJsonlWriter'
		);
		expect(structuralModuleReachabilityReportExitCode).toBeTypeOf('function');
		expect(buildStructuralSccAnalysis).toBeTypeOf('function');
		expect(runStructuralSccReport).toBeTypeOf('function');
		expect(structuralSccReportExitCode).toBeTypeOf('function');
		expect(publicSurface).not.toHaveProperty('createStructuralSccProgressJsonlWriter');
		expect(buildStateMachineGraph).toBeTypeOf('function');
		expect(runStateMachineGraphReport).toBeTypeOf('function');
		expect(stateMachineGraphReportExitCode).toBeTypeOf('function');
		expect(publicSurface).not.toHaveProperty('createStateMachineGraphProgressJsonlWriter');
		expect(publicSurface).not.toHaveProperty('runStateMachineGraphCommand');
		expect(publicSurface).not.toHaveProperty('classifyStateMachineGraphFailureState');
		expect(publicSurface).not.toHaveProperty('classifyStateMachineObservationFailureState');
		expect(buildStaticSemanticSnapshot).toBeTypeOf('function');
		expect(compareDependencyProviders).toBeTypeOf('function');
		expect(normalizeDependencyCruiserOutput).toBeTypeOf('function');
		expect(observeStateMachineTopology).toBeTypeOf('function');
		expect(observeArrowCommandCensus).toBeTypeOf('function');
		expect(observeGuardEnforcementLedger).toBeTypeOf('function');
		expect(selectJpwbCommandEventContractOverlayInputs).toBeTypeOf('function');
		expect(selectJpwbCommandHandlerRegistries).toBeTypeOf('function');
		expect(validateDependencyCruiserObservation).toBeTypeOf('function');
		expect(validateDependencyProviderComparison).toBeTypeOf('function');
		expect(validateCallGraph).toBeTypeOf('function');
		expect(validateConditionalExportResolution).toBeTypeOf('function');
		expect(publicSurface).not.toHaveProperty('validateConstructedConditionalExportResolution');
		expect(validateDeclarationContextAnalysis).toBeTypeOf('function');
		expect(publicSurface).not.toHaveProperty('validateConstructedDeclarationContextAnalysis');
		expect(publicSurface).not.toHaveProperty(
			'validateDeclarationContextAnalysisWithProviderForTesting'
		);
		expect(publicSurface).not.toHaveProperty(
			'compareDeclarationContextAnalysisCanonicalValuesForTesting'
		);
		expect(publicSurface).not.toHaveProperty('createCompilerProjectProgramSession');
		expect(publicSurface).not.toHaveProperty('createPrevalidatedVerifiedCompilerProjectInputHost');
		expect(publicSurface).not.toHaveProperty('withAttributedQueryForVerifiedHost');
		expect(publicSurface).not.toHaveProperty('declarationContextAnalysisCompilerProgramCapability');
		expect(publicSurface).not.toHaveProperty('declarationContextAnalysisTypeScriptPublicApi');
		expect(validateSourceOriginCorrelation).toBeTypeOf('function');
		expect(publicSurface).not.toHaveProperty('validateConstructedSourceOriginCorrelation');
		expect(publicSurface).not.toHaveProperty(
			'validateSourceOriginCorrelationWithProviderForTesting'
		);
		expect(publicSurface).not.toHaveProperty('emitCompilerProjectDeclaration');
		expect(publicSurface).not.toHaveProperty('decodeSourceMapV3');
		expect(publicSurface).not.toHaveProperty('sourceOriginCorrelationDeclarationEmissionProvider');
		expect(publicSurface).not.toHaveProperty('sourceOriginCorrelationInputDigest');
		expect(publicSurface).not.toHaveProperty('sourceOriginCorrelationContentDigest');
		expect(validateModuleResolutionTrace).toBeTypeOf('function');
		expect(publicSurface).not.toHaveProperty('validateConstructedModuleResolutionTrace');
		expect(publicSurface).not.toHaveProperty('getStaticSemanticSnapshotCompilerProjectInputLookup');
		expect(publicSurface).not.toHaveProperty(
			'attachVerifiedCompilerCaptureToStaticSemanticSnapshot'
		);
		expect(publicSurface).not.toHaveProperty('moduleResolutionTraceTypeScriptPublicApi');
		expect(validateCommandEventContractOverlay).toBeTypeOf('function');
		expect(validateCommandHandlerGraph).toBeTypeOf('function');
		expect(validateGuardClassificationOverlay).toBeTypeOf('function');
		expect(validateGuardEnforcementLedgerArtifactSet).toBeTypeOf('function');
		expect(validateGuardEnforcementLedgerObservation).toBeTypeOf('function');
		expect(validateReadWriteAccessGraph).toBeTypeOf('function');
		expect(validateArrowCommandCensusArtifactSet).toBeTypeOf('function');
		expect(validateArrowCommandCensusObservation).toBeTypeOf('function');
		expect(validateModuleDependencyGraph).toBeTypeOf('function');
		expect(validateLogicalGraphComposition).toBeTypeOf('function');
		expect(validateProjectContextGraph).toBeTypeOf('function');
		expect(validateStructuralModuleReachabilityAnalysis).toBeTypeOf('function');
		expect(validateStructuralSccAnalysis).toBeTypeOf('function');
		expect(validateStateMachineGraph).toBeTypeOf('function');
		expect(validateStateMachineTopologyObservation).toBeTypeOf('function');
		expect(validateStaticSemanticSnapshot).toBeTypeOf('function');
		expect(canonicalSemanticJson).toBeTypeOf('function');
		expect(canonicalSemanticJsonWitness).toBeTypeOf('function');
		expect(canonicalSemanticJson).toHaveLength(1);
		expect(canonicalSemanticJsonWitness).toHaveLength(1);
		expect(publicSurface).not.toHaveProperty('canonicalSemanticJsonWithProgress');
		expect(publicSurface).not.toHaveProperty('canonicalSemanticJsonWitnessWithProgress');
		expect(publicSurface).not.toHaveProperty('canonicalSemanticJsonPrefixedSha256');
		expect(publicSurface).not.toHaveProperty('compareCanonicalSemanticJsonStrings');
		expect(SEMANTIC_EXTRACTION_VERSION).toBe('jan-csaa-typescript-static/0.7.0');
		expect(SEMANTIC_OPERATION_VERSION).toBe('jan-csaa-build-static-semantic-snapshot/4.0.0');
		expect(SEMANTIC_REQUEST_SCHEMA_VERSION).toBe('jan-csaa-semantic-request/3.0.0');
		expect(SEMANTIC_SNAPSHOT_SCHEMA_VERSION).toBe('jan-csaa-semantic-snapshot/7.0.0');
		expect(STATIC_SEMANTIC_SNAPSHOT_PROGRESS_SCHEMA_VERSION).toBe(
			'jan-csaa-static-semantic-snapshot-progress/1.0.0'
		);
		expect(TYPESCRIPT_PROVIDER_VERSION).toBe('5.9.3');
		expect(CALL_GRAPH_OPERATION_VERSION).toBe('jan-csaa-build-call-graph/0.1.0');
		expect(CALL_GRAPH_REQUEST_SCHEMA_VERSION).toBe('jan-csaa-call-graph-request/1.0.0');
		expect(CALL_GRAPH_SCHEMA_VERSION).toBe('jan-csaa-call-graph/1.0.0');
		expect(CALL_GRAPH_REPORT_OPERATION_VERSION).toBe('jan-csaa-report-call-graph/0.1.0');
		expect(CALL_GRAPH_REPORT_REQUEST_SCHEMA_VERSION).toBe(
			'jan-csaa-call-graph-report-request/0.1.0'
		);
		expect(CALL_GRAPH_REPORT_RESULT_SCHEMA_VERSION).toBe('jan-csaa-call-graph-report-result/0.1.0');
		expect(CALL_GRAPH_REPORT_SCHEMA_VERSION).toBe('jan-csaa-call-graph-report/0.1.0');
		expect(CALL_GRAPH_REPORT_PROGRESS_SCHEMA_VERSION).toBe(
			'jan-csaa-call-graph-report-progress/0.1.0'
		);
		expect(CALL_GRAPH_PROGRESS_TRANSPORT_SCHEMA_VERSION).toBe(
			'jan-csaa-call-graph-progress-transport/0.1.0'
		);
		expect(CALL_GRAPH_PROGRESS_MAX_BYTES).toBe(8 * 1024 * 1024);
		expect(CALL_GRAPH_PROGRESS_MAX_EVENTS).toBe(2_048);
		expect(CONDITIONAL_EXPORT_RESOLUTION_OPERATION_VERSION).toBe(
			'jan-csaa-resolve-conditional-export/0.1.0'
		);
		expect(CONDITIONAL_EXPORT_RESOLUTION_PROGRESS_SCHEMA_VERSION).toBe(
			'jan-csaa-conditional-export-resolution-progress/1.0.0'
		);
		expect(CONDITIONAL_EXPORT_RESOLUTION_REQUEST_SCHEMA_VERSION).toBe(
			'jan-csaa-conditional-export-resolution-request/1.0.0'
		);
		expect(CONDITIONAL_EXPORT_RESOLUTION_SCHEMA_VERSION).toBe(
			'jan-csaa-conditional-export-resolution/1.0.0'
		);
		expect(DECLARATION_CONTEXT_ANALYSIS_OPERATION_VERSION).toBe(
			'jan-csaa-build-declaration-context-analysis/0.1.0'
		);
		expect(DECLARATION_CONTEXT_ANALYSIS_PROGRESS_SCHEMA_VERSION).toBe(
			'jan-csaa-declaration-context-analysis-progress/1.0.0'
		);
		expect(DECLARATION_CONTEXT_ANALYSIS_REQUEST_SCHEMA_VERSION).toBe(
			'jan-csaa-declaration-context-analysis-request/1.0.0'
		);
		expect(DECLARATION_CONTEXT_ANALYSIS_SCHEMA_VERSION).toBe(
			'jan-csaa-declaration-context-analysis/1.0.0'
		);
		expect(DECLARATION_CONTEXT_REPORT_OPERATION_VERSION).toBe(
			'jan-csaa-report-declaration-context/0.1.0'
		);
		expect(DECLARATION_CONTEXT_REPORT_REQUEST_SCHEMA_VERSION).toBe(
			'jan-csaa-declaration-context-report-request/0.1.0'
		);
		expect(DECLARATION_CONTEXT_REPORT_RESULT_SCHEMA_VERSION).toBe(
			'jan-csaa-declaration-context-report-result/0.1.0'
		);
		expect(DECLARATION_CONTEXT_REPORT_SCHEMA_VERSION).toBe(
			'jan-csaa-declaration-context-report/0.1.0'
		);
		expect(DECLARATION_CONTEXT_REPORT_PROGRESS_SCHEMA_VERSION).toBe(
			'jan-csaa-declaration-context-report-progress/0.1.0'
		);
		expect(DECLARATION_CONTEXT_PROGRESS_TRANSPORT_SCHEMA_VERSION).toBe(
			'jan-csaa-declaration-context-progress-transport/0.1.0'
		);
		expect(DECLARATION_CONTEXT_PROGRESS_MAX_BYTES).toBe(8 * 1024 * 1024);
		expect(DECLARATION_CONTEXT_PROGRESS_MAX_EVENTS).toBe(2_048);
		expect(READ_WRITE_ACCESS_REPORT_OPERATION_VERSION).toBe(
			'jan-csaa-report-read-write-access/0.1.0'
		);
		expect(READ_WRITE_ACCESS_REPORT_REQUEST_SCHEMA_VERSION).toBe(
			'jan-csaa-read-write-access-report-request/0.1.0'
		);
		expect(READ_WRITE_ACCESS_REPORT_RESULT_SCHEMA_VERSION).toBe(
			'jan-csaa-read-write-access-report-result/0.1.0'
		);
		expect(READ_WRITE_ACCESS_REPORT_SCHEMA_VERSION).toBe('jan-csaa-read-write-access-report/0.1.0');
		expect(READ_WRITE_ACCESS_REPORT_PROGRESS_SCHEMA_VERSION).toBe(
			'jan-csaa-read-write-access-report-progress/0.1.0'
		);
		expect(READ_WRITE_ACCESS_PROGRESS_TRANSPORT_SCHEMA_VERSION).toBe(
			'jan-csaa-read-write-access-progress-transport/0.1.0'
		);
		expect(READ_WRITE_ACCESS_PROGRESS_MAX_BYTES).toBe(8 * 1024 * 1024);
		expect(READ_WRITE_ACCESS_PROGRESS_MAX_EVENTS).toBe(2_048);
		expect(DECLARATION_CONTEXT_REPORT_NONCLAIMS).toContain(
			'COMPILER_CONTEXT_OR_CONTEXT_ONLY_TARGET_FILESYSTEM_CURRENTNESS'
		);
		expect(DECLARATION_CONTEXT_REPORT_NONCLAIMS).not.toContain('CURRENTNESS_OR_FRESHNESS');
		expect(DECLARATION_CONTEXT_REPORT_SELECTION).toMatchObject({
			declarationContext: {
				criterion:
					'ONE_EXACT_PACKAGE_ROOT_EXPORT_DECLARATION_BINDING_IN_CAP011_SELECTED_DECLARATION_TARGET'
			},
			moduleResolution: {
				moduleMode: 'IMPORT',
				occurrenceKind: 'IMPORT',
				typeOnly: false,
				valueKind: 'VALUE_NON_TYPE_ONLY'
			}
		});
		expect(DECLARATION_CONTEXT_REPORT_PREDECESSOR_NONCLAIMS.declarationContextAnalysis).toContain(
			'CURRENTNESS_OR_FRESHNESS'
		);
		expect(DECLARATION_CONTEXT_REPORT_PROGRESS_NONCLAIMS).toMatchObject({
			compilerCaptureCurrentness: 'NOT_ASSESSED',
			targetArtifactCurrentness: 'NOT_ASSESSED'
		});
		expect(SOURCE_ORIGIN_CORRELATION_OPERATION_VERSION).toBe(
			'jan-csaa-build-source-origin-correlation/0.1.0'
		);
		expect(SOURCE_ORIGIN_CORRELATION_PROGRESS_SCHEMA_VERSION).toBe(
			'jan-csaa-source-origin-correlation-progress/1.0.0'
		);
		expect(SOURCE_ORIGIN_CORRELATION_REQUEST_SCHEMA_VERSION).toBe(
			'jan-csaa-source-origin-correlation-request/1.0.0'
		);
		expect(SOURCE_ORIGIN_CORRELATION_SCHEMA_VERSION).toBe(
			'jan-csaa-source-origin-correlation/1.0.0'
		);
		expect(COMMAND_HANDLER_GRAPH_OPERATION_VERSION).toBe(
			'jan-csaa-build-command-handler-graph/0.1.0'
		);
		expect(COMMAND_HANDLER_GRAPH_PROGRESS_SCHEMA_VERSION).toBe(
			'jan-csaa-command-handler-graph-progress/1.0.0'
		);
		expect(COMMAND_HANDLER_GRAPH_REQUEST_SCHEMA_VERSION).toBe(
			'jan-csaa-command-handler-graph-request/1.0.0'
		);
		expect(COMMAND_HANDLER_GRAPH_SCHEMA_VERSION).toBe('jan-csaa-command-handler-graph/1.0.0');
		expect(COMMAND_HANDLER_GRAPH_REPORT_OPERATION_VERSION).toBe(
			'jan-csaa-report-command-handler-graph/0.1.0'
		);
		expect(COMMAND_HANDLER_GRAPH_REPORT_REQUEST_SCHEMA_VERSION).toBe(
			'jan-csaa-command-handler-graph-report-request/0.1.0'
		);
		expect(COMMAND_HANDLER_GRAPH_REPORT_RESULT_SCHEMA_VERSION).toBe(
			'jan-csaa-command-handler-graph-report-result/0.1.0'
		);
		expect(COMMAND_HANDLER_GRAPH_REPORT_SCHEMA_VERSION).toBe(
			'jan-csaa-command-handler-graph-report/0.1.0'
		);
		expect(COMMAND_HANDLER_GRAPH_REPORT_SCOPE).toBe(
			'EXACT_SELECTED_FROZEN_SUBJECT_SEMANTIC_RETAINED_ARROW_AND_COMMAND_HANDLER_GRAPH'
		);
		expect(COMMAND_HANDLER_GRAPH_REPORT_PROGRESS_SCHEMA_VERSION).toBe(
			'jan-csaa-command-handler-graph-report-progress/0.1.0'
		);
		expect(COMMAND_HANDLER_GRAPH_PROGRESS_TRANSPORT_SCHEMA_VERSION).toBe(
			'jan-csaa-command-handler-graph-progress-transport/0.1.0'
		);
		expect(COMMAND_HANDLER_GRAPH_PROGRESS_MAX_BYTES).toBe(8 * 1024 * 1024);
		expect(COMMAND_HANDLER_GRAPH_PROGRESS_MAX_EVENTS).toBe(2_048);
		expect(COMMAND_DISPATCH_TOPOLOGY_PROGRESS_SCHEMA_VERSION).toBe(
			'jan-csaa-command-dispatch-topology-progress/1.0.0'
		);
		expect(COMMAND_DISPATCH_TOPOLOGY_REPORT_OPERATION_VERSION).toBe(
			'jan-csaa-report-command-dispatch-topology/0.1.0'
		);
		expect(COMMAND_DISPATCH_TOPOLOGY_REPORT_REQUEST_SCHEMA_VERSION).toBe(
			'jan-csaa-command-dispatch-topology-report-request/0.1.0'
		);
		expect(COMMAND_DISPATCH_TOPOLOGY_REPORT_RESULT_SCHEMA_VERSION).toBe(
			'jan-csaa-command-dispatch-topology-report-result/0.1.0'
		);
		expect(COMMAND_DISPATCH_TOPOLOGY_REPORT_SCHEMA_VERSION).toBe(
			'jan-csaa-command-dispatch-topology-report/0.1.0'
		);
		expect(COMMAND_DISPATCH_TOPOLOGY_REPORT_SCOPE).toBe(
			'EXACT_SELECTED_FROZEN_SUBJECT_SEMANTIC_RETAINED_ARROW_COMMAND_HANDLER_AND_COMMAND_DISPATCH_TOPOLOGY'
		);
		expect(COMMAND_DISPATCH_TOPOLOGY_REPORT_PROGRESS_SCHEMA_VERSION).toBe(
			'jan-csaa-command-dispatch-topology-report-progress/0.1.0'
		);
		expect(COMMAND_DISPATCH_TOPOLOGY_PROGRESS_TRANSPORT_SCHEMA_VERSION).toBe(
			'jan-csaa-command-dispatch-topology-progress-transport/0.1.0'
		);
		expect(COMMAND_DISPATCH_TOPOLOGY_PROGRESS_MAX_BYTES).toBe(8 * 1024 * 1024);
		expect(COMMAND_DISPATCH_TOPOLOGY_PROGRESS_MAX_EVENTS).toBe(2_048);
		expect(COMMAND_EVENT_CONTRACT_OVERLAY_OPERATION_VERSION).toBe(
			'jan-csaa-build-command-event-contract-overlay/0.1.0'
		);
		expect(COMMAND_EVENT_CONTRACT_OVERLAY_PROGRESS_SCHEMA_VERSION).toBe(
			'jan-csaa-command-event-contract-overlay-progress/1.0.0'
		);
		expect(COMMAND_EVENT_CONTRACT_OVERLAY_REQUEST_SCHEMA_VERSION).toBe(
			'jan-csaa-command-event-contract-overlay-request/1.0.0'
		);
		expect(COMMAND_EVENT_CONTRACT_OVERLAY_SCHEMA_VERSION).toBe(
			'jan-csaa-command-event-contract-overlay/1.0.0'
		);
		expect(COMMAND_EVENT_CONTRACT_OVERLAY_REPORT_OPERATION_VERSION).toBe(
			'jan-csaa-report-command-event-contract-overlay/0.1.0'
		);
		expect(COMMAND_EVENT_CONTRACT_OVERLAY_REPORT_REQUEST_SCHEMA_VERSION).toBe(
			'jan-csaa-command-event-contract-overlay-report-request/0.1.0'
		);
		expect(COMMAND_EVENT_CONTRACT_OVERLAY_REPORT_RESULT_SCHEMA_VERSION).toBe(
			'jan-csaa-command-event-contract-overlay-report-result/0.1.0'
		);
		expect(COMMAND_EVENT_CONTRACT_OVERLAY_REPORT_SCHEMA_VERSION).toBe(
			'jan-csaa-command-event-contract-overlay-report/0.1.0'
		);
		expect(COMMAND_EVENT_CONTRACT_OVERLAY_REPORT_SCOPE).toBe(
			'EXACT_SELECTED_FROZEN_SUBJECT_SEMANTIC_RETAINED_ARROW_COMMAND_HANDLER_AND_COMMAND_EVENT_CONTRACT_OVERLAY'
		);
		expect(COMMAND_EVENT_CONTRACT_OVERLAY_REPORT_SELECTION).toMatchObject({
			commandDispatchTopology: 'NOT_CONSUMED',
			guardClassificationOverlay: 'NOT_CONSUMED',
			retainedEventSurfaceCensus:
				'EXACT_FROZEN_ARTIFACT_REFERENCE_NOT_EXECUTED_BY_CSAA_AND_NOT_INTEGRATED'
		});
		expect(COMMAND_EVENT_CONTRACT_OVERLAY_REPORT_PROGRESS_SCHEMA_VERSION).toBe(
			'jan-csaa-command-event-contract-overlay-report-progress/0.1.0'
		);
		expect(COMMAND_EVENT_CONTRACT_OVERLAY_PROGRESS_TRANSPORT_SCHEMA_VERSION).toBe(
			'jan-csaa-command-event-contract-overlay-progress-transport/0.1.0'
		);
		expect(COMMAND_EVENT_CONTRACT_OVERLAY_PROGRESS_MAX_BYTES).toBe(8 * 1024 * 1024);
		expect(COMMAND_EVENT_CONTRACT_OVERLAY_PROGRESS_MAX_EVENTS).toBe(2_048);
		expect(GUARD_CLASSIFICATION_OVERLAY_OPERATION_VERSION).toBe(
			'jan-csaa-build-guard-classification-overlay/0.1.0'
		);
		expect(GUARD_CLASSIFICATION_OVERLAY_PROGRESS_SCHEMA_VERSION).toBe(
			'jan-csaa-guard-classification-overlay-progress/1.0.0'
		);
		expect(GUARD_CLASSIFICATION_OVERLAY_REQUEST_SCHEMA_VERSION).toBe(
			'jan-csaa-guard-classification-overlay-request/1.0.0'
		);
		expect(GUARD_CLASSIFICATION_OVERLAY_SCHEMA_VERSION).toBe(
			'jan-csaa-guard-classification-overlay/1.0.0'
		);
		expect(GUARD_CLASSIFICATION_OVERLAY_REPORT_OPERATION_VERSION).toBe(
			'jan-csaa-report-guard-classification-overlay/0.1.0'
		);
		expect(GUARD_CLASSIFICATION_OVERLAY_REPORT_REQUEST_SCHEMA_VERSION).toBe(
			'jan-csaa-guard-classification-overlay-report-request/0.1.0'
		);
		expect(GUARD_CLASSIFICATION_OVERLAY_REPORT_RESULT_SCHEMA_VERSION).toBe(
			'jan-csaa-guard-classification-overlay-report-result/0.1.0'
		);
		expect(GUARD_CLASSIFICATION_OVERLAY_REPORT_SCHEMA_VERSION).toBe(
			'jan-csaa-guard-classification-overlay-report/0.1.0'
		);
		expect(GUARD_CLASSIFICATION_OVERLAY_REPORT_SCOPE).toBe(
			'EXACT_SELECTED_FROZEN_SUBJECT_RETAINED_GUARD_STATE_COMMAND_HANDLER_AND_GUARD_CLASSIFICATION_OVERLAY'
		);
		expect(GUARD_CLASSIFICATION_OVERLAY_REPORT_STATE_SOURCE).toEqual({
			logicalPath: 'packages/rph-domain/src/transitions.data.ts',
			projectConfigPath: 'packages/rph-domain/tsconfig.json'
		});
		expect(GUARD_CLASSIFICATION_OVERLAY_REPORT_SELECTION).toMatchObject({
			commandDispatchTopology: 'NOT_CONSUMED',
			commandEventContractOverlay: 'NOT_CONSUMED',
			stateSource: GUARD_CLASSIFICATION_OVERLAY_REPORT_STATE_SOURCE
		});
		expect(GUARD_CLASSIFICATION_OVERLAY_REPORT_PROGRESS_SCHEMA_VERSION).toBe(
			'jan-csaa-guard-classification-overlay-report-progress/0.1.0'
		);
		expect(GUARD_CLASSIFICATION_OVERLAY_PROGRESS_TRANSPORT_SCHEMA_VERSION).toBe(
			'jan-csaa-guard-classification-overlay-progress-transport/0.1.0'
		);
		expect(GUARD_CLASSIFICATION_OVERLAY_PROGRESS_MAX_BYTES).toBe(8 * 1024 * 1024);
		expect(GUARD_CLASSIFICATION_OVERLAY_PROGRESS_MAX_EVENTS).toBe(2_048);
		expect(READ_WRITE_ACCESS_GRAPH_OPERATION_VERSION).toBe(
			'jan-csaa-build-read-write-access-graph/0.1.0'
		);
		expect(READ_WRITE_ACCESS_GRAPH_REQUEST_SCHEMA_VERSION).toBe(
			'jan-csaa-read-write-access-graph-request/1.0.0'
		);
		expect(READ_WRITE_ACCESS_GRAPH_SCHEMA_VERSION).toBe('jan-csaa-read-write-access-graph/1.0.0');
		expect(ARROW_COMMAND_CENSUS_OPERATION_VERSION).toBe(
			'jan-csaa-observe-jpwb-arrow-command-census/0.1.0'
		);
		expect(ARROW_COMMAND_CENSUS_OBSERVATION_SCHEMA_VERSION).toBe(
			'jan-csaa-arrow-command-census-observation/1.0.0'
		);
		expect(ARROW_COMMAND_CENSUS_PROGRESS_SCHEMA_VERSION).toBe(
			'jan-csaa-arrow-command-census-progress/1.0.0'
		);
		expect(ARROW_COMMAND_CENSUS_REPORT_OPERATION_VERSION).toBe(
			'jan-csaa-report-arrow-command-census/0.1.0'
		);
		expect(ARROW_COMMAND_CENSUS_REPORT_REQUEST_SCHEMA_VERSION).toBe(
			'jan-csaa-arrow-command-census-report-request/0.1.0'
		);
		expect(ARROW_COMMAND_CENSUS_REPORT_RESULT_SCHEMA_VERSION).toBe(
			'jan-csaa-arrow-command-census-report-result/0.1.0'
		);
		expect(ARROW_COMMAND_CENSUS_REPORT_SCHEMA_VERSION).toBe(
			'jan-csaa-arrow-command-census-report/0.1.0'
		);
		expect(ARROW_COMMAND_CENSUS_REPORT_PROGRESS_SCHEMA_VERSION).toBe(
			'jan-csaa-arrow-command-census-report-progress/0.1.0'
		);
		expect(ARROW_COMMAND_CENSUS_PROGRESS_TRANSPORT_SCHEMA_VERSION).toBe(
			'jan-csaa-arrow-command-census-progress-transport/0.1.0'
		);
		expect(ARROW_COMMAND_CENSUS_PROGRESS_MAX_BYTES).toBe(8 * 1024 * 1024);
		expect(ARROW_COMMAND_CENSUS_PROGRESS_MAX_EVENTS).toBe(2_048);
		expect(ARROW_COMMAND_CENSUS_REPORT_ADMISSION_LIMITS).toEqual({
			maxDiagnosticPathCharacters: 10_000,
			maxProjectPathCharacters: 4_096
		});
		expect(GUARD_ENFORCEMENT_LEDGER_OPERATION_VERSION).toBe(
			'jan-csaa-observe-jpwb-guard-enforcement-ledger/0.1.0'
		);
		expect(GUARD_ENFORCEMENT_LEDGER_SCHEMA_VERSION).toBe(
			'jan-csaa-guard-enforcement-ledger-observation/1.0.0'
		);
		expect(GUARD_ENFORCEMENT_LEDGER_PROGRESS_SCHEMA_VERSION).toBe(
			'jan-csaa-guard-enforcement-ledger-progress/1.0.0'
		);
		expect(GUARD_ENFORCEMENT_LEDGER_REPORT_OPERATION_VERSION).toBe(
			'jan-csaa-report-guard-enforcement-ledger/0.1.0'
		);
		expect(GUARD_ENFORCEMENT_LEDGER_REPORT_REQUEST_SCHEMA_VERSION).toBe(
			'jan-csaa-guard-enforcement-ledger-report-request/0.1.0'
		);
		expect(GUARD_ENFORCEMENT_LEDGER_REPORT_RESULT_SCHEMA_VERSION).toBe(
			'jan-csaa-guard-enforcement-ledger-report-result/0.1.0'
		);
		expect(GUARD_ENFORCEMENT_LEDGER_REPORT_SCHEMA_VERSION).toBe(
			'jan-csaa-guard-enforcement-ledger-report/0.1.0'
		);
		expect(GUARD_ENFORCEMENT_LEDGER_REPORT_PROGRESS_SCHEMA_VERSION).toBe(
			'jan-csaa-guard-enforcement-ledger-report-progress/0.1.0'
		);
		expect(GUARD_ENFORCEMENT_LEDGER_PROGRESS_TRANSPORT_SCHEMA_VERSION).toBe(
			'jan-csaa-guard-enforcement-ledger-progress-transport/0.1.0'
		);
		expect(GUARD_ENFORCEMENT_LEDGER_PROGRESS_MAX_BYTES).toBe(8 * 1024 * 1024);
		expect(GUARD_ENFORCEMENT_LEDGER_PROGRESS_MAX_EVENTS).toBe(2_048);
		expect(GUARD_ENFORCEMENT_LEDGER_REPORT_ADMISSION_LIMITS).toEqual({
			maxDiagnosticPathCharacters: 10_000,
			maxProjectPathCharacters: 4_096
		});
		expect(STATE_MACHINE_TOPOLOGY_OBSERVATION_OPERATION_VERSION).toBe(
			'jan-csaa-observe-jpwb-state-machine-topology/0.1.0'
		);
		expect(STATE_MACHINE_TOPOLOGY_OBSERVATION_SCHEMA_VERSION).toBe(
			'jan-csaa-state-machine-topology-observation/1.0.0'
		);
		expect(STATE_MACHINE_GRAPH_OPERATION_VERSION).toBe('jan-csaa-build-state-machine-graph/0.1.0');
		expect(STATE_MACHINE_GRAPH_REQUEST_SCHEMA_VERSION).toBe(
			'jan-csaa-state-machine-graph-request/1.0.0'
		);
		expect(STATE_MACHINE_GRAPH_SCHEMA_VERSION).toBe('jan-csaa-state-machine-graph/1.0.0');
		expect(STATE_MACHINE_GRAPH_REPORT_OPERATION_VERSION).toBe(
			'jan-csaa-report-state-machine-graph/0.1.0'
		);
		expect(STATE_MACHINE_GRAPH_REPORT_REQUEST_SCHEMA_VERSION).toBe(
			'jan-csaa-state-machine-graph-report-request/0.1.0'
		);
		expect(STATE_MACHINE_GRAPH_REPORT_RESULT_SCHEMA_VERSION).toBe(
			'jan-csaa-state-machine-graph-report-result/0.1.0'
		);
		expect(STATE_MACHINE_GRAPH_REPORT_SCHEMA_VERSION).toBe(
			'jan-csaa-state-machine-graph-report/0.1.0'
		);
		expect(STATE_MACHINE_GRAPH_REPORT_PROGRESS_SCHEMA_VERSION).toBe(
			'jan-csaa-state-machine-graph-report-progress/0.1.0'
		);
		expect(STATE_MACHINE_GRAPH_PROGRESS_TRANSPORT_SCHEMA_VERSION).toBe(
			'jan-csaa-state-machine-graph-progress-transport/0.1.0'
		);
		expect(STATE_MACHINE_GRAPH_PROGRESS_MAX_BYTES).toBe(8 * 1024 * 1024);
		expect(STATE_MACHINE_GRAPH_PROGRESS_MAX_EVENTS).toBe(2_048);
		expect(MODULE_DEPENDENCY_GRAPH_OPERATION_VERSION).toBe(
			'jan-csaa-build-module-dependency-graph/0.1.1'
		);
		expect(MODULE_DEPENDENCY_GRAPH_CANONICAL_PROFILE).toBe(
			'jan-csaa-module-dependency-graph-canonical/1.0.1'
		);
		expect(MODULE_DEPENDENCY_GRAPH_REQUEST_SCHEMA_VERSION).toBe(
			'jan-csaa-module-dependency-graph-request/1.0.0'
		);
		expect(MODULE_DEPENDENCY_GRAPH_SCHEMA_VERSION).toBe('jan-csaa-module-dependency-graph/1.0.0');
		expect(MODULE_DEPENDENCY_REPORT_OPERATION_VERSION).toBe(
			'jan-csaa-report-module-dependency/0.1.0'
		);
		expect(MODULE_DEPENDENCY_REPORT_REQUEST_SCHEMA_VERSION).toBe(
			'jan-csaa-module-dependency-report-request/0.1.0'
		);
		expect(MODULE_DEPENDENCY_REPORT_RESULT_SCHEMA_VERSION).toBe(
			'jan-csaa-module-dependency-report-result/0.1.0'
		);
		expect(MODULE_DEPENDENCY_REPORT_SCHEMA_VERSION).toBe('jan-csaa-module-dependency-report/0.1.0');
		expect(MODULE_DEPENDENCY_REPORT_PROGRESS_SCHEMA_VERSION).toBe(
			'jan-csaa-module-dependency-report-progress/0.1.0'
		);
		expect(MODULE_DEPENDENCY_PROGRESS_TRANSPORT_SCHEMA_VERSION).toBe(
			'jan-csaa-module-dependency-progress-transport/0.1.0'
		);
		expect(MODULE_DEPENDENCY_PROGRESS_MAX_BYTES).toBe(8 * 1024 * 1024);
		expect(MODULE_DEPENDENCY_PROGRESS_MAX_EVENTS).toBe(2_048);
		expect(MODULE_RESOLUTION_TRACE_OPERATION_VERSION).toBe(
			'jan-csaa-build-module-resolution-trace/0.1.0'
		);
		expect(MODULE_RESOLUTION_TRACE_PROGRESS_SCHEMA_VERSION).toBe(
			'jan-csaa-module-resolution-trace-progress/1.0.0'
		);
		expect(MODULE_RESOLUTION_TRACE_REQUEST_SCHEMA_VERSION).toBe(
			'jan-csaa-module-resolution-trace-request/1.0.0'
		);
		expect(MODULE_RESOLUTION_TRACE_SCHEMA_VERSION).toBe('jan-csaa-module-resolution-trace/1.0.0');
		expect(MODULE_RESOLUTION_TRACE_REPORT_OPERATION_VERSION).toBe(
			'jan-csaa-report-module-resolution-trace/0.1.0'
		);
		expect(MODULE_RESOLUTION_TRACE_REPORT_REQUEST_SCHEMA_VERSION).toBe(
			'jan-csaa-module-resolution-trace-report-request/0.1.0'
		);
		expect(MODULE_RESOLUTION_TRACE_REPORT_RESULT_SCHEMA_VERSION).toBe(
			'jan-csaa-module-resolution-trace-report-result/0.1.0'
		);
		expect(MODULE_RESOLUTION_TRACE_REPORT_SCHEMA_VERSION).toBe(
			'jan-csaa-module-resolution-trace-report/0.1.0'
		);
		expect(MODULE_RESOLUTION_TRACE_REPORT_PROGRESS_SCHEMA_VERSION).toBe(
			'jan-csaa-module-resolution-trace-report-progress/0.1.0'
		);
		expect(MODULE_RESOLUTION_TRACE_PROGRESS_TRANSPORT_SCHEMA_VERSION).toBe(
			'jan-csaa-module-resolution-trace-progress-transport/0.1.0'
		);
		expect(MODULE_RESOLUTION_TRACE_PROGRESS_MAX_BYTES).toBe(8 * 1024 * 1024);
		expect(MODULE_RESOLUTION_TRACE_PROGRESS_MAX_EVENTS).toBe(2_048);
		expect(MODULE_RESOLUTION_TRACE_REPORT_NONCLAIMS).toContain(
			'COMPILER_CONTEXT_OR_CONTEXT_ONLY_TARGET_FILESYSTEM_CURRENTNESS'
		);
		expect(MODULE_RESOLUTION_TRACE_REPORT_NONCLAIMS).not.toContain('CURRENTNESS_OR_FRESHNESS');
		expect(MODULE_RESOLUTION_TRACE_REPORT_NONCLAIMS).toContain('TYPE_ONLY_IMPORT_OCCURRENCE');
		expect(MODULE_RESOLUTION_TRACE_REPORT_SELECTION).toMatchObject({
			moduleMode: 'IMPORT',
			occurrenceKind: 'IMPORT',
			typeOnly: false,
			valueKind: 'VALUE_NON_TYPE_ONLY'
		});
		expect(MODULE_RESOLUTION_TRACE_REPORT_PREDECESSOR_NONCLAIMS.moduleResolutionTrace).toContain(
			'CURRENTNESS_OR_FRESHNESS'
		);
		expect(MODULE_RESOLUTION_TRACE_REPORT_PROGRESS_NONCLAIMS).toMatchObject({
			compilerCaptureCurrentness: 'NOT_ASSESSED',
			targetArtifactCurrentness: 'NOT_ASSESSED'
		});
		expect(LOGICAL_GRAPH_COMPOSITION_OPERATION_VERSION).toBe(
			'jan-csaa-compose-logical-graph/0.1.0'
		);
		expect(LOGICAL_GRAPH_COMPOSITION_PROGRESS_SCHEMA_VERSION).toBe(
			'jan-csaa-logical-graph-composition-progress/1.0.0'
		);
		expect(LOGICAL_GRAPH_COMPOSITION_REQUEST_SCHEMA_VERSION).toBe(
			'jan-csaa-logical-graph-composition-request/1.0.0'
		);
		expect(LOGICAL_GRAPH_COMPOSITION_SCHEMA_VERSION).toBe(
			'jan-csaa-logical-graph-composition/1.0.0'
		);
		expect(PROJECT_CONTEXT_GRAPH_OPERATION_VERSION).toBe(
			'jan-csaa-build-project-context-graph/0.1.0'
		);
		expect(PROJECT_CONTEXT_GRAPH_PROGRESS_SCHEMA_VERSION).toBe(
			'jan-csaa-project-context-graph-progress/1.0.0'
		);
		expect(PROJECT_CONTEXT_GRAPH_REQUEST_SCHEMA_VERSION).toBe(
			'jan-csaa-project-context-graph-request/1.0.0'
		);
		expect(PROJECT_CONTEXT_GRAPH_SCHEMA_VERSION).toBe('jan-csaa-project-context-graph/1.0.0');
		expect(PROJECT_CONTEXT_REPORT_OPERATION_VERSION).toBe('jan-csaa-report-project-context/0.1.0');
		expect(PROJECT_CONTEXT_REPORT_PROGRESS_SCHEMA_VERSION).toBe(
			'jan-csaa-project-context-report-progress/0.1.0'
		);
		expect(PROJECT_CONTEXT_REPORT_PROGRESS_NONCLAIMS).toEqual({
			dwp006Completion: 'NOT_CLAIMED',
			facadeNonclaims: PROJECT_CONTEXT_REPORT_NONCLAIMS,
			janCsaa007OperationProgressResponse: 'NOT_CLAIMED',
			runtimeOutcomeInvariance: 'NOT_CLAIMED',
			terminalOutcomeEvidenceOrCapabilityCompleteness: 'NOT_CLAIMED'
		});
		expect(PROJECT_CONTEXT_PROGRESS_TRANSPORT_SCHEMA_VERSION).toBe(
			'jan-csaa-project-context-progress-transport/0.1.0'
		);
		expect(PROJECT_CONTEXT_PROGRESS_MAX_BYTES).toBe(8 * 1024 * 1024);
		expect(PROJECT_CONTEXT_PROGRESS_MAX_EVENTS).toBe(2_048);
		expect(PROJECT_CONTEXT_REPORT_REQUEST_SCHEMA_VERSION).toBe(
			'jan-csaa-project-context-report-request/0.1.0'
		);
		expect(PROJECT_CONTEXT_REPORT_RESULT_SCHEMA_VERSION).toBe(
			'jan-csaa-project-context-report-result/0.1.0'
		);
		expect(PROJECT_CONTEXT_REPORT_SCHEMA_VERSION).toBe('jan-csaa-project-context-report/0.1.0');
		expect(STRUCTURAL_MODULE_REACHABILITY_ANALYSIS_OPERATION_VERSION).toBe(
			'jan-csaa-analyze-structural-module-reachability/0.1.0'
		);
		expect(STRUCTURAL_MODULE_REACHABILITY_ANALYSIS_REQUEST_SCHEMA_VERSION).toBe(
			'jan-csaa-structural-module-reachability-analysis-request/1.0.0'
		);
		expect(STRUCTURAL_MODULE_REACHABILITY_ANALYSIS_SCHEMA_VERSION).toBe(
			'jan-csaa-structural-module-reachability-analysis/1.0.0'
		);
		expect(STRUCTURAL_MODULE_REACHABILITY_REPORT_OPERATION_VERSION).toBe(
			'jan-csaa-report-structural-module-reachability/0.1.0'
		);
		expect(STRUCTURAL_MODULE_REACHABILITY_REPORT_PROGRESS_SCHEMA_VERSION).toBe(
			'jan-csaa-structural-module-reachability-report-progress/0.1.0'
		);
		expect(STRUCTURAL_MODULE_REACHABILITY_REPORT_PROGRESS_NONCLAIMS).toEqual({
			dwp006Completion: 'NOT_CLAIMED',
			facadeNonclaims: STRUCTURAL_MODULE_REACHABILITY_REPORT_NONCLAIMS,
			janCsaa007OperationProgressResponse: 'NOT_CLAIMED',
			runtimeOutcomeInvariance: 'NOT_CLAIMED',
			terminalOutcomeEvidenceOrCapabilityCompleteness: 'NOT_CLAIMED'
		});
		expect(STRUCTURAL_MODULE_REACHABILITY_PROGRESS_TRANSPORT_SCHEMA_VERSION).toBe(
			'jan-csaa-structural-module-reachability-progress-transport/0.1.0'
		);
		expect(STRUCTURAL_MODULE_REACHABILITY_PROGRESS_MAX_BYTES).toBe(8 * 1024 * 1024);
		expect(STRUCTURAL_MODULE_REACHABILITY_PROGRESS_MAX_EVENTS).toBe(2_048);
		expect(STRUCTURAL_MODULE_REACHABILITY_REPORT_REQUEST_SCHEMA_VERSION).toBe(
			'jan-csaa-structural-module-reachability-report-request/0.1.0'
		);
		expect(STRUCTURAL_MODULE_REACHABILITY_REPORT_SCHEMA_VERSION).toBe(
			'jan-csaa-structural-module-reachability-report/0.1.0'
		);
		expect(STRUCTURAL_SCC_ANALYSIS_OPERATION_VERSION).toBe('jan-csaa-analyze-structural-scc/0.1.0');
		expect(STRUCTURAL_SCC_ANALYSIS_REQUEST_SCHEMA_VERSION).toBe(
			'jan-csaa-structural-scc-analysis-request/1.0.0'
		);
		expect(STRUCTURAL_SCC_ANALYSIS_SCHEMA_VERSION).toBe('jan-csaa-structural-scc-analysis/1.0.0');
		expect(STRUCTURAL_SCC_REPORT_OPERATION_VERSION).toBe('jan-csaa-report-structural-scc/0.1.0');
		expect(STRUCTURAL_SCC_REPORT_PROGRESS_SCHEMA_VERSION).toBe(
			'jan-csaa-structural-scc-report-progress/0.1.0'
		);
		expect(STRUCTURAL_SCC_REPORT_PROGRESS_NONCLAIMS).toEqual({
			dwp006Completion: 'NOT_CLAIMED',
			facadeNonclaims: STRUCTURAL_SCC_REPORT_NONCLAIMS,
			janCsaa007OperationProgressResponse: 'NOT_CLAIMED',
			runtimeOutcomeInvariance: 'NOT_CLAIMED',
			terminalOutcomeEvidenceOrCapabilityCompleteness: 'NOT_CLAIMED'
		});
		expect(STRUCTURAL_SCC_PROGRESS_TRANSPORT_SCHEMA_VERSION).toBe(
			'jan-csaa-structural-scc-progress-transport/0.1.0'
		);
		expect(STRUCTURAL_SCC_PROGRESS_MAX_BYTES).toBe(8 * 1024 * 1024);
		expect(STRUCTURAL_SCC_PROGRESS_MAX_EVENTS).toBe(2_048);
		expect(STRUCTURAL_SCC_REPORT_REQUEST_SCHEMA_VERSION).toBe(
			'jan-csaa-structural-scc-report-request/0.1.0'
		);
		expect(STRUCTURAL_SCC_REPORT_SCHEMA_VERSION).toBe('jan-csaa-structural-scc-report/0.1.0');
		expect(DEPENDENCY_CRUISER_PROVIDER_VERSION).toBe('16.10.4');
		expect(DEPENDENCY_CRUISER_NORMALIZATION_OPERATION_VERSION).toBe(
			'jan-csaa-normalize-dependency-cruiser-output/0.1.0'
		);
		expect(DEPENDENCY_PROVIDER_COMPARISON_OPERATION_VERSION).toBe(
			'jan-csaa-compare-dependency-providers/0.1.0'
		);
	});

	it('pins the provider version exactly at runtime and every repository declaration site', () => {
		const root = manifest('../../../package.json');
		const csaa = manifest('../package.json');
		const app = manifest('../../../apps/rph-demo/package.json');
		expect(ts.version).toBe(TYPESCRIPT_PROVIDER_VERSION);
		expect(root.devDependencies?.typescript).toBe(TYPESCRIPT_PROVIDER_VERSION);
		expect(app.devDependencies?.typescript).toBe(TYPESCRIPT_PROVIDER_VERSION);
		expect(csaa.dependencies?.typescript).toBe(TYPESCRIPT_PROVIDER_VERSION);
		expect(csaa.devDependencies?.typescript).toBeUndefined();
	});
});
