/**
 * Generate the Phase-9 executor LANGUAGE-sweep matrix.
 *
 *   npx tsx scripts/model-bakeoff/build-language-matrix.ts
 *
 * Crosses {models} × {languages} into one candidate per combination
 * (slug `<model>__<lang>`, forceStack `<lang>`) and writes
 * sweep-matrix-languages.json next to this script. Each candidate exports
 * JANUMICODE_FORCE_STACK so Phase-9 recon pins every area to that language —
 * isolating LANGUAGE as the only variable, holding the (slice-147-derived)
 * Phase-8 decomposition + the model constant. That answers the open question
 * from slice-147: was gpt-oss:20b's non-parsing scaffolding a model limit, or a
 * language mismatch (it had only ever been given TypeScript before)?
 *
 * Run it with:
 *   npx tsx scripts/model-bakeoff/run-bakeoff.ts \
 *     --config scripts/model-bakeoff/sweep-matrix-languages.json --tier 1 --resume
 *
 * gpt-oss is ordered first so the hypothesis-testing runs land first; --resume
 * lets the sweep span multiple sittings on one GPU.
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { expandLanguageSweep, type BakeoffSweepConfig, type SweepModel } from './bakeoffConfig';

// One representative server config per distinct MODEL (the context/KV sweep is
// an orthogonal axis — kept out of the language experiment to bound run count).
const MODELS: SweepModel[] = [
  {
    slug: 'gptoss-20b',
    modelTag: 'gpt-oss:20b',
    server: { flashAttention: true, contextLength: 131072 },
    goose: { inputLimit: 131072, contextLimit: 131072 },
    notes: 'Incumbent 20B at native 131k.',
  },
  {
    slug: 'gemma4-12b',
    modelTag: 'gemma4:12b-it-qat',
    // 256k: the system ollama runs this comfortably; the old 131k cap was an
    // alt-instance VRAM artifact that no longer applies and needlessly limited
    // the context (and could truncate large leaf prompts) vs the model's reach.
    server: { flashAttention: true, contextLength: 262144 },
    goose: { inputLimit: 262144, contextLimit: 262144 },
    notes: '12B QAT at 256k (its comfortable max on the system server).',
  },
  {
    slug: 'gemma4-26b',
    modelTag: 'gemma4:26b-a4b-it-qat',
    // 256k (was 64k — an alt-instance VRAM-fit artifact). Runs comfortably on
    // the system server; 64k could truncate larger leaf prompts unfairly.
    server: { flashAttention: true, kvCacheType: 'q8_0', contextLength: 262144 },
    goose: { inputLimit: 262144, contextLimit: 262144 },
    notes: '26B QAT at 256k (q8 KV) — strongest coder candidate.',
  },
];

// 'node' is the TypeScript/Node stack (STACK_EXTENSIONS.node → .ts first).
const LANGUAGES = ['node', 'python', 'go', 'rust', 'java'];

const config: BakeoffSweepConfig = {
  referenceWorkspace: 'test-and-evaluation/bakeoff-reference/reference-workspace',
  referenceDb: 'test-and-evaluation/bakeoff-reference/reference-phase8.db',
  outputDir: 'test-and-evaluation/bakeoff-results/language-sweep-1',
  systemOllamaPort: 11434,
  // The harness always uses the running system ollama (fast: 131-141 tok/s on
  // gpt-oss). It never spawns its own server — per-candidate server blocks below
  // are advisory only (the running server's own config governs).
  tier1: {
    globalTimeoutSeconds: 14400, // 4h: up to ~4 leaves × 30-min executor cap + overhead
    maxLeaves: 3,
    // Stream-gap watchdog (re-arms per chunk) — 600s is ample. The 30-min caps
    // below are the ones that matter for a long reasoning generation.
    noProgressSeconds: 600,
    maxCallSeconds: 1800,
    // Per-leaf executor cap 30 min (default 600s quarantined slow gpt-oss leaves
    // as "Process timed out"); idle 10 min (default 120s too short for silent
    // reasoning). Measures code quality given time, not raw speed.
    cliTimeoutSeconds: 1800,
    cliIdleTimeoutSeconds: 600,
  },
  tier2Finalists: [],
  candidates: expandLanguageSweep(MODELS, LANGUAGES),
};

const payload = {
  _comment:
    `Phase-9 executor LANGUAGE sweep: ${MODELS.length} models × ${LANGUAGES.length} languages = ` +
    `${config.candidates.length} candidates. Each forces JANUMICODE_FORCE_STACK so recon pins the ` +
    `language; topology + the slice-147 Phase-8 decomposition are held constant. Generated by ` +
    `build-language-matrix.ts — edit MODELS/LANGUAGES there and regenerate, do not hand-edit.`,
  ...config,
};

const outPath = join(__dirname, 'sweep-matrix-languages.json');
writeFileSync(outPath, JSON.stringify(payload, null, 2) + '\n', 'utf-8');
console.log(`[build-language-matrix] wrote ${config.candidates.length} candidates → ${outPath}`);
console.log(`[build-language-matrix] slugs: ${config.candidates.map((c) => c.slug).join(', ')}`);
