# Generated by Django 5.1.1 on 2025-02-11 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="squarecustomer",
            old_name="square_customer_id",
            new_name="square_id",
        ),
        migrations.AlterModelTable(
            name="squarecustomer",
            table=None,
        ),
        migrations.CreateModel(
            name="SquareSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("square_id", models.CharField(max_length=255, unique=True)),
                ("plan_variation_id", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("ACTIVE", "Active"),
                            ("CANCELED", "Canceled"),
                            ("DEACTIVATED", "Deactivated"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("charged_through_date", models.DateTimeField(blank=True, null=True)),
                ("canceled_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="subscriptions.squarecustomer",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
