// The PRODUCT-RUNTIME judge: Google Antigravity CLI (`agy`, Gemini) shelled out from the Node server.
// It is a DIFFERENT vendor than the Pi/Codex authoring executor — that is the whole point (exec != assurance).
// No Python dependency, no sidecar: `agy` is already configured, and Node spawns it as a child process.
//
// It matches the user's authorized invocation pattern exactly — a plain `agy --print "<prompt>"`. The graph export
// (+ the agent's plan) is passed INLINE in the prompt, so this is a PURE-REASONING call: the judge needs no tools,
// no workspace, and no permission bypass (no --add-dir / --sandbox / --dangerously-skip-permissions). No `--json`
// flag exists, so we prompt for strict JSON and parse defensively (fence-strip + brace-extract + one bounded retry).
// Model is `agy`'s configured default unless JPWB_JUDGE_MODEL pins one; binary is `agy` unless JPWB_AGY_BIN overrides.
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import type {
	AssessmentInput,
	AssessmentResult,
	CriterionScore,
	FaithfulnessAssessor,
	FaithfulnessVerdict
} from './types.js';

const execFileAsync = promisify(execFile);

const AGY_BIN = process.env.JPWB_AGY_BIN ?? 'agy';
const JUDGE_MODEL = process.env.JPWB_JUDGE_MODEL; // optional pin; omit → agy default
const PRINT_TIMEOUT = '3m';
const SPAWN_TIMEOUT_MS = 240_000;
const MAX_BUFFER = 16 * 1024 * 1024;
// Keep the whole inline prompt comfortably under the Windows CreateProcess command-line limit (~32k chars).
const MAX_PROMPT_CHARS = 28_000;

const VERDICTS: readonly FaithfulnessVerdict[] = ['FAITHFUL', 'PARTIAL', 'POOR'];

/** The strict-JSON rubric with the export inlined. Criteria are GENERIC — the judge derives them from the prompt,
 *  not from hardcoded SDLC dimensions — so this works for any PWA, not just the V-model/UCD/JTBD example. */
function judgePrompt(input: AssessmentInput): string {
	let exportJson = JSON.stringify(input.graphExport);
	// Belt-and-suspenders: if a very large graph would blow the command-line limit, truncate the raw JSON (the
	// judge still gets the head of the structure). Typical PWAs are a few KB and never hit this.
	if (exportJson.length > MAX_PROMPT_CHARS) {
		exportJson = `${exportJson.slice(0, MAX_PROMPT_CHARS)} …(export truncated)`;
	}
	const priorLine = input.prior
		? `\nThis is iteration ${input.iteration}. The PREVIOUS assessment scored ${input.prior.overallScore} overall with gaps: ${JSON.stringify(input.prior.gaps)}. Judge whether the graph has genuinely improved on those gaps, not just changed.`
		: '';
	const planLine = input.plan
		? `\nThe generating agent's OWN recorded plan / narration (what it intended):\n"""${input.plan.slice(0, 4000)}"""`
		: '';
	return [
		'You are an independent assurance reviewer. A PWA is a reusable software-engineering work architecture:',
		'a HIERARCHY of PWU Types (permits edges = decomposition / part-of) with DATA-FLOW between them',
		"(a producer's requiredOutput artifact feeds a consumer's requiredInput). It was generated by a DIFFERENT",
		'AI agent from this exact prompt:',
		'',
		`"""${input.prompt}"""`,
		'',
		'Here is the canonical graph export (JSON) to judge — nodes carry pwuKind / requiredInputs / requiredOutputs,',
		'plus permits, dataFlow, artifacts, roots:',
		'',
		exportJson,
		planLine,
		priorLine,
		'',
		'Judge how well the GENERATED graph is a reasonable, faithful, and COMPLETE interpretation of the prompt —',
		'not merely whether it is well-formed. Derive the judging criteria FROM THE PROMPT ITSELF (the specific',
		'methodologies, frameworks, and requirements it names); do not assume a fixed rubric.',
		'',
		'Return ONLY a single-line, minified JSON object (no markdown fences, no prose) with EXACTLY these keys:',
		'{"verdict":"FAITHFUL|PARTIAL|POOR",',
		'"overallScore":<number 0.0-1.0>,',
		'"criteria":[{"name":"<prompt-derived dimension>","score":<0.0-1.0>,"rationale":"<cite node names>"}],',
		'"gaps":["<specific thing the prompt asked for that is missing or weak>"],',
		'"recommendation":"<one short paragraph>"}'
	]
		.filter(Boolean)
		.join('\n');
}

function extractJson(raw: string): string {
	let s = raw.trim();
	const fence = /```(?:json)?\s*([\s\S]*?)```/i.exec(s);
	if (fence) s = fence[1].trim();
	const first = s.indexOf('{');
	const last = s.lastIndexOf('}');
	if (first >= 0 && last > first) s = s.slice(first, last + 1);
	return s;
}

const clamp01 = (n: unknown): number => {
	const x = typeof n === 'number' && Number.isFinite(n) ? n : 0;
	return x < 0 ? 0 : x > 1 ? 1 : x;
};
const asStringArray = (v: unknown): string[] =>
	Array.isArray(v) ? v.filter((x): x is string => typeof x === 'string') : [];

function coerce(parsed: unknown, model: string): AssessmentResult {
	const o = (parsed ?? {}) as Record<string, unknown>;
	const verdict: FaithfulnessVerdict = VERDICTS.includes(o.verdict as FaithfulnessVerdict)
		? (o.verdict as FaithfulnessVerdict)
		: 'PARTIAL';
	const criteria: CriterionScore[] = Array.isArray(o.criteria)
		? (o.criteria as Record<string, unknown>[]).map((c) => ({
				name: typeof c?.name === 'string' ? c.name : 'criterion',
				score: clamp01(c?.score),
				...(typeof c?.rationale === 'string' ? { rationale: c.rationale } : {})
			}))
		: [];
	return {
		verdict,
		overallScore: clamp01(o.overallScore),
		criteria,
		gaps: asStringArray(o.gaps),
		recommendation: typeof o.recommendation === 'string' ? o.recommendation : '',
		assessorModel: model
	};
}

/** One plain, non-interactive `agy --print` call — no tools, no workspace, no permission bypass. */
async function runAgy(prompt: string): Promise<string> {
	const args = [
		'--print',
		prompt,
		'--print-timeout',
		PRINT_TIMEOUT,
		...(JUDGE_MODEL ? ['--model', JUDGE_MODEL] : [])
	];
	const { stdout } = await execFileAsync(AGY_BIN, args, {
		timeout: SPAWN_TIMEOUT_MS,
		maxBuffer: MAX_BUFFER,
		windowsHide: true
	});
	return stdout;
}

export function createAgyAssessor(): FaithfulnessAssessor {
	return {
		kind: 'agy',
		async assess(input: AssessmentInput): Promise<AssessmentResult> {
			const model = JUDGE_MODEL ?? 'agy:default';
			const prompt = judgePrompt(input);
			let stdout = await runAgy(prompt);
			try {
				return coerce(JSON.parse(extractJson(stdout)), model);
			} catch {
				// One bounded retry with a stricter instruction — the judge occasionally adds prose.
				stdout = await runAgy(
					`${prompt}\n\nIMPORTANT: your previous reply was not valid JSON. Reply with ONLY the minified JSON object.`
				);
				return coerce(JSON.parse(extractJson(stdout)), model);
			}
		}
	};
}
