/**
 * LLM provider abstraction.
 *
 * Per docs/janumilegal_implementation_roadmap.md Wave 2 §2.3 §2.4:
 *   - LLM provider abstraction (model-agnostic).
 *   - Per-matter prompt-cache namespace; no cache key may be reused across matters.
 *   - Provider request headers carry no matter-identifying content.
 *
 * Wave 2 ships: interface, MockProvider for tests, matter-scoped cache key.
 * Wave 6+ ships: AnthropicProvider, prompt caching wired to Anthropic SDK.
 */

import { createHash } from 'node:crypto';
import type { Scope } from '../database/types.js';

export interface LLMRequest {
  readonly system?: string;
  readonly messages: readonly LLMMessage[];
  readonly maxTokens?: number;
  readonly temperature?: number;
  readonly model?: string;
  /** Matter-scoped cache namespace key. Generated by `cacheKeyForScope`. */
  readonly cacheNamespace: string;
}

export interface LLMMessage {
  readonly role: 'user' | 'assistant';
  readonly content: string;
}

export interface LLMResponse {
  readonly content: string;
  readonly stopReason?: string;
  readonly usage?: {
    readonly inputTokens?: number;
    readonly outputTokens?: number;
    readonly cacheReadTokens?: number;
    readonly cacheCreationTokens?: number;
  };
}

export interface LLMProvider {
  readonly name: string;
  invoke(request: LLMRequest): Promise<LLMResponse>;
}

/**
 * Per-matter cache namespace. The cache key for any prompt must include
 * this namespace to prevent cross-matter cache reuse.
 *
 * The namespace is a stable hash of the matter scope tuple — never the raw
 * client/matter ids — so provider-side cache keys do not carry matter-
 * identifying content (privilege design §11).
 */
export function cacheKeyForScope(scope: Scope): string {
  const h = createHash('sha256');
  h.update(scope.firmId);
  h.update('|');
  h.update(scope.clientId);
  h.update('|');
  h.update(scope.matterId);
  return `m_${h.digest('hex').slice(0, 24)}`;
}
