# Generated by Django 5.1.1 on 2025-05-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_propertyscrapeddata'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
