# Generated by Django 5.1.1 on 2025-05-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='geocode_address',
            field=models.JSONField(blank=True, default=dict, help_text='Structured address data from geocoding service'),
        ),
        migrations.AddField(
            model_name='property',
            name='geocode_address_source',
            field=models.CharField(blank=True, help_text="Source service used for geocoding (e.g., 'AZURE_MAPS')", max_length=50, null=True),
        ),
    ]
