# Generated by Django 5.1.1 on 2025-06-04 21:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_property_geocode_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermitHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_permit_data', models.JSONField(default=dict, help_text='Raw permit data from web scraping source')),
                ('permit_number', models.CharField(blank=True, help_text='Official permit number', max_length=255, null=True)),
                ('permit_type', models.CharField(blank=True, help_text='Type of permit (e.g., Building, Electrical, Plumbing, etc.)', max_length=255, null=True)),
                ('permit_description', models.TextField(blank=True, help_text='Description of the permit work', null=True)),
                ('permit_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', help_text='Current status of the permit', max_length=20)),
                ('application_date', models.DateField(blank=True, help_text='Date the permit application was submitted', null=True)),
                ('issued_date', models.DateField(blank=True, help_text='Date the permit was issued', null=True)),
                ('expiration_date', models.DateField(blank=True, help_text='Date the permit expires', null=True)),
                ('completion_date', models.DateField(blank=True, help_text='Date the permit work was completed', null=True)),
                ('contractor_name', models.CharField(blank=True, help_text='Name of the contractor for the permit', max_length=255, null=True)),
                ('contractor_license', models.CharField(blank=True, help_text='License number of the contractor', max_length=255, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated cost of the permit work', max_digits=12, null=True)),
                ('source_name', models.CharField(blank=True, help_text='Name of the data source (e.g., county website, permit portal)', max_length=255, null=True)),
                ('source_url', models.URLField(blank=True, help_text='URL where the permit data was scraped from', null=True)),
                ('extracted_fields', models.JSONField(default=dict, help_text="Additional extracted fields that don't fit standard schema")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scraped_at', models.DateTimeField(blank=True, help_text='When this permit data was originally scraped', null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permit_history', to='properties.property')),
            ],
            options={
                'verbose_name_plural': 'Permit History',
                'ordering': ['-created_at'],
                'permissions': [('view_permit_history', 'Can view permit history'), ('manage_permit_history', 'Can manage permit history')],
            },
        ),
        migrations.CreateModel(
            name='PermitAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(help_text='Original filename of the attachment', max_length=255)),
                ('file_type', models.CharField(help_text='MIME type of the file (e.g., application/pdf, image/jpeg)', max_length=50)),
                ('file_size', models.BigIntegerField(help_text='Size of the file in bytes')),
                ('file_data', models.BinaryField(help_text='Binary data of the attachment file')),
                ('description', models.TextField(blank=True, help_text='Description of the attachment', null=True)),
                ('attachment_type', models.CharField(blank=True, help_text='Type of attachment (e.g., permit_document, inspection_report, plans)', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('permit_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='properties.permithistory')),
            ],
            options={
                'verbose_name_plural': 'Permit Attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='permithistory',
            index=models.Index(fields=['property', '-created_at'], name='properties__propert_256b83_idx'),
        ),
        migrations.AddIndex(
            model_name='permithistory',
            index=models.Index(fields=['permit_number'], name='properties__permit__11ed98_idx'),
        ),
        migrations.AddIndex(
            model_name='permithistory',
            index=models.Index(fields=['permit_type'], name='properties__permit__ef6942_idx'),
        ),
        migrations.AddIndex(
            model_name='permithistory',
            index=models.Index(fields=['permit_status'], name='properties__permit__b1d14b_idx'),
        ),
        migrations.AddIndex(
            model_name='permithistory',
            index=models.Index(fields=['source_name'], name='properties__source__5b444f_idx'),
        ),
        migrations.AddIndex(
            model_name='permithistory',
            index=models.Index(fields=['application_date'], name='properties__applica_4480c7_idx'),
        ),
        migrations.AddIndex(
            model_name='permithistory',
            index=models.Index(fields=['issued_date'], name='properties__issued__802fd6_idx'),
        ),
        migrations.AddIndex(
            model_name='permitattachment',
            index=models.Index(fields=['permit_history', '-created_at'], name='properties__permit__a8582f_idx'),
        ),
        migrations.AddIndex(
            model_name='permitattachment',
            index=models.Index(fields=['file_type'], name='properties__file_ty_4415be_idx'),
        ),
        migrations.AddIndex(
            model_name='permitattachment',
            index=models.Index(fields=['attachment_type'], name='properties__attachm_f2b02c_idx'),
        ),
    ]
