# Generated by Django 5.1.1 on 2025-06-08 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_permithistory_permitattachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='permit_last_retrieved_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last successful permit retrieval', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='permit_next_retrieval_at',
            field=models.DateTimeField(blank=True, help_text='Scheduled timestamp for next permit retrieval attempt', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='permit_retrieval_error',
            field=models.TextField(blank=True, help_text='Error message from last failed permit retrieval attempt', null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='permit_retrieval_status',
            field=models.CharField(choices=[('NEVER_ATTEMPTED', 'Never Attempted'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('SCHEDULED', 'Scheduled')], default='NEVER_ATTEMPTED', help_text='Status of permit history retrieval process', max_length=20),
        ),
        migrations.AddField(
            model_name='property',
            name='permit_retrieval_workflow_id',
            field=models.CharField(blank=True, help_text='Temporal workflow ID for permit retrieval process', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='permithistory',
            name='permit_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('UNKNOWN', 'Unknown'), ('FAILED_RETRIEVAL', 'Failed Retrieval')], default='UNKNOWN', help_text='Current status of the permit', max_length=20),
        ),
    ]
