# Generated by Django 5.1.1 on 2025-06-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_property_permit_last_retrieved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyscrapeddata',
            name='scrape_type',
            field=models.CharField(choices=[('PERMIT_HISTORY', 'Permit History'), ('PROPERTY_DETAILS', 'Property Details'), ('SERVICE_REVIEWS', 'Service Reviews'), ('RAW_CONTENT', 'Raw Web Content'), ('OTHER', 'Other')], default='RAW_CONTENT', help_text='Type of data scraped, indicating how it should be processed.', max_length=50),
        ),
    ]
