# Generated by Django 5.1.1 on 2025-06-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_propertyscrapeddata_scrape_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyscrapeddata',
            name='tracking_id',
            field=models.CharField(blank=True, db_index=True, help_text='Tracking ID for linking related scrapes, can contain two UUID-length values', max_length=255, null=True),
        ),
    ]
