# Generated by Django 5.1.1 on 2025-06-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_propertyscrapeddata_tracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyscrapeddata',
            name='source_url',
            field=models.TextField(help_text='URL of the scraped page - stored as TextField to handle longer URLs'),
        ),
    ]
