# Generated by Django 5.1.1 on 2025-06-13 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_alter_propertyscrapeddata_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyscrapeddata',
            name='processed_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of the scraping process', max_length=50),
        ),
    ]
