# Generated by Django 5.1.1 on 2025-10-12 12:54

import properties.descriptives_schema
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_propertyscrapeddata_processed_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='descriptives',
            field=models.JSONField(blank=True, default=properties.descriptives_schema.get_default_descriptives, help_text='Structured property descriptive data including HVAC, utilities, structure, etc.'),
        ),
    ]
