/**
 * slices:ledger — the Slice Ledger writer and gate. `bun run scripts/slice-ledger.ts --write | --check`
 *
 * ── MODELLED ON `csaa:inventory:check`, NOT ON `tracker:build` ───────────────────────────────────────────────
 * The choice is measured, not stylistic. `tracker:build` deletes and rebuilds a GITIGNORED database on every gate
 * run, so it cannot detect staleness at all — there is no committed artifact for it to disagree with.
 * `tracker:check`, the only named staleness gate in this repository, is in NO gate. The Slice ledger is
 * COMMITTED, because a progress record nobody can read in the repo is not a progress record. A committed artifact
 * can go stale, so it needs a check, and the CSAA inventory is the repository's worked example of one.
 *
 * ── TWO WAYS TO FAIL, EACH NAMED ────────────────────────────────────────────────────────────────────────────
 *   LEDGER_STALE   — a committed product differs from what the declarations generate. Reported per path with
 *                    byte counts and sha256 on both sides, never as a text diff.
 *   <a refusal>    — a declaration is malformed. Every message names the file and the field, because a check
 *                    that fails without saying which law broke teaches its reader to re-run until green.
 *
 * ⚠ `--check` NEVER WRITES. That is the whole point of having two modes rather than one that "fixes" things.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
	buildLedger,
	canonicalJson,
	renderRegion,
	replaceRegion,
	sha256,
	BEGIN,
	END
} from '../verif/slice-ledger.js';

const SCRIPT_DIR = fileURLToPath(new URL('.', import.meta.url));
const ROOT = resolve(join(SCRIPT_DIR, '..'));

const LEDGER_MD = 'docs/tracking/slices/LEDGER.md';
const BASELINE = 'verif/slices/slice-ledger.baseline.json';

const flags = process.argv.slice(2);
const selected = flags.filter((f) => f === '--write' || f === '--check');

if (selected.length !== 1 || selected.length !== flags.length) {
	process.stderr.write(
		`${JSON.stringify({ error: 'usage', message: 'Use exactly one of --write or --check.' })}\n`
	);
	process.exit(2);
}

const mode = selected[0]!.slice(2) as 'write' | 'check';

/** The document shell. Only the region between the markers is generated; the preamble is a human's to write. */
function shell(): string {
	const path = join(ROOT, LEDGER_MD);
	try {
		return readFileSync(path, 'utf8');
	} catch {
		return [
			'# The Slice Ledger',
			'',
			'The derived record of every JAN-SLICE Slice. **Nothing in this file is hand-maintained** — the region',
			'below is generated by `verif/slice-ledger.ts` and the gate `slices:ledger:check` fails when the',
			'committed bytes differ from what the Slice declarations produce.',
			'',
			'Progress for JAN-SLICE is read here and nowhere else. `JPWB-REG-005` remains canonical; this is a',
			'derived view of it and never an authority over it.',
			'',
			BEGIN,
			END,
			''
		].join('\n');
	}
}

try {
	const ledger = buildLedger(ROOT);
	const products: { path: string; text: string }[] = [
		{ path: LEDGER_MD, text: replaceRegion(shell(), renderRegion(ledger)) },
		{
			path: BASELINE,
			text: canonicalJson({
				canary: 'packages/rph-engine/test-fixtures/slice-predicate-canary/CANARY.slice.test.ts',
				recognisedCount: ledger.recognisedCount,
				rows: ledger.rows
			})
		}
	];

	if (mode === 'write') {
		for (const p of products) {
			const abs = join(ROOT, p.path);
			mkdirSync(dirname(abs), { recursive: true });
			writeFileSync(abs, p.text, 'utf8');
		}
		process.stdout.write(
			`${JSON.stringify({ mode, ok: true, recognised: ledger.recognisedCount, written: products.map((p) => p.path) })}\n`
		);
	} else {
		const differences = products
			.map((p) => {
				let committed = '';
				try {
					committed = readFileSync(join(ROOT, p.path), 'utf8');
				} catch {
					committed = '';
				}
				if (committed === p.text) return null;
				return {
					actualBytes: Buffer.byteLength(committed, 'utf8'),
					actualSha256: sha256(committed),
					expectedBytes: Buffer.byteLength(p.text, 'utf8'),
					expectedSha256: sha256(p.text),
					path: p.path
				};
			})
			.filter((d) => d !== null);

		const ok = differences.length === 0;
		process.stdout.write(`${JSON.stringify({ differences, mode, ok, reason: ok ? null : 'LEDGER_STALE' })}\n`);
		if (!ok) process.exitCode = 1;
	}
} catch (error) {
	process.stderr.write(
		`${JSON.stringify({ error: 'slice-ledger-failed', message: error instanceof Error ? error.message : String(error) })}\n`
	);
	process.exitCode = 1;
}
