# Generated by Django 5.1.1 on 2024-12-09 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0003_initial'),
        ('properties', '0002_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_provider_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicebid',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submitted_bids', to='services.serviceprovider'),
        ),
        migrations.AddField(
            model_name='providercategory',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.serviceprovider'),
        ),
        migrations.AddField(
            model_name='servicereport',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='attachments',
            field=models.ManyToManyField(blank=True, help_text='Media files attached to this service request', related_name='service_request_attachments', to='media.media'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='properties.property'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='services.serviceprovider'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='runner_up_provider',
            field=models.ForeignKey(help_text='The runner-up service provider for this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runner_up_requests', to='services.serviceprovider'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='selected_provider',
            field=models.ForeignKey(help_text='The service provider selected for this request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_requests', to='services.serviceprovider'),
        ),
        migrations.AddField(
            model_name='servicereport',
            name='service_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='services.servicerequest'),
        ),
        migrations.AddField(
            model_name='servicebid',
            name='service_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='services.servicerequest'),
        ),
        migrations.AddField(
            model_name='servicerequestclarification',
            name='attachments',
            field=models.ManyToManyField(related_name='clarification_attachments', to='media.media'),
        ),
        migrations.AddField(
            model_name='servicerequestclarification',
            name='question_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asked_clarifications', to='services.serviceprovider'),
        ),
        migrations.AddField(
            model_name='servicerequestclarification',
            name='service_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clarifications', to='services.servicerequest'),
        ),
        migrations.AddField(
            model_name='servicerequestinterest',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_interests', to='services.serviceprovider'),
        ),
        migrations.AddField(
            model_name='servicerequestinterest',
            name='service_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to='services.servicerequest'),
        ),
        migrations.AddField(
            model_name='servicerequestview',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewed_requests', to='services.serviceprovider'),
        ),
        migrations.AddField(
            model_name='servicerequestview',
            name='service_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='services.servicerequest'),
        ),
        migrations.AddField(
            model_name='servicereview',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicereview',
            name='service_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='services.servicerequest'),
        ),
        migrations.AlterUniqueTogether(
            name='providercategory',
            unique_together={('provider', 'category')},
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['status', '-created_at'], name='services_se_status_f1d047_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['provider', 'status'], name='services_se_provide_d38524_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['property', '-created_at'], name='services_se_propert_ae6d74_idx'),
        ),
        migrations.AddIndex(
            model_name='servicebid',
            index=models.Index(fields=['service_request', 'status'], name='services_se_service_15f670_idx'),
        ),
        migrations.AddIndex(
            model_name='servicebid',
            index=models.Index(fields=['provider', '-created_at'], name='services_se_provide_04326a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='servicebid',
            unique_together={('service_request', 'provider')},
        ),
        migrations.AddIndex(
            model_name='servicerequestclarification',
            index=models.Index(fields=['service_request', '-created_at'], name='services_se_service_7e9107_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequestinterest',
            index=models.Index(fields=['service_request', 'interest_status'], name='services_se_service_e36f45_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequestinterest',
            index=models.Index(fields=['provider', '-created_at'], name='services_se_provide_2b07cb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='servicerequestinterest',
            unique_together={('service_request', 'provider')},
        ),
        migrations.AddIndex(
            model_name='servicerequestview',
            index=models.Index(fields=['service_request', '-viewed_at'], name='services_se_service_a18d2b_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequestview',
            index=models.Index(fields=['provider', '-viewed_at'], name='services_se_provide_57f62f_idx'),
        ),
    ]
