# Generated by Django 5.1.1 on 2024-12-13 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='attachments',
        ),
        migrations.RemoveField(
            model_name='servicerequestclarification',
            name='attachments',
        ),
    ]
