# Generated by Django 5.1.1 on 2025-01-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_servicerequest_attachments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providercategory',
            name='category',
            field=models.CharField(choices=[('PLUMBING', 'Plumbing'), ('ELECTRICAL', 'Electrical'), ('HVAC', 'HVAC'), ('GENERAL_MAINTENANCE', 'General Maintenance'), ('LANDSCAPING', 'Landscaping'), ('CLEANING', 'Cleaning'), ('SECURITY', 'Security'), ('PEST_CONTROL', 'Pest Control'), ('ROOFING', 'Roofing'), ('REMODELING', 'Remodeling'), ('OTHER', 'Other')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='category',
            field=models.CharField(choices=[('PLUMBING', 'Plumbing'), ('ELECTRICAL', 'Electrical'), ('HVAC', 'HVAC'), ('GENERAL_MAINTENANCE', 'General Maintenance'), ('LANDSCAPING', 'Landscaping'), ('CLEANING', 'Cleaning'), ('SECURITY', 'Security'), ('PEST_CONTROL', 'Pest Control'), ('ROOFING', 'Roofing'), ('REMODELING', 'Remodeling'), ('OTHER', 'Other')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('BIDDING', 'Open for Bidding'), ('REOPENED_BIDDING', 'Reopened for Bidding'), ('ACCEPTED', 'Accepted'), ('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('DECLINED', 'Declined'), ('IN_RESEARCH', 'In Research')], default='PENDING', max_length=20),
        ),
    ]
