# Generated by Django 5.1.1 on 2025-02-28 14:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_servicerequest_is_diy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_RESEARCH', 'In Research'), ('BIDDING', 'Open for Bidding'), ('REOPENED_BIDDING', 'Reopened for Bidding'), ('ACCEPTED', 'Accepted'), ('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('DECLINED', 'Declined')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='ServiceResearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('research_data', models.JSONField(default=dict, help_text='Structured research data including candidate service providers')),
                ('research_content', models.TextField(blank=True, help_text='Rich text content with base64-encoded embedded images')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the research')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('researched_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_research', to=settings.AUTH_USER_MODEL)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_entries', to='services.servicerequest')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['service_request', '-created_at'], name='services_se_service_98fd2a_idx'), models.Index(fields=['researched_by', '-created_at'], name='services_se_researc_b9eb75_idx')],
            },
        ),
    ]
