# Generated by Django 5.1.1 on 2025-03-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_serviceresearch_data_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceresearch',
            name='research_content_raw_text',
            field=models.TextField(blank=True, help_text='Raw text content extracted from HTML (basically just copy-paste from browser)'),
        ),
    ]
