# Generated by Django 5.1.1 on 2025-04-07 10:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_serviceresearch_research_content_raw_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProviderScrapedData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_name', models.CharField(help_text="Name of the source website (e.g., 'Yelp', 'Angi', 'HomeAdvisor')", max_length=255)),
                ('source_url', models.URLField(help_text='URL of the scraped page')),
                ('raw_html', models.TextField(help_text='Raw HTML content from web scraping')),
                ('processed_data', models.JSONField(default=dict, help_text='Processed structured data extracted from raw HTML')),
                ('scrape_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of the scraping process', max_length=50)),
                ('error_message', models.TextField(blank=True, help_text='Error message if scraping failed', null=True)),
                ('last_scraped_at', models.DateTimeField(auto_now=True, help_text='Timestamp of when the data was last scraped')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scraped_data', to='services.serviceprovider')),
            ],
            options={
                'ordering': ['-last_scraped_at'],
                'indexes': [models.Index(fields=['service_provider', '-last_scraped_at'], name='services_se_service_481ec3_idx'), models.Index(fields=['source_name'], name='services_se_source__a4df3f_idx'), models.Index(fields=['scrape_status'], name='services_se_scrape__4fc318_idx')],
                'unique_together': {('service_provider', 'source_url')},
            },
        ),
    ]
