# Generated by Django 5.1.1 on 2025-04-25 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_remove_serviceprovider_user_serviceprovider_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='users',
        ),
    ]
