# Generated by Django 5.1.1 on 2025-04-25 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_remove_serviceprovider_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceresearch',
            name='service_provider_created',
            field=models.BooleanField(default=False, help_text='Indicates if a service provider was created from this research'),
        ),
    ]
