# Generated by Django 5.1.1 on 2025-08-25 13:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_serviceresearch_service_provider_created'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimelineEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('STATUS_CHANGE', 'Status Change'), ('COMMENT', 'Comment'), ('DOCUMENT_UPLOAD', 'Document Upload'), ('ESTIMATE_SUBMISSION', 'Estimate Submission'), ('PAYMENT', 'Payment'), ('SCHEDULING', 'Scheduling'), ('SYSTEM', 'System')], db_index=True, max_length=50)),
                ('content', models.TextField(blank=True, max_length=5000)),
                ('metadata', models.JSONField(default=dict, help_text='Additional metadata specific to the entry type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft deletion flag')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timeline_entries', to=settings.AUTH_USER_MODEL)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_entries', to='services.servicerequest')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_timeline_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Timeline Entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TimelineComment',
            fields=[
                ('timelineentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='services.timelineentry')),
                ('comment_type', models.CharField(choices=[('QUESTION', 'Question'), ('UPDATE', 'Update'), ('ISSUE', 'Issue'), ('GENERAL', 'General')], default='GENERAL', max_length=50)),
                ('visibility', models.CharField(choices=[('ALL', 'All'), ('PROPERTY_OWNER_ONLY', 'Property Owner Only'), ('PROVIDER_ONLY', 'Service Provider Only'), ('STAFF_ONLY', 'Staff Only')], default='ALL', max_length=50)),
                ('is_edited', models.BooleanField(default=False)),
                ('edit_history', models.JSONField(default=list, help_text='History of edits to this comment')),
                ('mentions', models.JSONField(default=list, help_text='Array of user IDs mentioned in this comment')),
            ],
            bases=('services.timelineentry',),
        ),
        migrations.CreateModel(
            name='TimelineReadReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('timeline_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_receipts', to='services.timelineentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_read_receipts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='timelineentry',
            index=models.Index(fields=['service_request', '-created_at'], name='services_ti_service_b8afe7_idx'),
        ),
        migrations.AddIndex(
            model_name='timelineentry',
            index=models.Index(fields=['entry_type'], name='services_ti_entry_t_4d0ac8_idx'),
        ),
        migrations.AddIndex(
            model_name='timelineentry',
            index=models.Index(fields=['created_by'], name='services_ti_created_2d212f_idx'),
        ),
        migrations.AddIndex(
            model_name='timelineentry',
            index=models.Index(fields=['is_deleted'], name='services_ti_is_dele_30ca5f_idx'),
        ),
        migrations.AddIndex(
            model_name='timelinereadreceipt',
            index=models.Index(fields=['timeline_entry', 'user'], name='services_ti_timelin_c5089e_idx'),
        ),
        migrations.AddIndex(
            model_name='timelinereadreceipt',
            index=models.Index(fields=['user', 'read_at'], name='services_ti_user_id_305660_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='timelinereadreceipt',
            unique_together={('timeline_entry', 'user')},
        ),
    ]
