# Generated by Django 4.2.7 on 2025-10-29 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0013_timelineentry_timelinecomment_timelinereadreceipt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='assigned_to',
            field=models.ForeignKey(
                blank=True,
                help_text='STAFF member assigned to handle this service request',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='assigned_requests',
                to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
