# Generated by Django 5.1.1 on 2025-10-31 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_add_provider_outreach_model'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='provideroutreach',
            new_name='services_pr_service_1c9318_idx',
            old_name='services_pr_service_idx',
        ),
        migrations.RenameIndex(
            model_name='provideroutreach',
            new_name='services_pr_provide_1f6357_idx',
            old_name='services_pr_provide_idx',
        ),
        migrations.RenameIndex(
            model_name='provideroutreach',
            new_name='services_pr_last_co_2d7479_idx',
            old_name='services_pr_last_co_idx',
        ),
    ]
