# Generated by Django 5.1.1 on 2025-11-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_rename_services_pr_service_idx_services_pr_service_1c9318_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceresearch',
            name='source_url',
            field=models.URLField(blank=True, help_text='URL of the source where the research data was obtained', max_length=2048),
        ),
    ]
