# Generated by Django 5.1.1 on 2025-11-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_serviceresearch_source_url'),
    ]

    operations = [
        # Add provenance fields to ServiceProvider
        migrations.AddField(
            model_name='serviceprovider',
            name='enriched_sources',
            field=models.JSONField(default=list, help_text='Array of source URLs/names that contributed to this provider'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='enriched_at',
            field=models.DateTimeField(blank=True, help_text='Last enrichment timestamp', null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='enrichment_metadata',
            field=models.JSONField(default=dict, help_text='Additional enrichment context (e.g., confidence scores, merge history)'),
        ),
        # Update ServiceProvider.service_area help text
        migrations.AlterField(
            model_name='serviceprovider',
            name='service_area',
            field=models.JSONField(default=dict, help_text='Service area with normalized geography: {normalized: {counties: [...], states: [...], independent_cities: [...]}, raw_tags: [...]}'),
        ),
        # Make ServiceProviderScrapedData.service_provider nullable
        migrations.AlterField(
            model_name='serviceproviderscrapeddata',
            name='service_provider',
            field=models.ForeignKey(blank=True, help_text='Linked service provider (nullable for new scraped data)', null=True, on_delete=models.deletion.CASCADE, related_name='scraped_data', to='services.serviceprovider'),
        ),
        # Add intervention fields to ServiceProviderScrapedData
        migrations.AddField(
            model_name='serviceproviderscrapeddata',
            name='intervention_reason',
            field=models.TextField(blank=True, help_text='Explanation for why manual intervention is needed', null=True),
        ),
        migrations.AddField(
            model_name='serviceproviderscrapeddata',
            name='workflow_id',
            field=models.CharField(blank=True, help_text='DBOS workflow ID for tracking', max_length=255, null=True),
        ),
        # Update scrape_status choices to include paused_intervention
        migrations.AlterField(
            model_name='serviceproviderscrapeddata',
            name='scrape_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('paused_intervention', 'Paused - Needs Intervention')], default='pending', help_text='Status of the scraping and processing workflow', max_length=50),
        ),
        # Update error_message help text
        migrations.AlterField(
            model_name='serviceproviderscrapeddata',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message if scraping/processing failed', null=True),
        ),
        # Remove unique_together constraint since service_provider can be null
        migrations.AlterUniqueTogether(
            name='serviceproviderscrapeddata',
            unique_together=set(),
        ),
    ]
