# Generated by Django 5.1.1 on 2025-11-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_add_contact_fields_to_service_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproviderscrapeddata',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or context about this scraped data'),
        ),
        migrations.AddField(
            model_name='serviceproviderscrapeddata',
            name='processed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of when the data was successfully processed', null=True),
        ),
        migrations.AddField(
            model_name='serviceproviderscrapeddata',
            name='raw_text',
            field=models.TextField(blank=True, help_text='Plain text content extracted from the page'),
        ),
        migrations.AlterField(
            model_name='serviceproviderscrapeddata',
            name='raw_html',
            field=models.TextField(blank=True, help_text='Raw HTML content from web scraping'),
        ),
    ]
