# Generated by Django 5.1.1 on 2025-11-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_serviceproviderscrapeddata_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceproviderscrapeddata',
            name='source_url',
            field=models.URLField(help_text='URL of the scraped page', max_length=2048),
        ),
    ]
