# Generated by Django 5.1.1 on 2025-11-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_alter_serviceproviderscrapeddata_source_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='business_license',
            field=models.CharField(blank=True, help_text='Business license or registration number', max_length=255, null=True),
        ),
    ]
