# Generated by Django 5.1.1 on 2025-11-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_alter_serviceprovider_business_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceproviderscrapeddata',
            name='candidate_providers',
            field=models.JSONField(blank=True, default=list, help_text='List of candidate provider IDs when manual intervention is needed'),
        ),
        migrations.AddField(
            model_name='serviceproviderscrapeddata',
            name='match_scores',
            field=models.JSONField(blank=True, default=dict, help_text='Match scores for candidate providers (provider_id -> score)'),
        ),
    ]
