# Generated by Django 5.1.1 on 2025-11-06 18:02

import django.contrib.gis.db.models.fields
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0023_serviceproviderscrapeddata_candidate_providers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='address',
            field=models.TextField(blank=True, help_text='Full business address', null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='business_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Geographic location of business (latitude, longitude)', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='description_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, help_text='Vector embedding of business description for semantic search', null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='merged_data',
            field=models.JSONField(blank=True, default=dict, help_text='Consolidated data from all scraped sources (JSONB with GIN index)'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='plus_code',
            field=models.CharField(blank=True, help_text='Google Plus Code for location', max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='serviceprovider',
            index=models.Index(fields=['business_location'], name='services_se_busines_0832ea_idx'),
        ),
    ]
