# Generated by Django 5.1.1 on 2025-11-07 16:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0028_update_embedding_dimensions_to_4096'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('search_query', models.CharField(help_text="Search query used to find this provider (e.g., 'Milcon HVAC')", max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this scrape group')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Staff member who created this scrape group', on_delete=django.db.models.deletion.CASCADE, related_name='scrape_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='serviceproviderscrapeddata',
            name='scrape_group',
            field=models.ForeignKey(blank=True, help_text='Optional group linking related scrapes for the same entity', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scraped_data', to='services.scrapegroup'),
        ),
        migrations.AddIndex(
            model_name='scrapegroup',
            index=models.Index(fields=['created_by', '-created_at'], name='services_sc_created_2edcca_idx'),
        ),
    ]
