# Generated by Django 5.1.1 on 2025-11-07 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0029_scrapegroup_serviceproviderscrapeddata_scrape_group_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceproviderscrapeddata',
            name='scrape_group',
            field=models.ForeignKey(blank=True, help_text='Optional group linking related scrapes for the same entity', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scraped_data', to='services.scrapegroup'),
        ),
    ]
