/**
 * Family Law Production Lens — manifest.
 *
 * Per docs/janumilegal_product_description.md §Test Use Case (lines 1040–2511).
 *
 * Wave 6 ships a structurally-sufficient subset of the 22-state lens that
 * produces all snapshot fields the gold-matter assertion set checks. The
 * full 22-state lens is reachable in Wave 7+ as agent implementations land.
 *
 * Layer 2 — practice-area lens pack.
 */

import type { LensPhaseManifest } from '../../lib/orchestrator/types.js';

export const FAMILY_LAW_LENS_ID = 'family_law_production_lens';
export const FAMILY_LAW_LENS_VERSION = 'v1';

export const FAMILY_LAW_AGENTS = {
  matterContextNormalize: 'family_law_matter_context_normalize_agent.v1',
  jurisdictionCapture: 'family_law_jurisdiction_capture_agent.v1',
  factExtraction: 'family_law_fact_extraction_agent.v1',
  existingOrderExtract: 'family_law_existing_order_extract_agent.v1',
  issueBloom: 'family_law_issue_bloom_agent.v1',
  issuePrune: 'family_law_issue_prune_agent.v1',
  authorityVerification: 'family_law_authority_verification_agent.v1',
  directLegalConclusion: 'family_law_direct_legal_conclusion_agent.v1',
  clientAdviceDraft: 'family_law_client_advice_draft_agent.v1',
  courtFilingDraft: 'family_law_court_filing_draft_agent.v1',
  releaseStatusDetermine: 'family_law_release_status_determine_agent.v1',
} as const;

export const familyLawProductionManifest: LensPhaseManifest = {
  lensId: FAMILY_LAW_LENS_ID,
  lensVersion: FAMILY_LAW_LENS_VERSION,
  practiceArea: 'family_law',
  applicableJurisdictions: ['MD', 'VA', 'PA', 'DC'],
  states: [
    {
      stateId: 'MatterContextNormalize',
      required: true,
      predecessors: [],
      permittedAgents: [FAMILY_LAW_AGENTS.matterContextNormalize],
      inputSchema: 'MatterContextNormalizeInput.v1',
      outputSchema: 'MatterContextNormalizeOutput.v1',
      validators: [],
      escalationConditions: [],
      clvScope: ['clv.core.matter.v1', 'clv.core.client.v1'],
      artifactsProduced: [],
    },
    {
      stateId: 'JurisdictionCapture',
      required: true,
      predecessors: ['MatterContextNormalize'],
      permittedAgents: [FAMILY_LAW_AGENTS.jurisdictionCapture],
      inputSchema: 'JurisdictionCaptureInput.v1',
      outputSchema: 'JurisdictionCaptureOutput.v1',
      validators: [],
      escalationConditions: [],
      clvScope: ['clv.core.matter.v1'],
      artifactsProduced: [],
    },
    {
      stateId: 'FactExtraction',
      required: true,
      predecessors: ['JurisdictionCapture'],
      permittedAgents: [FAMILY_LAW_AGENTS.factExtraction],
      inputSchema: 'FactExtractionInput.v1',
      outputSchema: 'FactExtractionOutput.v1',
      validators: [],
      escalationConditions: [],
      clvScope: ['clv.core.fact.v1', 'clv.core.source.v1'],
      artifactsProduced: [],
    },
    {
      stateId: 'ExistingOrderExtract',
      required: true,
      predecessors: ['FactExtraction'],
      permittedAgents: [FAMILY_LAW_AGENTS.existingOrderExtract],
      inputSchema: 'ExistingOrderExtractInput.v1',
      outputSchema: 'ExistingOrderExtractOutput.v1',
      validators: [],
      escalationConditions: [],
      clvScope: ['clv.core.authority.v1', 'clv.core.source.v1'],
      artifactsProduced: [],
    },
    {
      stateId: 'IssueBloom',
      required: true,
      predecessors: ['ExistingOrderExtract'],
      permittedAgents: [FAMILY_LAW_AGENTS.issueBloom],
      inputSchema: 'IssueBloomInput.v1',
      outputSchema: 'IssueCandidateSet.v1',
      validators: [],
      escalationConditions: [],
      clvScope: ['clv.core.issue.v1'],
      artifactsProduced: [],
      isHandoffBoundary: true,
    },
    {
      stateId: 'IssuePrune',
      required: true,
      predecessors: ['IssueBloom'],
      permittedAgents: [FAMILY_LAW_AGENTS.issuePrune],
      inputSchema: 'IssuePruneInput.v1',
      outputSchema: 'PruningDecisionSet.v1',
      validators: [],
      escalationConditions: [],
      clvScope: ['clv.core.issue.v1', 'clv.core.work_product.v1'],
      artifactsProduced: [],
    },
    {
      stateId: 'AuthorityVerification',
      required: true,
      predecessors: ['IssuePrune'],
      permittedAgents: [FAMILY_LAW_AGENTS.authorityVerification],
      inputSchema: 'AuthorityVerificationInput.v1',
      outputSchema: 'AuthorityVerificationOutput.v1',
      validators: [],
      escalationConditions: [],
      clvScope: ['clv.core.authority.v1', 'clv.core.machine_assessed_support.v1'],
      artifactsProduced: [],
    },
    {
      stateId: 'DirectLegalConclusionDraft',
      required: true,
      predecessors: ['AuthorityVerification'],
      permittedAgents: [FAMILY_LAW_AGENTS.directLegalConclusion],
      inputSchema: 'DirectLegalConclusionInput.v1',
      outputSchema: 'DirectLegalConclusionOutput.v1',
      validators: [],
      escalationConditions: [],
      clvScope: ['clv.core.conclusion.v1'],
      artifactsProduced: ['direct_legal_conclusion_draft'],
    },
    {
      stateId: 'ClientAdviceDraft',
      required: true,
      predecessors: ['DirectLegalConclusionDraft'],
      permittedAgents: [FAMILY_LAW_AGENTS.clientAdviceDraft],
      inputSchema: 'ClientAdviceDraftInput.v1',
      outputSchema: 'ClientAdviceDraftOutput.v1',
      validators: [],
      escalationConditions: [],
      clvScope: ['clv.core.client.v1', 'clv.core.privilege_attorney_client.v1'],
      artifactsProduced: ['client_advice_draft'],
    },
    {
      stateId: 'CourtFilingDraftGenerate',
      required: true,
      predecessors: ['ClientAdviceDraft'],
      permittedAgents: [FAMILY_LAW_AGENTS.courtFilingDraft],
      inputSchema: 'CourtFilingDraftInput.v1',
      outputSchema: 'CourtFilingDraftOutput.v1',
      validators: [],
      escalationConditions: [],
      clvScope: ['clv.core.filing.v1', 'clv.core.filing_package.v1'],
      artifactsProduced: ['court_filing_draft'],
    },
    {
      stateId: 'ReleaseStatusDetermine',
      required: true,
      predecessors: ['CourtFilingDraftGenerate'],
      permittedAgents: [FAMILY_LAW_AGENTS.releaseStatusDetermine],
      inputSchema: 'ReleaseStatusInput.v1',
      outputSchema: 'ReleaseStatusOutput.v1',
      validators: [],
      escalationConditions: [],
      clvScope: ['clv.core.release.v1', 'clv.core.gate.v1'],
      artifactsProduced: [],
    },
  ],
  requiredArtifacts: [
    { artifactType: 'direct_legal_conclusion_draft', schema: 'DirectLegalConclusionOutput.v1' },
    { artifactType: 'client_advice_draft', schema: 'ClientAdviceDraftOutput.v1' },
    { artifactType: 'court_filing_draft', schema: 'CourtFilingDraftOutput.v1' },
  ],
  validators: [],
  escalationTriggers: [],
  releasePolicies: [],
  clvBindings: [
    'clv.core.matter.v1',
    'clv.core.client.v1',
    'clv.core.fact.v1',
    'clv.core.source.v1',
    'clv.core.issue.v1',
    'clv.core.work_product.v1',
    'clv.core.authority.v1',
    'clv.core.machine_assessed_support.v1',
    'clv.core.conclusion.v1',
    'clv.core.privilege_attorney_client.v1',
    'clv.core.filing.v1',
    'clv.core.filing_package.v1',
    'clv.core.release.v1',
    'clv.core.gate.v1',
  ],
  dependencies: [],
};
