import type { LensPhaseManifest } from '../../lib/orchestrator/types.js';
import { SHARED_AGENTS } from '../sharedAgents.js';

export const COURT_FILING_DRAFT_LENS_ID = 'court_filing_draft_lens';

export const courtFilingDraftManifest: LensPhaseManifest = {
  lensId: COURT_FILING_DRAFT_LENS_ID,
  lensVersion: 'v1',
  practiceArea: 'court_filing',
  applicableJurisdictions: ['MD', 'VA', 'PA', 'DC', 'US'],
  states: [
    {
      stateId: 'FilingTypeSelect',
      required: true,
      predecessors: [],
      permittedAgents: [SHARED_AGENTS.intakeNormalize],
      inputSchema: 'FilingTypeInput.v1',
      outputSchema: 'FilingTypeOutput.v1',
      validators: [],
      escalationConditions: [],
      clvScope: ['clv.core.filing.v1'],
      artifactsProduced: [],
    },
    {
      stateId: 'JurisdictionCapture',
      required: true,
      predecessors: ['FilingTypeSelect'],
      permittedAgents: [SHARED_AGENTS.jurisdictionCapture],
      inputSchema: 'JurisdictionCaptureInput.v1',
      outputSchema: 'JurisdictionCaptureOutput.v1',
      validators: [],
      escalationConditions: [],
      clvScope: ['clv.core.matter.v1'],
      artifactsProduced: [],
    },
    {
      stateId: 'AuthorityRetrieve',
      required: true,
      predecessors: ['JurisdictionCapture'],
      permittedAgents: [SHARED_AGENTS.authorityRetrieve],
      inputSchema: 'AuthorityRetrieveInput.v1',
      outputSchema: 'AuthorityRetrieveOutput.v1',
      validators: [],
      escalationConditions: [],
      clvScope: ['clv.core.authority.v1'],
      artifactsProduced: [],
    },
    {
      stateId: 'FilingDraftGenerate',
      required: true,
      predecessors: ['AuthorityRetrieve'],
      permittedAgents: [SHARED_AGENTS.courtFilingDraft],
      inputSchema: 'FilingDraftInput.v1',
      outputSchema: 'FilingDraftOutput.v1',
      validators: [],
      escalationConditions: [],
      clvScope: ['clv.core.filing.v1', 'clv.core.filing_package.v1'],
      artifactsProduced: ['court_filing_draft'],
    },
    {
      stateId: 'AuthorityVerification',
      required: true,
      predecessors: ['FilingDraftGenerate'],
      permittedAgents: [SHARED_AGENTS.authorityVerification],
      inputSchema: 'AuthorityVerificationInput.v1',
      outputSchema: 'AuthorityVerificationOutput.v1',
      validators: [],
      escalationConditions: [],
      clvScope: ['clv.core.authority.v1', 'clv.core.machine_assessed_support.v1'],
      artifactsProduced: [],
    },
    {
      stateId: 'ReleaseStatusDetermine',
      required: true,
      predecessors: ['AuthorityVerification'],
      permittedAgents: [SHARED_AGENTS.releaseStatusDetermine],
      inputSchema: 'ReleaseStatusInput.v1',
      outputSchema: 'ReleaseStatusOutput.v1',
      validators: [],
      escalationConditions: [],
      clvScope: ['clv.core.release.v1', 'clv.core.gate.v1'],
      artifactsProduced: [],
    },
  ],
  requiredArtifacts: [{ artifactType: 'court_filing_draft', schema: 'FilingDraftOutput.v1' }],
  validators: [],
  escalationTriggers: [],
  releasePolicies: [],
  clvBindings: [
    'clv.core.matter.v1',
    'clv.core.filing.v1',
    'clv.core.filing_package.v1',
    'clv.core.authority.v1',
    'clv.core.machine_assessed_support.v1',
    'clv.core.release.v1',
    'clv.core.gate.v1',
  ],
  dependencies: [],
};
