import { spawnSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

// ── THE RULE THIS FILE ENFORCES, AND WHY IT HAD NO INSTRUMENT FOR A MONTH ────────────────────────────
// `JPWB-REG-005`'s own front matter (`:19`) reads: "Append-only after ratification … **Entries are never
// destructively edited; a correction is a superseding entry citing the entry it supersedes.**"
//
// Nothing checked it. Between 103 and 163 removed lines (the range is derivation-dependent — see
// DESIGN-register-append-only.md §3) are absent from the register at HEAD, and 26 in-place rewrites of live
// entry text were confirmed by adjudication, starting NINE DAYS after REG-D-010 ratified the register.
// They cluster on `Status:` and `Merge target:` — the two most load-bearing fields an open entry has.
//
// ⚠ THE OBVIOUS INSTRUMENT IS THE WRONG ONE, AND THE FIRST MEASUREMENT THIS SESSION USED IT. Counting git
// deletions reports the SANCTIONED idiom as a violation: retiring text by striking it (`~~old~~` plus an
// appended replacement, as at `:57`) rewrites the line, so git scores it `-1/+1` while NOTHING IS LOST.
// A history assertion over git deletions flags 6 of 9 adjudicated compliant strikes; an n-gram shingle
// contract flags 12 of 12, because re-wrapping destroys every n-gram. Both were built and driven before
// this design was chosen — see the design paper's table.
//
// So the question is CONTENT SURVIVAL, not line churn, and this gate asks it at two levels.

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = join(HERE, '..');
const REGISTER = 'docs/canon/JPWB-REG-005 Decision and Divergence Register.md';

// ⚠ THE BASELINE IS A COMMIT, NOT A CHECKED-IN FILE. A `.baseline.json` of per-entry word counts would be
// megabytes and would have to be regenerated by hand — a maintenance burden that eventually gets satisfied
// by regenerating rather than by reading. `git show` cannot drift from what was actually committed.
//
// ⚠ AND BECAUSE THE PIN IS AT THE CURRENT STATE, THE 26 HISTORICAL VIOLATIONS NEED NO GRANDFATHER LIST.
// The baseline already reflects the post-deletion text, so this gate guards FORWARD only. That is the one
// respect in which it is simpler than `register-status.test.ts`, which had to grandfather 63 entries BY ID
// (`:74`) because its subject was the state of the entries themselves rather than their history.
// Advancing this pin is a deliberate act: it should move only when a deletion has been RATIFIED.
const BASELINE_COMMIT = '95d0b3ae';

function registerAtBaseline(): string {
	// ⚠ THE `./` IS LOAD-BEARING. `git show <rev>:<path>` resolves the path from the REPOSITORY ROOT unless
	// it is written as explicitly relative, and this package is a subdirectory of the git root. Without it
	// git reports "exists, but not <path>" and this gate fails closed on every run — which is how it was
	// caught, on its first drive.
	const result = spawnSync('git', ['show', `${BASELINE_COMMIT}:./${REGISTER}`], {
		cwd: ROOT,
		encoding: 'utf8',
		maxBuffer: 64 * 1024 * 1024
	});
	// FAIL CLOSED. A gate that silently passes when it cannot establish its baseline is worse than no gate:
	// it reports green while measuring nothing. `mutation-tree-baseline.test.ts:78` takes the same position.
	if (result.status !== 0)
		throw new Error(
			`cannot read the register at ${BASELINE_COMMIT}: ${result.stderr || result.stdout}`
		);
	return result.stdout;
}

/** Strip strike markers so a struck heading still keys to its id and struck text still counts as present. */
const unstrike = (s: string): string => s.replace(/~~/g, '');

/**
 * Split into entries keyed by REG id.
 *
 * ⚠ TOLERATE A STRUCK HEADING. Three headings have been struck (`### ~~REG-F-105~~`, `-106`, `-108`), and
 * an id-extractor that missed them would report those three entries as DELETED on every run — a gate that
 * is red for a reason unrelated to its subject gets disabled, which is how instruments die here.
 */
function entriesById(text: string): Map<string, string> {
	const out = new Map<string, string>();
	const blocks = text.split(/^### /m);
	for (const block of blocks.slice(1)) {
		const id = /^~{0,2}(REG-[A-Z]-\d{3})~{0,2}/.exec(block)?.[1];
		if (!id) continue;
		// A later entry with the same id would silently overwrite an earlier one; concatenate instead so
		// the count only ever grows, which keeps the comparison conservative.
		out.set(id, (out.get(id) ?? '') + '\n' + block);
	}
	return out;
}

function wordCounts(text: string): Map<string, number> {
	const counts = new Map<string, number>();
	for (const m of unstrike(text).matchAll(/[A-Za-z0-9_./:%-]{2,}/g)) {
		const w = m[0];
		counts.set(w, (counts.get(w) ?? 0) + 1);
	}
	return counts;
}

/**
 * The entries whose text lost words that did not reappear anywhere else in the file.
 *
 * ⚠ THE FILE-LEVEL LEG IS WHAT MAKES THIS USABLE. Without it, moving a bullet from one entry to another —
 * or reflowing a paragraph across different line breaks — would redden the gate, and a gate that reddens on
 * every legitimate edit is one that gets deleted. The entry level catches the deletion; the file level
 * ABSOLVES a word that merely relocated. A word must fall at BOTH levels to count as lost.
 */
function lostByEntry(baseline: string, current: string): Map<string, string[]> {
	const baseEntries = entriesById(baseline);
	const curEntries = entriesById(current);

	// ⚠ "ELSEWHERE" MEANS THE ENTRIES THAT ALREADY EXISTED, NOT THE WHOLE FILE — AND THAT DISTINCTION WAS
	// FOUND BY THIS GATE FAILING ON ITS OWN AUTHOR'S APPEND.
	//
	// The first version counted words over the ENTIRE current file. That absolves relocation, which is the
	// point — but it cannot tell "this word moved to another entry" from "this word was independently
	// written somewhere else later". Appending REG-F-274..276 (185 lines) raised the global counts of
	// `the`, `at`, `was`, `register`, `audit`, `corrected`, `COMPLETE` and `record`, and MUTANT A's
	// detection collapsed from NINE words to ONE (`design`, 153 -> 152 file-wide). **The gate was eroding
	// toward a false negative with every append, which for an append-only artifact means eroding always.**
	//
	// Restricting the elsewhere-count to entries PRESENT IN THE BASELINE fixes it: a brand-new entry cannot
	// absolve a deletion from an old one, while a genuine cross-entry MOVE still can. Re-measured: MUTANT A
	// back to all nine words, MUTANT B still green, identity still green.
	const baseElsewhere = new Map<string, number>();
	for (const text of baseEntries.values())
		for (const [w, n] of wordCounts(text)) baseElsewhere.set(w, (baseElsewhere.get(w) ?? 0) + n);
	const curElsewhere = new Map<string, number>();
	for (const [id, text] of curEntries) {
		if (!baseEntries.has(id)) continue;
		for (const [w, n] of wordCounts(text)) curElsewhere.set(w, (curElsewhere.get(w) ?? 0) + n);
	}

	const lost = new Map<string, string[]>();
	for (const [id, baseText] of baseEntries) {
		const curText = curEntries.get(id);
		if (curText === undefined) {
			lost.set(id, ['<THE ENTIRE ENTRY IS ABSENT>']);
			continue;
		}
		const baseWords = wordCounts(baseText);
		const curWords = wordCounts(curText);
		const gone: string[] = [];
		for (const [w, n] of baseWords) {
			const here = curWords.get(w) ?? 0;
			if (here >= n) continue;
			// Did it turn up in a DIFFERENT pre-existing entry? Then it moved rather than died.
			const wasElsewhere = (baseElsewhere.get(w) ?? 0) - n;
			const isElsewhere = (curElsewhere.get(w) ?? 0) - here;
			if (isElsewhere > wasElsewhere) continue;
			gone.push(w);
		}
		if (gone.length > 0) lost.set(id, gone.sort());
	}
	return lost;
}

describe('JPWB-REG-005 is append-only', () => {
	const baseline = registerAtBaseline();
	const current = readFileSync(join(ROOT, REGISTER), 'utf8');

	// The instrument's own control. If the baseline were empty, every assertion below would pass vacuously
	// — the "control that cannot fail" shape this repository has recorded three times.
	it('the baseline is established and is the register', () => {
		expect(baseline.length, 'a truncated or empty baseline would pass every check below').toBeGreaterThan(
			1_000_000
		);
		expect(baseline).toContain('Entries are never destructively edited');
		expect(entriesById(baseline).size, 'entries parsed out of the baseline').toBeGreaterThan(250);
	});

	it('no entry has lost text since the baseline commit', () => {
		const lost = lostByEntry(baseline, current);
		const report = [...lost.entries()].map(
			([id, words]) => `${id}: lost ${JSON.stringify(words.slice(0, 12))}`
		);
		expect(
			report,
			'an entry may be APPENDED to freely and its text may be STRUCK, but text may not be removed. ' +
				'A correction is a superseding entry citing the entry it supersedes (REG-005 front matter, :19).'
		).toEqual([]);
	});

	// ── ⚠ THE TWO MUTANTS, AND WHY ONE OF THEM MUST STAY GREEN ────────────────────────────────────────────
	// A control needs its OWN predicted red. It also needs a predicted GREEN when the sanctioned act is
	// performed — otherwise "it reddened" proves only that the gate reacts to edits, not that it tells the
	// forbidden act from the permitted one. This repository has shipped three controls that could not fail;
	// the distinguishing pair below is the reason this one is not a fourth.
	const targetEntry = 'REG-F-049';
	const liveLine =
		'- **Merge target:** This register — **audit COMPLETE**; the design record was corrected at';

	it('MUTANT A — an in-place rewrite of a live line is REFUSED', () => {
		expect(current, 'the mutant must anchor on real text').toContain(liveLine);
		// The exact shape `c61d92cf` performed: the line overwritten, no strike, no superseding entry.
		const mutated = current.replace(
			liveLine,
			'- **Merge target:** This register. **Status:** **CLOSED**.'
		);
		expect(mutated, 'the mutation must actually change the file').not.toBe(current);
		const lost = lostByEntry(baseline, mutated);
		expect(lost.has(targetEntry), `${targetEntry} must be reported as having lost text`).toBe(true);
		expect(lost.get(targetEntry)?.length ?? 0).toBeGreaterThan(3);
	});

	it('MUTANT B — retiring the same line BY STRIKING it is PERMITTED', () => {
		// `~~old~~` plus an appended replacement. Git scores this as a deletion too; the gate must not.
		const mutated = current.replace(
			liveLine,
			`- ~~${liveLine.slice(2)}~~\n- **Status:** **CLOSED 2026-08-27** — retired by strike.`
		);
		expect(mutated, 'the mutation must actually change the file').not.toBe(current);
		const lost = lostByEntry(baseline, mutated);
		expect(
			lost.get(targetEntry) ?? [],
			'striking preserves the text; a gate that reddens here cannot tell the sanctioned act from the ' +
				'forbidden one, and would be satisfied by deleting the gate'
		).toEqual([]);
	});
});
