import type { LensPhaseManifest } from '../../lib/orchestrator/types.js';
import { SHARED_AGENTS } from '../sharedAgents.js';

export const DIRECT_LEGAL_CONCLUSION_LENS_ID = 'direct_legal_conclusion_lens';

export const directLegalConclusionManifest: LensPhaseManifest = {
  lensId: DIRECT_LEGAL_CONCLUSION_LENS_ID,
  lensVersion: 'v1',
  practiceArea: 'legal_conclusion',
  applicableJurisdictions: ['MD', 'VA', 'PA', 'DC'],
  states: [
    {
      stateId: 'LegalQuestionNormalize',
      required: true,
      predecessors: [],
      permittedAgents: [SHARED_AGENTS.intakeNormalize],
      inputSchema: 'LegalQuestionInput.v1',
      outputSchema: 'LegalQuestionNormalized.v1',
      validators: [],
      escalationConditions: [],
      clvScope: ['clv.core.issue.v1', 'clv.core.matter.v1'],
      artifactsProduced: [],
    },
    {
      stateId: 'JurisdictionCapture',
      required: true,
      predecessors: ['LegalQuestionNormalize'],
      permittedAgents: [SHARED_AGENTS.jurisdictionCapture],
      inputSchema: 'JurisdictionCaptureInput.v1',
      outputSchema: 'JurisdictionCaptureOutput.v1',
      validators: [],
      escalationConditions: [],
      clvScope: ['clv.core.matter.v1'],
      artifactsProduced: [],
    },
    {
      stateId: 'AuthorityRetrieve',
      required: true,
      predecessors: ['JurisdictionCapture'],
      permittedAgents: [SHARED_AGENTS.authorityRetrieve],
      inputSchema: 'AuthorityRetrieveInput.v1',
      outputSchema: 'AuthorityRetrieveOutput.v1',
      validators: [],
      escalationConditions: [],
      clvScope: ['clv.core.authority.v1'],
      artifactsProduced: [],
    },
    {
      stateId: 'RuleElementMap',
      required: true,
      predecessors: ['AuthorityRetrieve'],
      permittedAgents: [SHARED_AGENTS.ruleElementMap],
      inputSchema: 'RuleElementInput.v1',
      outputSchema: 'RuleElementOutput.v1',
      validators: [],
      escalationConditions: [],
      clvScope: ['clv.core.rule.v1', 'clv.core.element.v1'],
      artifactsProduced: [],
    },
    {
      stateId: 'ConclusionDraft',
      required: true,
      predecessors: ['RuleElementMap'],
      permittedAgents: [SHARED_AGENTS.conclusionDraft],
      inputSchema: 'LegalConclusionInput.v1',
      outputSchema: 'LegalConclusionOutput.v1',
      validators: [],
      escalationConditions: [],
      clvScope: ['clv.core.conclusion.v1'],
      artifactsProduced: ['legal_conclusion_draft'],
    },
    {
      stateId: 'ReleaseStatusDetermine',
      required: true,
      predecessors: ['ConclusionDraft'],
      permittedAgents: [SHARED_AGENTS.releaseStatusDetermine],
      inputSchema: 'ReleaseStatusInput.v1',
      outputSchema: 'ReleaseStatusOutput.v1',
      validators: [],
      escalationConditions: [],
      clvScope: ['clv.core.release.v1', 'clv.core.gate.v1'],
      artifactsProduced: [],
    },
  ],
  requiredArtifacts: [{ artifactType: 'legal_conclusion_draft', schema: 'LegalConclusionOutput.v1' }],
  validators: [],
  escalationTriggers: [],
  releasePolicies: [],
  clvBindings: [
    'clv.core.matter.v1',
    'clv.core.issue.v1',
    'clv.core.authority.v1',
    'clv.core.rule.v1',
    'clv.core.element.v1',
    'clv.core.conclusion.v1',
    'clv.core.release.v1',
    'clv.core.gate.v1',
  ],
  dependencies: [],
};
