/**
 * Executor Role (Agent)
 * Implements Phase 6.2: Proposal generation, assumption surfacing, and artifact generation
 * This is an LLM-backed agent that executes tasks within verified constraints
 */

import type {
	Result,
	Role,
	Claim,
	ClaimCriticality,
} from '../types';
import type { TaskUnit } from '../types/maker';
import { ClaimStatus, Phase, Role as RoleEnum } from '../types';
import { assembleContext } from '../context';
import { getDatabase } from '../database/init';
import type { RoleCLIProvider } from '../cli/roleCLIProvider';
import { buildStdinContent } from '../cli/types';
import type { CLIActivityEvent } from '../cli/types';
import { invokeRoleStreaming } from '../cli/roleInvoker';
import { randomUUID } from 'node:crypto';
import { getLogger, isLoggerInitialized } from '../logging';
import { emitWorkflowCommand, emitCLIActivity, getEventBus } from '../integration/eventBus';
import { updateWorkflowMetadata } from '../workflow/stateMachine';
import { analyzeGoalForMobile } from '../mcp/goalDetector';
import {
	buildMobileSpecialistMCPConfig,
	buildPermissionMCPConfig,
	createMCPConfigFile,
	cleanupMCPConfigFile,
} from '../mcp/mcpConfigManager';
import {
	isMobileSpecialistEnabled,
	getMobileSpecialistConfig,
} from '../config/manager';
import { PermissionBridge, setActivePermissionBridge } from '../mcp/permissionBridge';
import type { PermissionDecision } from '../mcp/permissionBridge';
import * as path from 'node:path';

/**
 * Executor invocation options
 */
export interface ExecutorInvocationOptions {
	dialogueId: string;
	goal: string;
	tokenBudget: number;
	provider: RoleCLIProvider;
	temperature?: number;
	includeHistoricalFindings?: boolean;
	commandId?: string;
	onEvent?: (event: CLIActivityEvent) => void;
}

/**
 * Assumption surfaced by Executor
 */
export interface Assumption {
	assumption_id: string;
	statement: string;
	criticality: ClaimCriticality;
	rationale: string;
	assumption_type?: string;
}

/**
 * Artifact generated by Executor
 */
export interface Artifact {
	artifact_id: string;
	type: 'CODE' | 'DESIGN' | 'DOCUMENTATION' | 'SPECIFICATION';
	content: string;
	description: string;
}

/**
 * Executor response
 */
export interface ExecutorResponse {
	proposal: string;
	assumptions: Assumption[];
	artifacts: Artifact[];
	constraint_adherence_notes: string[];
	raw_response: string;
}

/**
 * System prompt template for Executor
 */
const EXECUTOR_SYSTEM_PROMPT = `You are the EXECUTOR role in the JanumiCode autonomous system.

# Your Responsibilities

1. **Propose Solutions**: Generate concrete, actionable proposals with specific implementation steps
2. **Surface Assumptions**: Identify and articulate all assumptions in your proposal as claims
3. **Generate Artifacts**: Create code, designs, documentation, or specifications as needed
4. **Adhere to Constraints**: Strictly follow all constraints in the constraint manifest
5. **Defer to Verification**: Accept verifier verdicts without challenge

# Critical Guardrails

## NEVER Override Verification
- You MUST NOT challenge or reinterpret verifier verdicts
- If a claim is DISPROVED or UNKNOWN, you MUST NOT proceed with dependent actions
- If blocked by verification, surface this as a gate condition

## NEVER Invent Constraints
- You MUST ONLY reference constraints from the provided constraint manifest
- You MUST NOT introduce new constraints or interpret constraints creatively
- If a constraint is unclear, surface this as an assumption requiring verification

## ALWAYS Surface Assumptions
- Every assumption in your proposal MUST be surfaced as an explicit claim
- Mark assumptions with appropriate criticality (CRITICAL or NON_CRITICAL)
- Classify each assumption by type:
  - "architectural" — Design or technology choices (e.g., "Use Better Auth for sessions")
  - "compatibility" — Runtime or library compatibility (e.g., "DBOS works with Bun")
  - "structural" — Workspace or file structure (e.g., "specs directory contains 3 files")
  - "scoping" — Deferral or phasing decisions (e.g., "Defer email integration")
  - "intent" — Interpretation of user intent (e.g., "This is a greenfield build")
- Provide clear rationale for why each assumption matters

# Response Format

Your response MUST be valid JSON with this exact structure:

\`\`\`json
{
  "proposal": "A concrete, step-by-step implementation plan. Include specific file paths, function signatures, data structures, architectural decisions, and code patterns. Do NOT write a high-level summary or phase overview — write the actual technical blueprint that a developer could follow to implement the solution.",
  "assumptions": [
    {
      "statement": "Assumption statement",
      "criticality": "CRITICAL" | "NON_CRITICAL",
      "assumption_type": "architectural" | "compatibility" | "structural" | "scoping" | "intent",
      "rationale": "Why this assumption matters"
    }
  ],
  "artifacts": [
    {
      "type": "CODE" | "DESIGN" | "DOCUMENTATION" | "SPECIFICATION",
      "content": "Artifact content...",
      "description": "What this artifact does"
    }
  ],
  "constraint_adherence_notes": [
    "How this proposal adheres to constraint X",
    "Why constraint Y is satisfied by approach Z"
  ]
}
\`\`\`

IMPORTANT: The "proposal" field is the PRIMARY deliverable. It must contain the full, concrete technical plan — not a summary, not a description of phases, not meta-commentary about what you will do. Write the actual implementation steps with specifics.

## NEVER Use Temporal References
- This plan will be executed by AI agents, not humans. Do NOT express milestones, roadmaps, or sequencing in temporal terms (e.g., "Week 1", "Day 3", "Sprint 2", "Phase 1 (2 weeks)")
- Instead, express implementation sequences as logical execution steps ordered by dependency and optimal build order
- Use labels like "Step 1", "Stage A", or descriptive names (e.g., "Foundation", "Core API", "Integration Layer") — never time-based labels
- Do NOT estimate durations, timelines, or delivery dates

## Implementation Completeness
- Implement features as specified in the requirements and constraints. Do NOT defer specified features to "later milestones" or "future phases."
- The ONLY acceptable deferrals are for external integrations (email providers, SMS gateways, third-party APIs) that lack detailed specifications in the provided documentation. When deferring, surface this as an explicit assumption explaining what specification is missing.
- For all features with clear specifications, implement them fully. If implementation is complex, decompose into smaller steps but still implement each step completely.
- Do NOT stub, mock, or placeholder features that have detailed specifications — implement them.
- Surface complexity concerns as assumptions rather than silently deferring.

# Context

You will receive:
- **Goal**: The objective you need to achieve
- **Constraint Manifest**: Constraints you MUST follow
- **Active Claims**: Current claims and their verification status
- **Verifier Verdicts**: Verification results you MUST respect
- **Human Decisions**: Human authority decisions that override all else
- **Historical Findings**: Relevant past decisions and precedents

Process this context carefully and generate your response in the required JSON format.`;

/**
 * System prompt supplement appended when mobile-specialist MCP tools are injected.
 */
const MOBILE_SPECIALIST_PROMPT_SUPPLEMENT = `

# Mobile Development Specialist Tools Available

You have access to a mobile development specialist LLM via the \`query_mobile_specialist\` tool.
Use it when you need:
- iOS/Android platform-specific code generation
- Mobile architecture diagnosis or debugging
- ARKit, SwiftUI, Jetpack Compose, or other framework-specific guidance
- Platform constraint validation

You also have access to:
- \`get_mobile_guidelines\` — curated iOS/Android best practices and code patterns
- \`analyze_mobile_project\` — detect mobile project type from workspace structure

ALWAYS use the specialist tool for mobile-specific code rather than generating it from general knowledge alone.`;

/**
 * Invoke Executor agent
 * Generates proposals, surfaces assumptions, and creates artifacts
 *
 * @param options Invocation options
 * @returns Result containing Executor response
 */
export async function invokeExecutor(
	options: ExecutorInvocationOptions
): Promise<Result<ExecutorResponse>> {
	try {
		// Check for blocking conditions (direct DB query — safety check independent of LLM)
		const blockingCheck = checkBlockingConditions(options.dialogueId);
		if (!blockingCheck.canProceed) {
			return {
				success: false,
				error: new Error(
					`Executor blocked: ${blockingCheck.reason}\nBlocking claims: ${blockingCheck.blockingClaims.join(', ')}`
				),
			};
		}

		// Pre-read workspace structure for context
		const { getWorkspaceStructureSummary } = await import('../context/workspaceReader.js');
		const workspaceSpecs = await getWorkspaceStructureSummary();

		// Assemble context via Context Engineer
		const contextResult = await assembleContext({
			dialogueId: options.dialogueId,
			role: RoleEnum.EXECUTOR,
			phase: Phase.EXECUTE,
			tokenBudget: options.tokenBudget,
			extras: { goal: options.goal, workspace_specs: workspaceSpecs },
			onEvent: options.onEvent,
		});

		if (!contextResult.success) {
			return contextResult;
		}

		const formattedContext = contextResult.value.briefing;

		// ── Mobile specialist MCP injection ──
		// Detect whether the goal involves mobile development and inject MCP tools
		const goalAnalysis = analyzeGoalForMobile(options.goal);
		const useMobileSpecialist = goalAnalysis.isMobileRelated && isMobileSpecialistEnabled();
		let mcpConfigPath: string | undefined;

		let systemPrompt = EXECUTOR_SYSTEM_PROMPT;
		if (useMobileSpecialist) {
			systemPrompt += MOBILE_SPECIALIST_PROMPT_SUPPLEMENT;

			const specialistConfig = getMobileSpecialistConfig();
			if (specialistConfig.baseUrl && specialistConfig.serverPath) {
				const mcpConfig = buildMobileSpecialistMCPConfig(
					specialistConfig.serverPath,
					specialistConfig.baseUrl,
					specialistConfig.apiKey,
					specialistConfig.model,
				);
				mcpConfigPath = createMCPConfigFile(mcpConfig);
			}
		}

		// Build stdin content: system prompt + formatted context
		const stdinContent = buildStdinContent(systemPrompt, formattedContext);

		// Emit full stdin content for observability (expandable in command block UI)
		if (options.commandId) {
			emitWorkflowCommand({
				dialogueId: options.dialogueId,
				commandId: options.commandId,
				action: 'output',
				commandType: 'role_invocation',
				label: 'Executor',
				summary: '── stdin ──',
				detail: stdinContent,
				lineType: 'stdin',
				timestamp: new Date().toISOString(),
			});
		}

		let cliResult: Result<import('../cli/types').RoleCLIResult>;
		try {
			cliResult = await invokeRoleStreaming({
				provider: options.provider,
				stdinContent,
				onEvent: options.onEvent,
				mcpConfigPaths: mcpConfigPath ? [mcpConfigPath] : undefined,
			});
		} finally {
			// Clean up temp MCP config file regardless of outcome
			if (mcpConfigPath) {
				cleanupMCPConfigFile(mcpConfigPath);
			}
		}

		if (!cliResult.success) {
			return cliResult;
		}

		const rawResponse = cliResult.value.response;

		// Cache raw output in metadata BEFORE parsing — enables retry on parse failure
		updateWorkflowMetadata(options.dialogueId, {
			cachedRawCliOutput: rawResponse,
		});

		// Parse response
		const parseResult = parseExecutorResponse(rawResponse);

		if (!parseResult.success) {
			// Emit raw response to command block for observability
			if (options.commandId) {
				emitWorkflowCommand({
					dialogueId: options.dialogueId,
					commandId: options.commandId,
					action: 'output',
					commandType: 'role_invocation',
					label: 'Executor',
					summary: `── Raw Response (parse failed) ──`,
					detail: rawResponse,
					timestamp: new Date().toISOString(),
				});
			}
			return parseResult;
		}

		// Validate response
		const validationResult = validateExecutorResponse(
			parseResult.value,
			options.dialogueId
		);

		if (!validationResult.success) {
			return validationResult;
		}

		// Add IDs to assumptions and artifacts
		const response = parseResult.value;
		response.assumptions = response.assumptions.map((a) => ({
			...a,
			assumption_id: randomUUID(),
		}));
		response.artifacts = response.artifacts.map((a) => ({
			...a,
			artifact_id: randomUUID(),
		}));

		return { success: true, value: response };
	} catch (error) {
		return {
			success: false,
			error:
				error instanceof Error
					? error
					: new Error('Failed to invoke Executor'),
		};
	}
}

/**
 * Re-parse a cached raw executor response.
 * Used on retry to avoid re-invoking the CLI when the raw output is already cached.
 * Skips full context-aware validation (context is not available on retry).
 */
export function reparseExecutorResponse(
	rawResponse: string,
): Result<ExecutorResponse> {
	const parseResult = parseExecutorResponse(rawResponse);
	if (!parseResult.success) {
		return parseResult;
	}

	const response = parseResult.value;
	response.assumptions = response.assumptions.map((a) => ({
		...a,
		assumption_id: a.assumption_id || randomUUID(),
	}));
	response.artifacts = response.artifacts.map((a) => ({
		...a,
		artifact_id: a.artifact_id || randomUUID(),
	}));

	return { success: true, value: response };
}

/**
 * Check for blocking conditions via direct DB query.
 * Executor MUST NOT proceed if critical claims are DISPROVED or UNKNOWN.
 */
function checkBlockingConditions(dialogueId: string): {
	canProceed: boolean;
	reason?: string;
	blockingClaims: string[];
} {
	try {
		const db = getDatabase();
		if (!db) { return { canProceed: true, blockingClaims: [] }; }

		const rows = db.prepare(`
			SELECT claim_id FROM claims
			WHERE dialogue_id = ? AND criticality = 'CRITICAL' AND status IN ('DISPROVED', 'UNKNOWN')
		`).all(dialogueId) as Array<{ claim_id: string }>;

		if (rows.length > 0) {
			return {
				canProceed: false,
				reason: `Found ${rows.length} blocking critical claims (DISPROVED or UNKNOWN)`,
				blockingClaims: rows.map(r => r.claim_id),
			};
		}
	} catch { /* DB not available — allow execution */ }

	return { canProceed: true, blockingClaims: [] };
}

/**
 * Parse Executor response from LLM
 */
function parseExecutorResponse(
	rawResponse: string
): Result<ExecutorResponse> {
	const logger = isLoggerInitialized()
		? getLogger().child({ component: 'role:executor', fn: 'parseExecutorResponse' })
		: undefined;

	logger?.debug('Attempting to parse Executor response', {
		rawResponseLength: rawResponse.length,
		rawResponsePreview: rawResponse.substring(0, 500),
	});

	try {
		// Extract JSON from response — multiple strategies for robustness
		const jsonStr = extractJsonFromResponse(rawResponse);

		logger?.debug('Extracted JSON string, attempting JSON.parse', {
			jsonStrLength: jsonStr.length,
			jsonStrTail: jsonStr.substring(Math.max(0, jsonStr.length - 300)),
		});

		const parsed = JSON.parse(jsonStr);

		// Validate structure
		if (!parsed.proposal || typeof parsed.proposal !== 'string') {
			return {
				success: false,
				error: new Error('Executor response missing or invalid proposal'),
			};
		}

		if (!Array.isArray(parsed.assumptions)) {
			return {
				success: false,
				error: new Error('Executor response missing or invalid assumptions'),
			};
		}

		if (!Array.isArray(parsed.artifacts)) {
			return {
				success: false,
				error: new Error('Executor response missing or invalid artifacts'),
			};
		}

		if (!Array.isArray(parsed.constraint_adherence_notes)) {
			return {
				success: false,
				error: new Error(
					'Executor response missing or invalid constraint_adherence_notes'
				),
			};
		}

		const response: ExecutorResponse = {
			proposal: parsed.proposal,
			assumptions: parsed.assumptions,
			artifacts: parsed.artifacts,
			constraint_adherence_notes: parsed.constraint_adherence_notes,
			raw_response: rawResponse,
		};

		return { success: true, value: response };
	} catch (error) {
		const errMsg = error instanceof Error ? error.message : 'Failed to parse Executor response';
		logger?.error('Failed to parse Executor response JSON', {
			errorMessage: errMsg,
			rawResponseLength: rawResponse.length,
			rawResponse,
		});
		return {
			success: false,
			error:
				error instanceof Error
					? error
					: new Error('Failed to parse Executor response'),
		};
	}
}

/**
 * Extract a JSON object string from a raw LLM response.
 * Handles markdown code fences, surrounding prose, and braces in trailing text.
 *
 * Strategy order:
 *   1. Direct JSON.parse of trimmed input (already clean JSON)
 *   2. Markdown code fence extraction (```json ... ```)
 *   3. Brace-balanced extraction (first { to its matching }, respecting strings)
 *   4. Fallback: return trimmed input as-is and let the caller's JSON.parse report the error
 */
function extractJsonFromResponse(rawResponse: string): string {
	const trimmed = rawResponse.trim();

	return tryDirectParse(trimmed)
		?? tryFenceExtraction(trimmed)
		?? extractBalancedJsonObject(trimmed)
		?? trimmed;
}

/** Return the text if it's already valid JSON, otherwise null. */
function tryDirectParse(text: string): string | null {
	try { JSON.parse(text); return text; } catch { return null; }
}

/** Extract JSON from a markdown code fence, with balanced-brace fallback. */
function tryFenceExtraction(text: string): string | null {
	const m = /```(?:json)?\s*([\s\S]*)\s*```/.exec(text);
	if (!m) { return null; }

	const content = m[1].trim();
	return tryDirectParse(content) ?? extractBalancedJsonObject(content);
}

/**
 * Extract the first balanced JSON object from a string.
 * Finds the first '{' and walks forward, tracking brace depth while
 * respecting JSON string boundaries (so braces inside strings don't count).
 * Returns the substring from the opening '{' to its matching '}', or null.
 */
function extractBalancedJsonObject(text: string): string | null {
	const start = text.indexOf('{');
	if (start === -1) { return null; }

	const end = findMatchingBrace(text, start);
	return end === -1 ? null : text.substring(start, end + 1);
}

/** Walk from the '{' at `start` and return the index of its matching '}', or -1. */
function findMatchingBrace(text: string, start: number): number {
	let depth = 0;
	let inString = false;
	let skip = false;

	for (let i = start; i < text.length; i++) {
		const ch = text[i];

		// Previous char was a backslash inside a string — skip this char
		if (skip) { skip = false; continue; }

		if (inString) {
			skip = ch === '\\';
			if (ch === '"') { inString = false; }
			continue;
		}
		if (ch === '"') { inString = true; continue; }
		if (ch === '{') { depth++; }
		if (ch === '}' && --depth === 0) { return i; }
	}

	return -1;
}

/**
 * Validate Executor response
 * Ensure guardrails are not violated
 */
function validateExecutorResponse(
	response: ExecutorResponse,
	dialogueId: string,
): Result<void> {
	const errors: string[] = [];

	// Check that proposal doesn't challenge verifier verdicts (via DB query)
	try {
		const db = getDatabase();
		if (db) {
			const disproved = db.prepare(`
				SELECT claim_id, statement FROM claims
				WHERE dialogue_id = ? AND status = 'DISPROVED'
			`).all(dialogueId) as Array<{ claim_id: string; statement: string }>;

			for (const claim of disproved) {
				if (response.proposal.toLowerCase().includes(claim.statement.toLowerCase())) {
					errors.push(
						`Proposal may be attempting to work around DISPROVED claim: ${claim.claim_id}`
					);
				}
			}
		}
	} catch { /* DB not available — skip validation */ }

	// Validate assumption structure
	for (const assumption of response.assumptions) {
		if (!assumption.statement || !assumption.criticality || !assumption.rationale) {
			errors.push(
				`Invalid assumption structure: ${JSON.stringify(assumption)}`
			);
		}

		if (
			assumption.criticality !== 'CRITICAL' &&
			assumption.criticality !== 'NON_CRITICAL'
		) {
			errors.push(
				`Invalid criticality for assumption: ${assumption.criticality}`
			);
		}
	}

	// Validate artifact structure
	for (const artifact of response.artifacts) {
		if (!artifact.type || !artifact.content || !artifact.description) {
			errors.push(`Invalid artifact structure: ${JSON.stringify(artifact)}`);
		}

		const validTypes = ['CODE', 'DESIGN', 'DOCUMENTATION', 'SPECIFICATION'];
		if (!validTypes.includes(artifact.type)) {
			errors.push(`Invalid artifact type: ${artifact.type}`);
		}
	}

	if (errors.length > 0) {
		return {
			success: false,
			error: new Error(
				`Executor response validation failed:\n${errors.join('\n')}`
			),
		};
	}

	return { success: true, value: undefined };
}

/**
 * Convert Executor assumptions to Claims
 * Prepares assumptions for verification
 *
 * @param assumptions Assumptions from Executor
 * @param dialogueId Dialogue ID
 * @param turnId Turn ID where assumptions were surfaced
 * @returns Array of Claim objects
 */
export function assumptionsToClaims(
	assumptions: Assumption[],
	dialogueId: string,
	turnId: number
): Claim[] {
	return assumptions.map((assumption) => {
		const claim: Claim = {
			claim_id: assumption.assumption_id,
			statement: assumption.statement,
			introduced_by: 'EXECUTOR' as Role,
			criticality: assumption.criticality,
			status: ClaimStatus.OPEN,
			dialogue_id: dialogueId,
			turn_id: turnId,
			created_at: new Date().toISOString(),
		};
		if (assumption.assumption_type) {
			claim.assumption_type = assumption.assumption_type as Claim['assumption_type'];
		}
		return claim;
	});
}

// ==================== UNIT-SCOPED EXECUTION (MAKER) ====================

/**
 * System prompt for per-unit execution within a task graph.
 * Constrains the executor to a single task unit's goal, inputs, outputs,
 * and change scope — preventing scope creep beyond the unit boundary.
 */
const EXECUTOR_UNIT_SYSTEM_PROMPT = `You are the EXECUTOR role in the JanumiCode autonomous system, executing a SINGLE TASK UNIT from a decomposed task graph.

# Scope Constraint

You are executing ONE unit of work. You MUST:
- Focus ONLY on the goal described for this unit
- Only modify files within the specified change scope
- Produce ONLY the outputs listed for this unit
- Satisfy ALL postconditions before considering the unit complete
- Do NOT work on tasks belonging to other units in the graph

# Unit Execution Protocol

1. Read the unit goal, inputs, and preconditions carefully
2. Verify preconditions are met before starting
3. Execute the work to achieve the unit goal
4. Verify postconditions are satisfied
5. Ensure all specified observables are present in the result

# Critical Guardrails

## NEVER Exceed Change Scope
- You MUST NOT modify files outside the unit's max_change_scope directory
- You MUST NOT create new files outside the change scope unless explicitly required by the unit goal
- If you discover work needed outside your scope, note it but do NOT execute it

## ALWAYS Satisfy Postconditions
- Every postcondition listed for this unit MUST be true when you finish
- If a postcondition cannot be satisfied, stop and report the issue

## RESPECT Observables and Falsifiers
- Observables are concrete things that should be true after execution
- Falsifiers are conditions that would prove the unit was NOT correctly executed
- Ensure observables are present and falsifiers are absent

Apply all changes to the workspace. Execute the unit goal completely.`;

/**
 * Unit-scoped executor invocation options
 */
export interface UnitExecutorInvocationOptions {
	dialogueId: string;
	unit: TaskUnit;
	context: string; // Pre-built context from makerPlanner builder
	provider: RoleCLIProvider;
	commandId?: string;
}

/**
 * Unit-scoped executor result
 */
export interface UnitExecutorResult {
	success: boolean;
	exitCode: number;
	response: string;
	executionTimeMs: number;
}

/**
 * Invoke Executor for a single task unit within a MAKER task graph.
 * Uses a unit-scoped system prompt that constrains execution to the unit's
 * goal, change scope, and postconditions.
 *
 * @param options Unit executor invocation options
 * @returns Result containing unit execution outcome
 */
export async function invokeExecutorForUnit(
	options: UnitExecutorInvocationOptions
): Promise<Result<UnitExecutorResult>> {
	try {
		const { unit, provider, dialogueId, commandId } = options;

		// Build unit-scoped user prompt with structured unit metadata
		const userPrompt = formatUnitPrompt(unit, options.context);

		// Build stdin content: unit system prompt + unit-specific context
		const stdinContent = buildStdinContent(EXECUTOR_UNIT_SYSTEM_PROMPT, userPrompt);

		// Emit stdin for observability
		if (commandId) {
			emitWorkflowCommand({
				dialogueId,
				commandId,
				action: 'output',
				commandType: 'cli_invocation',
				label: `Executor — Unit: ${unit.label}`,
				summary: '── stdin ──',
				detail: stdinContent,
				lineType: 'stdin',
				timestamp: new Date().toISOString(),
			});
		}

		const startMs = Date.now();

		// Map unit's allowed_tools categories to Claude Code tool names
		const allowedTools = mapUnitToolsToClaudeTools(unit.allowed_tools);

		// ── Permission bridge lifecycle ──
		// Start an HTTP bridge that intercepts Claude Code tool permission requests.
		// The MCP permission server (child process) forwards requests here.
		const permissionBridge = new PermissionBridge();
		const mcpConfigPaths: string[] = [];
		let permissionConfigPath: string | undefined;

		try {
			const permissionPort = await permissionBridge.start({
				allowedTools,
				maxChangeScope: unit.max_change_scope,
				onHumanPrompt: async (request) => {
					const permissionId = (request.input._permissionId as string) || randomUUID();
					// Surface permission card in the Governed Stream webview
					getEventBus().emit('permission:requested', {
						dialogueId,
						permissionId,
						tool: request.tool,
						input: request.input,
					});
					// Wait for user decision via event bus
					return new Promise<PermissionDecision>((resolve) => {
						const bus = getEventBus();
						const unsub = bus.on('permission:decided', (payload) => {
							if (payload.permissionId === permissionId) {
								unsub();
								if (payload.approveAll) {
									permissionBridge.addSessionApproval(request.tool);
								}
								resolve({ approved: payload.approved, reason: payload.reason });
							}
						});
					});
				},
			});

			setActivePermissionBridge(permissionBridge);

			// Build MCP config for the permission server
			// __dirname at runtime is the dist/ directory (extension.js is bundled there),
			// and permissionServer.js is at dist/mcp/permissionServer.js
			const permissionServerPath = path.join(__dirname, 'mcp', 'permissionServer.js');

			// Diagnostic: verify the MCP server script exists
			const fs = await import('node:fs');
			const serverExists = fs.existsSync(permissionServerPath);
			const pbLog = isLoggerInitialized() ? getLogger().child({ component: 'permissionBridge' }) : undefined;
			pbLog?.debug('Permission bridge paths resolved', {
				dirname: __dirname,
				permissionServerPath,
				serverFileExists: serverExists,
				bridgePort: permissionPort,
			});

			const permissionMCPConfig = buildPermissionMCPConfig(permissionServerPath, permissionPort);
			permissionConfigPath = createMCPConfigFile(permissionMCPConfig);
			mcpConfigPaths.push(permissionConfigPath);

			// Diagnostic: log the MCP config file contents
			const mcpLogPath = path.join(require('node:os').tmpdir(), 'janumicode-mcp', 'permission-server.log');
			pbLog?.debug('Permission bridge MCP config created', {
				mcpConfigPath: permissionConfigPath,
				mcpConfig: permissionMCPConfig,
				mcpServerLogFile: mcpLogPath,
			});

			// Invoke with streaming for real-time progress
			const executionResult = await invokeRoleStreaming({
				provider,
				stdinContent,
				allowedTools,
				mcpConfigPaths,
				permissionPromptTool: 'mcp__janumicode-permission__decide_permission',
				onEvent: (event) => {
					emitCLIActivity(dialogueId, {
						...event,
						role: 'EXECUTOR' as Role,
						phase: 'EXECUTE' as import('../types').Phase,
					});
				},
			});

			const elapsedMs = Date.now() - startMs;

			if (!executionResult.success) {
				return {
					success: false,
					error: executionResult.error,
				};
			}

			return {
				success: true,
				value: {
					success: executionResult.value.exitCode === 0,
					exitCode: executionResult.value.exitCode,
					response: executionResult.value.response ?? '',
					executionTimeMs: elapsedMs,
				},
			};
		} finally {
			// Clean up permission bridge and temp config
			setActivePermissionBridge(null);
			await permissionBridge.stop().catch(() => {});
			if (permissionConfigPath) {
				cleanupMCPConfigFile(permissionConfigPath);
			}
		}
	} catch (error) {
		return {
			success: false,
			error:
				error instanceof Error
					? error
					: new Error('Failed to invoke executor for unit'),
		};
	}
}

/**
 * Format the unit-scoped user prompt with structured metadata.
 */
function formatUnitPrompt(unit: TaskUnit, plannerContext: string): string {
	const sections: string[] = [];

	sections.push(`# Task Unit: ${unit.label}`);
	sections.push(`## Goal\n\n${unit.goal}`);

	if (unit.category) {
		sections.push(`## Category\n\n${unit.category}`);
	}

	if (unit.max_change_scope) {
		sections.push(`## Change Scope\n\nYour primary workspace is: \`${unit.max_change_scope}\`\nFocus changes within this directory.`);
	}

	if (unit.inputs.length > 0) {
		sections.push(`## Inputs\n\n${unit.inputs.map((i) => `- ${i}`).join('\n')}`);
	}

	if (unit.outputs.length > 0) {
		sections.push(`## Expected Outputs\n\n${unit.outputs.map((o) => `- ${o}`).join('\n')}`);
	}

	if (unit.preconditions.length > 0) {
		sections.push(`## Preconditions (must be true before you start)\n\n${unit.preconditions.map((p) => `- ${p}`).join('\n')}`);
	}

	if (unit.postconditions.length > 0) {
		sections.push(`## Postconditions (must be true when you finish)\n\n${unit.postconditions.map((p) => `- ${p}`).join('\n')}`);
	}

	if (unit.observables.length > 0) {
		sections.push(`## Observables (concrete evidence of success)\n\n${unit.observables.map((o) => `- ${o}`).join('\n')}`);
	}

	if (unit.falsifiers.length > 0) {
		sections.push(`## Falsifiers (if any of these are true, the unit FAILED)\n\n${unit.falsifiers.map((f) => `- ${f}`).join('\n')}`);
	}

	if (unit.allowed_tools && unit.allowed_tools.length > 0) {
		sections.push(`## Allowed Tools\n\n${unit.allowed_tools.map((t) => `- ${t}`).join('\n')}`);
	}

	if (plannerContext) {
		sections.push(`## Additional Context\n\n${plannerContext}`);
	}

	return sections.join('\n\n');
}

/**
 * Map task-unit allowed_tools categories to Claude Code CLI tool names.
 * Task units use semantic categories like "file_write", "bash", "file_read".
 * Claude Code CLI --allowedTools expects tool names like "Write", "Edit", "Bash", "Read".
 *
 * Always includes read-only tools (Read, Glob, Grep) since every unit needs to
 * inspect the workspace. Write/Edit/Bash are gated on unit declarations.
 */
function mapUnitToolsToClaudeTools(unitTools?: string[]): string[] {
	// Read-only tools are always safe
	const tools = ['Read', 'Glob', 'Grep'];

	if (!unitTools || unitTools.length === 0) {
		return tools;
	}

	for (const t of unitTools) {
		switch (t.toLowerCase()) {
			case 'file_write':
			case 'write':
				tools.push('Write', 'Edit');
				break;
			case 'bash':
			case 'shell':
			case 'command':
				tools.push('Bash');
				break;
			case 'web_search':
				tools.push('WebSearch', 'WebFetch');
				break;
			case 'notebook':
				tools.push('NotebookEdit');
				break;
			case 'file_read':
			case 'read':
				break;  // Read/Glob/Grep always included
			default:
				// Pass through unrecognized names directly — lets the CLI handle them
				tools.push(t);
				break;
		}
	}

	// Deduplicate
	return [...new Set(tools)];
}
