/**
 * Executor Role (Agent)
 * Implements Phase 6.2: Proposal generation, assumption surfacing, and artifact generation
 * This is an LLM-backed agent that executes tasks within verified constraints
 */

import type {
	Result,
	Role,
	Claim,
	ClaimCriticality,
} from '../types';
import { ClaimStatus } from '../types';
import { buildExecutorContext, formatExecutorContext } from '../context';
import type { CompiledContextPack } from '../context/compiler';
import type { RoleCLIProvider } from '../cli/roleCLIProvider';
import { buildStdinContent } from '../cli/types';
import { randomUUID } from 'node:crypto';
import { getLogger, isLoggerInitialized } from '../logging';
import { emitWorkflowCommand } from '../integration/eventBus';
import { updateWorkflowMetadata } from '../workflow/stateMachine';
import { analyzeGoalForMobile } from '../mcp/goalDetector';
import {
	buildMobileSpecialistMCPConfig,
	createMCPConfigFile,
	cleanupMCPConfigFile,
} from '../mcp/mcpConfigManager';
import {
	isMobileSpecialistEnabled,
	getMobileSpecialistConfig,
} from '../config/manager';

/**
 * Executor invocation options
 */
export interface ExecutorInvocationOptions {
	dialogueId: string;
	goal: string;
	tokenBudget: number;
	provider: RoleCLIProvider;
	temperature?: number;
	includeHistoricalFindings?: boolean;
	commandId?: string;
}

/**
 * Assumption surfaced by Executor
 */
export interface Assumption {
	assumption_id: string;
	statement: string;
	criticality: ClaimCriticality;
	rationale: string;
}

/**
 * Artifact generated by Executor
 */
export interface Artifact {
	artifact_id: string;
	type: 'CODE' | 'DESIGN' | 'DOCUMENTATION' | 'SPECIFICATION';
	content: string;
	description: string;
}

/**
 * Executor response
 */
export interface ExecutorResponse {
	proposal: string;
	assumptions: Assumption[];
	artifacts: Artifact[];
	constraint_adherence_notes: string[];
	raw_response: string;
}

/**
 * System prompt template for Executor
 */
const EXECUTOR_SYSTEM_PROMPT = `You are the EXECUTOR role in the JanumiCode autonomous system.

# Your Responsibilities

1. **Propose Solutions**: Generate concrete, actionable proposals with specific implementation steps
2. **Surface Assumptions**: Identify and articulate all assumptions in your proposal as claims
3. **Generate Artifacts**: Create code, designs, documentation, or specifications as needed
4. **Adhere to Constraints**: Strictly follow all constraints in the constraint manifest
5. **Defer to Verification**: Accept verifier verdicts without challenge

# Critical Guardrails

## NEVER Override Verification
- You MUST NOT challenge or reinterpret verifier verdicts
- If a claim is DISPROVED or UNKNOWN, you MUST NOT proceed with dependent actions
- If blocked by verification, surface this as a gate condition

## NEVER Invent Constraints
- You MUST ONLY reference constraints from the provided constraint manifest
- You MUST NOT introduce new constraints or interpret constraints creatively
- If a constraint is unclear, surface this as an assumption requiring verification

## ALWAYS Surface Assumptions
- Every assumption in your proposal MUST be surfaced as an explicit claim
- Mark assumptions with appropriate criticality (CRITICAL or NON_CRITICAL)
- Provide clear rationale for why each assumption matters

# Response Format

Your response MUST be valid JSON with this exact structure:

\`\`\`json
{
  "proposal": "A concrete, step-by-step implementation plan. Include specific file paths, function signatures, data structures, architectural decisions, and code patterns. Do NOT write a high-level summary or phase overview — write the actual technical blueprint that a developer could follow to implement the solution.",
  "assumptions": [
    {
      "statement": "Assumption statement",
      "criticality": "CRITICAL" | "NON_CRITICAL",
      "rationale": "Why this assumption matters"
    }
  ],
  "artifacts": [
    {
      "type": "CODE" | "DESIGN" | "DOCUMENTATION" | "SPECIFICATION",
      "content": "Artifact content...",
      "description": "What this artifact does"
    }
  ],
  "constraint_adherence_notes": [
    "How this proposal adheres to constraint X",
    "Why constraint Y is satisfied by approach Z"
  ]
}
\`\`\`

IMPORTANT: The "proposal" field is the PRIMARY deliverable. It must contain the full, concrete technical plan — not a summary, not a description of phases, not meta-commentary about what you will do. Write the actual implementation steps with specifics.

## NEVER Use Temporal References
- This plan will be executed by AI agents, not humans. Do NOT express milestones, roadmaps, or sequencing in temporal terms (e.g., "Week 1", "Day 3", "Sprint 2", "Phase 1 (2 weeks)")
- Instead, express implementation sequences as logical execution steps ordered by dependency and optimal build order
- Use labels like "Step 1", "Stage A", or descriptive names (e.g., "Foundation", "Core API", "Integration Layer") — never time-based labels
- Do NOT estimate durations, timelines, or delivery dates

# Context

You will receive:
- **Goal**: The objective you need to achieve
- **Constraint Manifest**: Constraints you MUST follow
- **Active Claims**: Current claims and their verification status
- **Verifier Verdicts**: Verification results you MUST respect
- **Human Decisions**: Human authority decisions that override all else
- **Historical Findings**: Relevant past decisions and precedents

Process this context carefully and generate your response in the required JSON format.`;

/**
 * System prompt supplement appended when mobile-specialist MCP tools are injected.
 */
const MOBILE_SPECIALIST_PROMPT_SUPPLEMENT = `

# Mobile Development Specialist Tools Available

You have access to a mobile development specialist LLM via the \`query_mobile_specialist\` tool.
Use it when you need:
- iOS/Android platform-specific code generation
- Mobile architecture diagnosis or debugging
- ARKit, SwiftUI, Jetpack Compose, or other framework-specific guidance
- Platform constraint validation

You also have access to:
- \`get_mobile_guidelines\` — curated iOS/Android best practices and code patterns
- \`analyze_mobile_project\` — detect mobile project type from workspace structure

ALWAYS use the specialist tool for mobile-specific code rather than generating it from general knowledge alone.`;

/**
 * Invoke Executor agent
 * Generates proposals, surfaces assumptions, and creates artifacts
 *
 * @param options Invocation options
 * @returns Result containing Executor response
 */
export async function invokeExecutor(
	options: ExecutorInvocationOptions
): Promise<Result<ExecutorResponse>> {
	try {
		// Build Executor context pack
		const contextResult = await buildExecutorContext({
			dialogueId: options.dialogueId,
			goal: options.goal,
			tokenBudget: options.tokenBudget,
			includeHistoricalFindings: options.includeHistoricalFindings,
		});

		if (!contextResult.success) {
			return contextResult;
		}

		const context = contextResult.value;

		// Check for blocking conditions
		const blockingCheck = checkBlockingConditions(context);
		if (!blockingCheck.canProceed) {
			return {
				success: false,
				error: new Error(
					`Executor blocked: ${blockingCheck.reason}\nBlocking claims: ${blockingCheck.blockingClaims.join(', ')}`
				),
			};
		}

		// Format context for CLI invocation
		const formattedContext = formatExecutorContext(context);

		// ── Mobile specialist MCP injection ──
		// Detect whether the goal involves mobile development and inject MCP tools
		const goalAnalysis = analyzeGoalForMobile(options.goal);
		const useMobileSpecialist = goalAnalysis.isMobileRelated && isMobileSpecialistEnabled();
		let mcpConfigPath: string | undefined;

		let systemPrompt = EXECUTOR_SYSTEM_PROMPT;
		if (useMobileSpecialist) {
			systemPrompt += MOBILE_SPECIALIST_PROMPT_SUPPLEMENT;

			const specialistConfig = getMobileSpecialistConfig();
			if (specialistConfig.baseUrl && specialistConfig.serverPath) {
				const mcpConfig = buildMobileSpecialistMCPConfig(
					specialistConfig.serverPath,
					specialistConfig.baseUrl,
					specialistConfig.apiKey,
					specialistConfig.model,
				);
				mcpConfigPath = createMCPConfigFile(mcpConfig);
			}
		}

		// Build stdin content: system prompt + formatted context
		const stdinContent = buildStdinContent(systemPrompt, formattedContext);

		// Emit full stdin content for observability (expandable in command block UI)
		if (options.commandId) {
			emitWorkflowCommand({
				dialogueId: options.dialogueId,
				commandId: options.commandId,
				action: 'output',
				commandType: 'role_invocation',
				label: 'Executor',
				summary: '── stdin ──',
				detail: stdinContent,
				lineType: 'stdin',
				timestamp: new Date().toISOString(),
			});
		}

		// Invoke via RoleCLIProvider (CLI tool or API adapter)
		let cliResult;
		try {
			cliResult = await options.provider.invoke({
				stdinContent,
				outputFormat: 'json',
				mcpConfigPaths: mcpConfigPath ? [mcpConfigPath] : undefined,
			});
		} finally {
			// Clean up temp MCP config file regardless of outcome
			if (mcpConfigPath) {
				cleanupMCPConfigFile(mcpConfigPath);
			}
		}

		if (!cliResult.success) {
			return cliResult;
		}

		const rawResponse = cliResult.value.response;

		// Cache raw output in metadata BEFORE parsing — enables retry on parse failure
		updateWorkflowMetadata(options.dialogueId, {
			cachedRawCliOutput: rawResponse,
		});

		// Parse response
		const parseResult = parseExecutorResponse(rawResponse);

		if (!parseResult.success) {
			// Emit raw response to command block for observability
			if (options.commandId) {
				emitWorkflowCommand({
					dialogueId: options.dialogueId,
					commandId: options.commandId,
					action: 'output',
					commandType: 'role_invocation',
					label: 'Executor',
					summary: `── Raw Response (parse failed) ──`,
					detail: rawResponse,
					timestamp: new Date().toISOString(),
				});
			}
			return parseResult;
		}

		// Validate response
		const validationResult = validateExecutorResponse(
			parseResult.value,
			context
		);

		if (!validationResult.success) {
			return validationResult;
		}

		// Add IDs to assumptions and artifacts
		const response = parseResult.value;
		response.assumptions = response.assumptions.map((a) => ({
			...a,
			assumption_id: randomUUID(),
		}));
		response.artifacts = response.artifacts.map((a) => ({
			...a,
			artifact_id: randomUUID(),
		}));

		return { success: true, value: response };
	} catch (error) {
		return {
			success: false,
			error:
				error instanceof Error
					? error
					: new Error('Failed to invoke Executor'),
		};
	}
}

/**
 * Re-parse a cached raw executor response.
 * Used on retry to avoid re-invoking the CLI when the raw output is already cached.
 * Skips full context-aware validation (context is not available on retry).
 */
export function reparseExecutorResponse(
	rawResponse: string,
): Result<ExecutorResponse> {
	const parseResult = parseExecutorResponse(rawResponse);
	if (!parseResult.success) {
		return parseResult;
	}

	const response = parseResult.value;
	response.assumptions = response.assumptions.map((a) => ({
		...a,
		assumption_id: a.assumption_id || randomUUID(),
	}));
	response.artifacts = response.artifacts.map((a) => ({
		...a,
		artifact_id: a.artifact_id || randomUUID(),
	}));

	return { success: true, value: response };
}

/**
 * Check for blocking conditions
 * Executor MUST NOT proceed if critical claims are DISPROVED or UNKNOWN
 */
function checkBlockingConditions(context: CompiledContextPack): {
	canProceed: boolean;
	reason?: string;
	blockingClaims: string[];
} {
	const blockingClaims = context.active_claims.filter(
		(claim) =>
			claim.criticality === 'CRITICAL' &&
			(claim.status === 'DISPROVED' || claim.status === 'UNKNOWN')
	);

	if (blockingClaims.length > 0) {
		return {
			canProceed: false,
			reason: `Found ${blockingClaims.length} blocking critical claims (DISPROVED or UNKNOWN)`,
			blockingClaims: blockingClaims.map((c) => c.claim_id),
		};
	}

	return {
		canProceed: true,
		blockingClaims: [],
	};
}

/**
 * Parse Executor response from LLM
 */
function parseExecutorResponse(
	rawResponse: string
): Result<ExecutorResponse> {
	const logger = isLoggerInitialized()
		? getLogger().child({ component: 'role:executor', fn: 'parseExecutorResponse' })
		: undefined;

	logger?.debug('Attempting to parse Executor response', {
		rawResponseLength: rawResponse.length,
		rawResponsePreview: rawResponse.substring(0, 500),
	});

	try {
		// Extract JSON from response — multiple strategies for robustness
		const jsonStr = extractJsonFromResponse(rawResponse);

		logger?.debug('Extracted JSON string, attempting JSON.parse', {
			jsonStrLength: jsonStr.length,
			jsonStrTail: jsonStr.substring(Math.max(0, jsonStr.length - 300)),
		});

		const parsed = JSON.parse(jsonStr);

		// Validate structure
		if (!parsed.proposal || typeof parsed.proposal !== 'string') {
			return {
				success: false,
				error: new Error('Executor response missing or invalid proposal'),
			};
		}

		if (!Array.isArray(parsed.assumptions)) {
			return {
				success: false,
				error: new Error('Executor response missing or invalid assumptions'),
			};
		}

		if (!Array.isArray(parsed.artifacts)) {
			return {
				success: false,
				error: new Error('Executor response missing or invalid artifacts'),
			};
		}

		if (!Array.isArray(parsed.constraint_adherence_notes)) {
			return {
				success: false,
				error: new Error(
					'Executor response missing or invalid constraint_adherence_notes'
				),
			};
		}

		const response: ExecutorResponse = {
			proposal: parsed.proposal,
			assumptions: parsed.assumptions,
			artifacts: parsed.artifacts,
			constraint_adherence_notes: parsed.constraint_adherence_notes,
			raw_response: rawResponse,
		};

		return { success: true, value: response };
	} catch (error) {
		const errMsg = error instanceof Error ? error.message : 'Failed to parse Executor response';
		logger?.error('Failed to parse Executor response JSON', {
			errorMessage: errMsg,
			rawResponseLength: rawResponse.length,
			rawResponse,
		});
		return {
			success: false,
			error:
				error instanceof Error
					? error
					: new Error('Failed to parse Executor response'),
		};
	}
}

/**
 * Extract a JSON object string from a raw LLM response.
 * Handles markdown code fences, surrounding prose, and braces in trailing text.
 *
 * Strategy order:
 *   1. Direct JSON.parse of trimmed input (already clean JSON)
 *   2. Markdown code fence extraction (```json ... ```)
 *   3. Brace-balanced extraction (first { to its matching }, respecting strings)
 *   4. Fallback: return trimmed input as-is and let the caller's JSON.parse report the error
 */
function extractJsonFromResponse(rawResponse: string): string {
	const trimmed = rawResponse.trim();

	return tryDirectParse(trimmed)
		?? tryFenceExtraction(trimmed)
		?? extractBalancedJsonObject(trimmed)
		?? trimmed;
}

/** Return the text if it's already valid JSON, otherwise null. */
function tryDirectParse(text: string): string | null {
	try { JSON.parse(text); return text; } catch { return null; }
}

/** Extract JSON from a markdown code fence, with balanced-brace fallback. */
function tryFenceExtraction(text: string): string | null {
	const m = /```(?:json)?\s*([\s\S]*?)\s*```/.exec(text);
	if (!m) { return null; }

	const content = m[1].trim();
	return tryDirectParse(content) ?? extractBalancedJsonObject(content);
}

/**
 * Extract the first balanced JSON object from a string.
 * Finds the first '{' and walks forward, tracking brace depth while
 * respecting JSON string boundaries (so braces inside strings don't count).
 * Returns the substring from the opening '{' to its matching '}', or null.
 */
function extractBalancedJsonObject(text: string): string | null {
	const start = text.indexOf('{');
	if (start === -1) { return null; }

	const end = findMatchingBrace(text, start);
	return end === -1 ? null : text.substring(start, end + 1);
}

/** Walk from the '{' at `start` and return the index of its matching '}', or -1. */
function findMatchingBrace(text: string, start: number): number {
	let depth = 0;
	let inString = false;
	let skip = false;

	for (let i = start; i < text.length; i++) {
		const ch = text[i];

		// Previous char was a backslash inside a string — skip this char
		if (skip) { skip = false; continue; }

		if (inString) {
			skip = ch === '\\';
			if (ch === '"') { inString = false; }
			continue;
		}
		if (ch === '"') { inString = true; continue; }
		if (ch === '{') { depth++; }
		if (ch === '}' && --depth === 0) { return i; }
	}

	return -1;
}

/**
 * Validate Executor response
 * Ensure guardrails are not violated
 */
function validateExecutorResponse(
	response: ExecutorResponse,
	context: CompiledContextPack
): Result<void> {
	const errors: string[] = [];

	// Check for constraint invention (references to non-existent constraints)
	// constraint_manifest is optional — its absence is normal for new dialogues
	const constraintManifest = context.constraint_manifest;
	if (!constraintManifest) {
		if (isLoggerInitialized()) {
			getLogger().child({ component: 'role:executor' }).debug('No constraint manifest present — skipping adherence validation');
		}
	}

	// Check that proposal doesn't challenge verifier verdicts
	const disproved = context.active_claims.filter(
		(c) => c.status === 'DISPROVED'
	);
	for (const claim of disproved) {
		// Check if proposal mentions this claim positively
		if (
			response.proposal.toLowerCase().includes(claim.statement.toLowerCase())
		) {
			// This is a simplified check - in production, would use more sophisticated NLP
			errors.push(
				`Proposal may be attempting to work around DISPROVED claim: ${claim.claim_id}`
			);
		}
	}

	// Validate assumption structure
	for (const assumption of response.assumptions) {
		if (!assumption.statement || !assumption.criticality || !assumption.rationale) {
			errors.push(
				`Invalid assumption structure: ${JSON.stringify(assumption)}`
			);
		}

		if (
			assumption.criticality !== 'CRITICAL' &&
			assumption.criticality !== 'NON_CRITICAL'
		) {
			errors.push(
				`Invalid criticality for assumption: ${assumption.criticality}`
			);
		}
	}

	// Validate artifact structure
	for (const artifact of response.artifacts) {
		if (!artifact.type || !artifact.content || !artifact.description) {
			errors.push(`Invalid artifact structure: ${JSON.stringify(artifact)}`);
		}

		const validTypes = ['CODE', 'DESIGN', 'DOCUMENTATION', 'SPECIFICATION'];
		if (!validTypes.includes(artifact.type)) {
			errors.push(`Invalid artifact type: ${artifact.type}`);
		}
	}

	if (errors.length > 0) {
		return {
			success: false,
			error: new Error(
				`Executor response validation failed:\n${errors.join('\n')}`
			),
		};
	}

	return { success: true, value: undefined };
}

/**
 * Convert Executor assumptions to Claims
 * Prepares assumptions for verification
 *
 * @param assumptions Assumptions from Executor
 * @param dialogueId Dialogue ID
 * @param turnId Turn ID where assumptions were surfaced
 * @returns Array of Claim objects
 */
export function assumptionsToClaims(
	assumptions: Assumption[],
	dialogueId: string,
	turnId: number
): Claim[] {
	return assumptions.map((assumption) => ({
		claim_id: assumption.assumption_id,
		statement: assumption.statement,
		introduced_by: 'EXECUTOR' as Role,
		criticality: assumption.criticality,
		status: ClaimStatus.OPEN,
		dialogue_id: dialogueId,
		turn_id: turnId,
		created_at: new Date().toISOString(),
	}));
}
