import type { LensPhaseManifest } from '../../lib/orchestrator/types.js';
import { SHARED_AGENTS } from '../sharedAgents.js';

export const AUTHORITY_VERIFICATION_LENS_ID = 'authority_verification_lens';

export const authorityVerificationManifest: LensPhaseManifest = {
  lensId: AUTHORITY_VERIFICATION_LENS_ID,
  lensVersion: 'v1',
  practiceArea: 'authority_verification',
  applicableJurisdictions: ['MD', 'VA', 'PA', 'DC', 'US'],
  states: [
    {
      stateId: 'AuthorityIngest',
      required: true,
      predecessors: [],
      permittedAgents: [SHARED_AGENTS.authorityRetrieve],
      inputSchema: 'AuthorityIngestInput.v1',
      outputSchema: 'AuthorityIngestOutput.v1',
      validators: [],
      escalationConditions: [],
      clvScope: ['clv.core.authority.v1', 'clv.core.citation.v1'],
      artifactsProduced: [],
    },
    {
      stateId: 'MechanicalCheck',
      required: true,
      predecessors: ['AuthorityIngest'],
      permittedAgents: [SHARED_AGENTS.authorityVerification],
      inputSchema: 'MechanicalCheckInput.v1',
      outputSchema: 'MechanicalCheckOutput.v1',
      validators: [],
      escalationConditions: [],
      clvScope: ['clv.core.source_located.v1', 'clv.core.quote_matched.v1'],
      artifactsProduced: [],
    },
    {
      stateId: 'MachineAssessedSupport',
      required: true,
      predecessors: ['MechanicalCheck'],
      permittedAgents: [SHARED_AGENTS.authorityVerification],
      inputSchema: 'MachineAssessedSupportInput.v1',
      outputSchema: 'MachineAssessedSupportOutput.v1',
      validators: [],
      escalationConditions: [],
      clvScope: ['clv.core.machine_assessed_support.v1'],
      artifactsProduced: [],
    },
    {
      stateId: 'CitatorLookup',
      required: false,
      predecessors: ['MachineAssessedSupport'],
      permittedAgents: [SHARED_AGENTS.authorityVerification],
      inputSchema: 'CitatorLookupInput.v1',
      outputSchema: 'CitatorLookupOutput.v1',
      validators: [],
      escalationConditions: [],
      clvScope: ['clv.core.citator_status.v1'],
      artifactsProduced: [],
    },
    {
      stateId: 'VerificationLabel',
      required: true,
      predecessors: ['MachineAssessedSupport'],
      permittedAgents: [SHARED_AGENTS.authorityVerification],
      inputSchema: 'VerificationLabelInput.v1',
      outputSchema: 'VerificationLabelOutput.v1',
      validators: [],
      escalationConditions: [],
      clvScope: ['clv.core.attorney_confirmation_required.v1'],
      artifactsProduced: ['authority_verification_packet'],
    },
  ],
  requiredArtifacts: [{ artifactType: 'authority_verification_packet', schema: 'VerificationLabelOutput.v1' }],
  validators: [],
  escalationTriggers: [],
  releasePolicies: [],
  clvBindings: [
    'clv.core.authority.v1',
    'clv.core.citation.v1',
    'clv.core.source_located.v1',
    'clv.core.quote_matched.v1',
    'clv.core.machine_assessed_support.v1',
    'clv.core.citator_status.v1',
    'clv.core.attorney_confirmation_required.v1',
  ],
  dependencies: [],
};
