// JAN-EXECREM WP-11 — the PURE half of F-01 limb B: `structuredResultHasContent` and `unassessableAiContentBlock`.
//
// These two predicates decide whether AI-produced work may enter the governed stream with nothing to assess. They
// take no `ctx`, so every cell is checkable in isolation — and a pure predicate has no excuse for an untested one.
// The live composition (an engine dispatch actually being refused) is `execution-floor-zero-subject.test.ts`; this
// file is where the emptiness LINE is pinned, because that line is the whole over-refusal risk: draw it one way and
// the reference seed and the demo both stop working, draw it another and an AI step ships content past the floor.
import { describe, expect, it } from 'vitest';
import { structuredResultHasContent, unassessableAiContentBlock } from './floor-gate.js';

describe('WP-11 — structuredResultHasContent: the emptiness line, pinned', () => {
	// CONTENT: an object with >= 1 own key, an array with length > 0, or a string with a non-whitespace character.
	it.each([
		['a populated object', { architecture: 'generated by the model' }],
		['an object whose only value is falsy', { result: null }],
		['a nested empty object still has a key', { inner: {} }],
		['a one-element array', ['x']],
		['an array of empty objects', [{}]],
		['a non-empty string', 'the model said something'],
		['a string that is only punctuation', '.']
	])('CONTENT: %s', (_label, value) => {
		expect(structuredResultHasContent(value)).toBe(true);
	});

	// EMPTY. `{}` is the load-bearing row: the reference seed and the demo both send it, and a stricter reading of
	// "has content" would refuse them both — the over-refusal this fix is most at risk of.
	it.each([
		['the empty object — the seed and the demo both send this', {}],
		['the empty array', []],
		['the empty string', ''],
		['a whitespace-only string', '   \n\t '],
		['undefined', undefined],
		['null', null],
		// The design called `0` and `false` CONTENT while calling `''` EMPTY — an arbitrary line a truth table would
		// then enshrine. A bare scalar names no field saying what it IS, so it cannot be individuated as a
		// downstream-consumable result under §8.4 L844 anyway: refusing on one would name no content to record.
		['the number zero', 0],
		['a non-zero number', 42],
		['false', false],
		['true', true]
	])('EMPTY: %s', (_label, value) => {
		expect(structuredResultHasContent(value)).toBe(false);
	});
});

describe('WP-11 — unassessableAiContentBlock: the exhaustive truth table', () => {
	// THREE inputs, so EIGHT cells — enumerated, not sampled. The designed interface carried a fourth
	// (`explicitNoOutput`); it is absent because composed with WP-11's RPH-EXE-006 fix a zero-subject completion
	// already IMPLIES the assertion was made, so the fourth input could not change any answer. Sixteen cells over a
	// parameter the predicate ignores would be eight duplicated rows presented as coverage.
	const CELLS: ReadonlyArray<readonly [boolean, number, boolean, boolean]> = [
		// aiProduced, subjectCount, hasContent, blocked
		[true, 0, true, true], // THE DEFECT: AI work, nothing assessable, and it shipped something
		[true, 0, false, false], // a genuine empty attempt (Coding Agent Guide L1964) — must NOT be over-refused
		[true, 1, true, false], // has a subject: the per-subject floor loop below judges it, this rule steps aside
		[true, 1, false, false],
		[false, 0, true, false], // a human step owes no Reasoning Review; §8.4 step 3 is AI-scoped
		[false, 0, false, false],
		[false, 1, true, false],
		[false, 1, false, false]
	];

	it.each(CELLS)(
		'aiProduced=%s subjectCount=%d hasContent=%s -> blocked=%s',
		(aiProduced, subjectCount, structuredResultHasContentFlag, blocked) => {
			const r = unassessableAiContentBlock({
				aiProduced,
				subjectCount,
				structuredResultHasContent: structuredResultHasContentFlag
			});
			expect(
				r === null,
				JSON.stringify({ aiProduced, subjectCount, structuredResultHasContentFlag })
			).toBe(!blocked);
		}
	);

	it('exactly ONE of the eight cells blocks — the rule is as narrow as it claims', () => {
		const blocking = CELLS.filter(([, , , blocked]) => blocked);
		expect(blocking).toHaveLength(1);
	});

	it('a multi-subject completion is never blocked by this rule, however much content it carries', () => {
		// Guards against a `subjectCount === 0` -> `subjectCount >= 0` slip, which would refuse every AI completion.
		for (const subjectCount of [1, 2, 7])
			expect(
				unassessableAiContentBlock({
					aiProduced: true,
					subjectCount,
					structuredResultHasContent: true
				})
			).toBeNull();
	});
});
