import type { LensPhaseManifest } from '../../lib/orchestrator/types.js';
import { SHARED_AGENTS } from '../sharedAgents.js';

export const CLIENT_ADVICE_DRAFT_LENS_ID = 'client_advice_draft_lens';

export const clientAdviceDraftManifest: LensPhaseManifest = {
  lensId: CLIENT_ADVICE_DRAFT_LENS_ID,
  lensVersion: 'v1',
  practiceArea: 'client_advice',
  applicableJurisdictions: ['MD', 'VA', 'PA', 'DC'],
  states: [
    {
      stateId: 'ClientQuestionNormalize',
      required: true,
      predecessors: [],
      permittedAgents: [SHARED_AGENTS.intakeNormalize],
      inputSchema: 'ClientQuestionInput.v1',
      outputSchema: 'ClientQuestionNormalized.v1',
      validators: [],
      escalationConditions: [],
      clvScope: ['clv.core.client.v1', 'clv.core.privilege_attorney_client.v1'],
      artifactsProduced: [],
    },
    {
      stateId: 'JurisdictionCapture',
      required: true,
      predecessors: ['ClientQuestionNormalize'],
      permittedAgents: [SHARED_AGENTS.jurisdictionCapture],
      inputSchema: 'JurisdictionCaptureInput.v1',
      outputSchema: 'JurisdictionCaptureOutput.v1',
      validators: [],
      escalationConditions: [],
      clvScope: ['clv.core.matter.v1'],
      artifactsProduced: [],
    },
    {
      stateId: 'LegalConclusionDraft',
      required: true,
      predecessors: ['JurisdictionCapture'],
      permittedAgents: [SHARED_AGENTS.conclusionDraft],
      inputSchema: 'LegalConclusionInput.v1',
      outputSchema: 'LegalConclusionOutput.v1',
      validators: [],
      escalationConditions: [],
      clvScope: ['clv.core.conclusion.v1'],
      artifactsProduced: [],
    },
    {
      stateId: 'ClientAdviceDraft',
      required: true,
      predecessors: ['LegalConclusionDraft'],
      permittedAgents: [SHARED_AGENTS.clientAdviceDraft],
      inputSchema: 'ClientAdviceDraftInput.v1',
      outputSchema: 'ClientAdviceDraftOutput.v1',
      validators: [],
      escalationConditions: [],
      clvScope: ['clv.core.client.v1', 'clv.core.privilege_attorney_client.v1'],
      artifactsProduced: ['client_advice_draft'],
    },
    {
      stateId: 'ReleaseStatusDetermine',
      required: true,
      predecessors: ['ClientAdviceDraft'],
      permittedAgents: [SHARED_AGENTS.releaseStatusDetermine],
      inputSchema: 'ReleaseStatusInput.v1',
      outputSchema: 'ReleaseStatusOutput.v1',
      validators: [],
      escalationConditions: [],
      clvScope: ['clv.core.release.v1', 'clv.core.gate.v1'],
      artifactsProduced: [],
    },
  ],
  requiredArtifacts: [{ artifactType: 'client_advice_draft', schema: 'ClientAdviceDraftOutput.v1' }],
  validators: [],
  escalationTriggers: [],
  releasePolicies: [],
  clvBindings: [
    'clv.core.matter.v1',
    'clv.core.client.v1',
    'clv.core.privilege_attorney_client.v1',
    'clv.core.conclusion.v1',
    'clv.core.release.v1',
    'clv.core.gate.v1',
  ],
  dependencies: [],
};
