-- CreateEnum
CREATE TYPE "CaseNoteType" AS ENUM ('GENERAL', 'CLARIFICATION_REQUEST', 'CLARIFICATION_RESPONSE', 'DECISION_RATIONALE');

-- AlterTable
ALTER TABLE "case_notes" ADD COLUMN     "note_type" "CaseNoteType" NOT NULL DEFAULT 'GENERAL';
